### ISSUE TITLE
🐛 Bug: Mis-linked page

### ISSUE THREAD

**Issue by IyaadDev** [json-schema-org/website#1012]
### Describe the bug

https://json-schema.org/docs

"Help us make our docs great!
At JSON Schema, we value docs contributions as much as every other type of contribution!

[Edit this page on Github](https://github.com/json-schema-org/website/blob/main/pages/docs/_index.md)
[Learn how to contribute](https://github.com/json-schema-org/website/blob/main/CONTRIBUTING.md)"

Edt this page on github returns 404

### Steps To Reproduce

https://json-schema.org/docs

"Help us make our docs great!
At JSON Schema, we value docs contributions as much as every other type of contribution!

[Edit this page on Github](https://github.com/json-schema-org/website/blob/main/pages/docs/_index.md)
[Learn how to contribute](https://github.com/json-schema-org/website/blob/main/CONTRIBUTING.md)"

Edt this page on github returns 404

### Expected Behavior

https://json-schema.org/docs

"Help us make our docs great!
At JSON Schema, we value docs contributions as much as every other type of contribution!

[Edit this page on Github](https://github.com/json-schema-org/website/blob/main/pages/docs/_index.md)
[Learn how to contribute](https://github.com/json-schema-org/website/blob/main/CONTRIBUTING.md)"

Edt this page on github returns 404

### Screenshots

https://json-schema.org/docs

"Help us make our docs great!
At JSON Schema, we value docs contributions as much as every other type of contribution!

[Edit this page on Github](https://github.com/json-schema-org/website/blob/main/pages/docs/_index.md)
[Learn how to contribute](https://github.com/json-schema-org/website/blob/main/CONTRIBUTING.md)"

Edt this page on github returns 404

### Device Information [optional]

```markdown
OS: Ubuntu 20.04
Browser: chrome
version: 22
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by DarhkVoyd** [comment]
Thank you for reporting this issue! It seems the bug is caused by passing `_indexPage` as `markdownFile`, even though the page isn't generated from a markdown file. Removing that reference should resolve the problem. If you'd like, feel free to take this on and submit a fix!

**Comment by IyaadDev** [comment]
Alright, I guess I will take this on and submit a pr! Thanks!

**Comment by IyaadDev** [comment]
This should fix the problem
