### ISSUE TITLE
🐛 Bug: Alignment issues and banner image missing at latest GSoD blog card

### ISSUE THREAD

**Issue by DhairyaMajmudar** [json-schema-org/website#1019]
### Describe the bug

The blog preview card of JSON Schema Google Season of Docs program'24 has the following bugs:

1. The banner image is missing just as other cards have.
2. Alignment problems with avatar images and text.  

### Steps To Reproduce

1.  Vist https://json-schema.org/blog.
2. Notice the very first card of the grid.

### Expected Behavior

It should be like below image

![image](https://github.com/user-attachments/assets/3157826e-e0d7-44d7-b079-0ac8514599d0)

### Screenshots

![image](https://github.com/user-attachments/assets/f6f244f8-35e6-46f0-82ef-62b7f311772e)

### Device Information [optional]

```markdown
- OS: Linux (Debian)
- Browser: Firefox
- version: Latest
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by mishraRj** [comment]
Hello sir,
I am totally new to Open source programming and grinding myself hard for Hactober fest. I would like to work on this issue.
Being a senior to me, Can you plz suggest or guide me with something for this issue. I will really appreciate your guidance sir.

**Comment by DhairyaMajmudar** [comment]
Hi, Rajat welcome to the community 

-> Please go through the repo. [setup guide](https://github.com/json-schema-org/website/blob/main/INSTALLATION.md) from here you can install and run the website in our local PC.

-> After doing so you can use the VSCode search feature and browser inspect tools to search the file from where the mentioned issue is originated. 

Try to figure out the things by above ways, if you are stuck on anything feel free to ask on JSON Schema [Slack ](https://json-schema.slack.com/ssb/redirect)

Best Wishes! Happy Coding 🚀

**Comment by arpitkuriyal** [comment]
i am also new to open source and I see someone is already working on this issue, but I’m interested in contributing as well. If there’s any way I can help?

**Comment by mishraRj** [comment]
Hello @DhairyaMajmudar  can you plz check your DM box on Slack... I really need your guidance lil bit bcuz I am totally new to Open Source projects. 
Thankyou!

**Comment by mishraRj** [comment]
> i am also new to open source and I see someone is already working on this issue, but I’m interested in contributing as well. If there’s any way I can help?

you can work on this, I know only HTML, CSS and JS for now... but this issue needs more skills than these.

**Comment by Ritesh2351235** [comment]
Hey @DhairyaMajmudar 
I was working on this issue and discovered that the image was missing due to the number of authors on the page. I fixed it by listing all the authors below their avatars.
<img width="1470" alt="Screenshot 2024-10-17 at 10 22 53 AM" src="https://github.com/user-attachments/assets/ef803e4f-be7e-4256-be97-be2e10415963">


I also have an alternate solution 
we can just list the top two authors on the blog component which will align and look clean compared to the other solution

**Comment by Ritesh2351235** [comment]
@DhairyaMajmudar Can you assign me this issue ?

**Comment by DhairyaMajmudar** [comment]
> @DhairyaMajmudar Can you assign me this issue ?

Assigned to you, looking forward for your PR

**Comment by Ritesh2351235** [comment]
@DhairyaMajmudar I have made a PR but the website built through cloudfare has some different output compared to the changes I have made locally.
Can use please take a look at it
