### ISSUE TITLE
Improve the CI/CD pipeline to avoid broken links

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#103]
After the site roll-out we found some broken links. In order to avoid this in the future we should improve the merge checks:

- [ ] Add workflow to validate broken links.

GA Example to validate links:
https://github.com/openjs-foundation/cross-project-council/actions/runs/6412837418/workflow

**Comment by Min2who** [comment]
Hey @benjagm would love to work on this

**Comment by ayushnau** [comment]
@benjagm can I right the tests for it using puppeteer. which we can run pipeline.

**Comment by praveen-rikhari** [comment]
Hey @ayushnau @benjagm is this available?? I can add this in the CI if it's still not worked on

**Comment by praveen-rikhari** [comment]
I see we have some work already done in #297 to add this in the CI, and we need to first make sure if we have any broken links already on the website and fix them, right @benjagm??

**Comment by benjagm** [comment]
We have some work in progress for the broken links but the whole issue is not going to be available as it is. This will be developed with the selected contributor during the program.

Considering that we have some small tasks in progress I am going to increase the scope of this issue.
