### ISSUE TITLE
✨ Enhancement: Improve the design of the Spec versions page

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#1030]
### Is your feature request related to a problem? Please describe

Recently we released a new structure for the Specification docs and now we have a page with all the information for each spec version (See picture of the menu, all sections under versions):
![Screenshot 2024-10-17 at 09 32 52](https://github.com/user-attachments/assets/e244ee5c-a2d3-4956-b54f-5661c0b1234f)

We focused on documentation, however, the design of those pages has a wide range of improvements. See:
![Screenshot 2024-10-17 at 09 34 10](https://github.com/user-attachments/assets/a4e0fd93-ca70-4155-bf4b-5c7a5d2b4ae3)

We'd like to have something with a better UX. You can find inspiration in the work done by @jviotti in Learn JSON Schema here: https://www.learnjsonschema.com/2020-12/

### Describe the solution you'd like

The goal of this issue is to create and implement a new design proposal. Focusing on the header of the page.

### Are you working on this?

No

**Comment by rishabhknowss** [comment]
Hello @benjagm , I think I have now got a good understanding of the repo. Therefore, I would like to work on this issue as well.( i enjoy working on Nextjs xd )

**Comment by DhairyaMajmudar** [comment]
Assigned to you @rishabhknowss, looking forward for your PR 🚀

**Comment by arpitkuriyal** [comment]
can I also contribute to this . I have also make the prototype for the UX 
<img width="905" alt="contentPage" src="https://github.com/user-attachments/assets/6fb08e55-8e77-4017-b945-f899ccb539ca">

**Comment by rishabhknowss** [comment]
> Assigned to you @rishabhknowss, looking forward for the designs proposals 🚀

On it !

**Comment by DhairyaMajmudar** [comment]
@arpitkuriyal you can collaborate with @rishabhknowss

**Comment by rishabhknowss** [comment]
> @arpitkuriyal you can collaborate with @rishabhknowss

happy to collaborate ! @arpitkuriyal you can give design proposal and i will code it 
how does that sound ? :rocket:

**Comment by arpitkuriyal** [comment]
Sounds Great! @rishabhknowss  Looking forward to learn  from you

**Comment by benjagm** [comment]
@arpitkuriyal Your design is cool.

**Comment by arpitkuriyal** [comment]
okay i understood it . Proposing  another prototype in few hours .

**Comment by arpitkuriyal** [comment]
@benjagm please find the attached proposal. Looking forward to your kind feedback 
<img width="909" alt="Screenshot 2024-10-19 at 10 32 54 AM" src="https://github.com/user-attachments/assets/77c40c15-3beb-404c-9c26-1f8d53043367">

**Comment by rishabhknowss** [comment]
Is it ready? Should I start coding this?

**Comment by DhairyaMajmudar** [comment]
Hi @rishabhknowss,  yes you can open a PR

**Comment by rishabhknowss** [comment]
@arpitkuriyal are the designs completed ? could you please share them ? ( figma file or smth else ? )

**Comment by benjagm** [comment]
> @benjagm, in this issue we need to improve the design for the specification version pages. Correct?

Correct. You already have some good proposals by @arpitkuriyal.

**Comment by rishabhknowss** [comment]
I was waiting for the designs but nvm feel free to take this issue guys  🙌

**Comment by arpitkuriyal** [comment]
@techmannih I can create a new design for the spec page if @benjagm isn't satisfied with the current one. Let me know if you'd prefer me to just design it, or I can handle the coding as well either works for me!
