### ISSUE TITLE
🐛 Bug: Broken Links

### ISSUE THREAD

**Issue by LasneF** [json-schema-org/website#1032]
### Describe the bug

there is a broken link :( 

### Steps To Reproduce

Go to 
https://json-schema.org/learn/glossary#validation-result

then click on on validation result (not the title , the link) 

it does a 404 

it was looking to  
https://json-schema.org/blog/posts/get-started-with-json-schema-in-node-js.md#creating-a-schema-and-validating-data

### Expected Behavior

no broken link 

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by DhairyaMajmudar** [comment]
Thank you for reporting the issue 🤝

**Comment by arpitkuriyal** [comment]
hey @DhairyaMajmudar , Can you please assign this to me . I can solve this.
