### ISSUE TITLE
🐛 Bug: Webpage Overflow on Smaller Devices

### ISSUE THREAD

**Issue by toffee-k21** [json-schema-org/website#1044]
### Describe the bug

The webpage content overflows on smaller devices, causing horizontal scrolling and layout issues.

### Steps To Reproduce

1. Open the webpage on a smaller device or in a browser with a narrow viewport.
2. Observe the content overflowing beyond the screen width.

### Expected Behavior

The webpage should be fully responsive, with no overflow or horizontal scrolling on smaller devices.

### Screenshots

https://github.com/user-attachments/assets/1d12bd96-71ba-4e4f-a250-98de8368bee2

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by DhairyaMajmudar** [comment]
@toffee-k21 thanks for reporting this issue it's open for takes

**Comment by arpitkuriyal** [comment]
@DhairyaMajmudar  can you assign this issue to me.

**Comment by DhairyaMajmudar** [comment]
> @DhairyaMajmudar can you assign this issue to me.

Assigned to you, looking forward for your PR

**Comment by DhairyaMajmudar** [comment]
Issue completed here https://github.com/json-schema-org/website/pull/1048
