### ISSUE TITLE
🐛 Bug: maxProperties Keyword Not Found in Documentation

### ISSUE THREAD

**Issue by techmannih** [json-schema-org/website#1052]
### Describe the bug

I noticed that the maxProperties keyword is not listed in the documentation. Could you please check it here: [JSON Schema Keywords](https://json-schema.org/understanding-json-schema/keywords)?

### Steps To Reproduce

1. Understand the code.
2. Add the maxProperties keyword.
3. Also, add a redirect link for the description of the maxProperties keyword.

### Expected Behavior

1. The code should correctly implement the maxProperties keyword, allowing for the specified maximum number of properties.
2. The redirect link should direct users to the appropriate description for the maxProperties keyword, providing clear and useful information.

### Screenshots

![image](https://github.com/user-attachments/assets/744c27c5-71a4-4c4c-84ac-5413a6319865)

### Device Information [optional]

```markdown
- OS: Windows
- Browser: Microsoft Edge
- version:
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

Yes

**Comment by techmannih** [comment]
@DhairyaMajmudar please assign me this issue

**Comment by DhairyaMajmudar** [comment]
Assigned the issue to you @techmannih 🚀
