### ISSUE TITLE
[📝 Docs]: JSON Schema Docs Board

### ISSUE THREAD

**Issue by Playaset** [json-schema-org/website#1055]
### What Docs changes are you proposing?

I'll like to contribute to JSON Schema Docs Board using Schama Doc. ch fen #1054 #1029 #1028 #1040 #

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DhairyaMajmudar** [comment]
Closing since the mentioned PRs are in progress @Playaset feel free to look for an another issue.
