### ISSUE TITLE
🐛 Bug: Some Section need's Improvement

### ISSUE THREAD

**Issue by officeneerajsaini** [json-schema-org/website#1057]
### Describe the bug

I encountered an issue with the navbar when dark mode is enabled. I'm unable to see which page I'm currently navigating to because there is no visible active element. Typically, the active route or page is highlighted with a different color, but in dark mode, all the navbar items appear the same.

<img width="1440" alt="Screenshot 2024-10-23 at 5 03 19 PM" src="https://github.com/user-attachments/assets/c050002d-967b-4c89-a12c-6bd9907edf4c">

### Steps To Reproduce

1. Turn on Dark Mode
2. Check the Active Item of Navbar

### Expected Behavior

In dark mode, it's hard to see which page we're currently on. There should be an active color for the navbar items so the current page is clearly visible.

<img width="1440" alt="Screenshot 2024-10-23 at 5 03 07 PM" src="https://github.com/user-attachments/assets/8497ee79-4034-4025-a121-6f1f15eab8f2">

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

NO

**Comment by officeneerajsaini** [comment]
I found another issue on the community page. In the Upcoming Events section, if there are four dates, everything looks fine, but if there are five, the background color of one of the divs doesn't appear. I initially styled it for four divs only, so I need to add an additional CSS class to ensure it looks as it should.
![Uploading Screenshot 2024-10-23 at 5.00.04 PM.png…]()

**Comment by Utkarsh-Agarwal-585** [comment]
hI @officeneerajsaini can I start work on this? Please assign it to me!

**Comment by officeneerajsaini** [comment]
@Utkarsh-Agarwal-585, please read this issue carefully. As I mentioned earlier, I am already working on it, and like you, I am a contributor, not a member of the JSON Schema project.

**Comment by officeneerajsaini** [comment]
There are other issues in this repo that you can look into. Feel free to ask a maintainer or collaborator to assign one to you. Please  leave this issue to me. @Utkarsh-Agarwal-585

**Comment by officeneerajsaini** [comment]
@DhairyaMajmudar  please assign this issue to me.

**Comment by DhairyaMajmudar** [comment]
Looking forward for your PR @officeneerajsaini
