### ISSUE TITLE
[📝 Docs]:  Edit keywords to camelCasing 

### ISSUE THREAD

**Issue by kwennB** [json-schema-org/website#1062]
### What Docs changes are you proposing?

The [keywords used in JSON Schema](https://json-schema.org/understanding-json-schema/keywords) adopt the camel case style; some keywords are written in camel case, and others are not. 

![camelcase-keywords](https://github.com/user-attachments/assets/5500fd5a-7a65-438d-97cd-ffb4c6e3161b)

This issue is about editing all the keywords to have camelCase. 

Examples: `minproperties` is supposed to be `minProperties`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by techmannih** [comment]
@DhairyaMajmudar may I work on this issue

**Comment by DhairyaMajmudar** [comment]
> @DhairyaMajmudar may I work on this issue

Go ahead @arpitkuriyal, looking forward for you PR  🚀

**Comment by techmannih** [comment]
thank you @DhairyaMajmudar

**Comment by benjagm** [comment]
Closed as completed after the merge of #1063
