### ISSUE TITLE
🐛 Bug: Blog Page Author rendering problem

### ISSUE THREAD

**Issue by Ritesh2351235** [json-schema-org/website#1065]
### Describe the bug

The Authors on the Blog page are not rendering as expected.

### Steps To Reproduce

1. Changing the Styles on the blogs page.
2. Making some changes in tailwind.config file.blog

### Expected Behavior

Correct rendering of all authors for their respective blogs.

### Screenshots

<img width="1470" alt="Screenshot 2024-10-26 at 2 43 31 PM" src="https://github.com/user-attachments/assets/6722dc46-9aea-4baa-8db1-e508ebe8efaf">

### Device Information [optional]

```markdown
- OS: MacOS
- Browser: Chrome
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

Yes

**Comment by benjagm** [comment]
Thanks Ritesh. Please go ahead!
