### ISSUE TITLE
🐛 Bug: Sponsors Button Not Working Correctly

### ISSUE THREAD

**Issue by IyaadArshad** [json-schema-org/website#1067]
### Describe the bug

While the "Add your brand here" technically works, most users would perceive this as not working / broken, as only the text saying "Your logo here" has a href referencing the link, meaning the rest of the button, inclusive of the "+" icon does not function, providing a misleading idea that it is a broken link

### Steps To Reproduce

1. Navigate to https://json-schema.org/ (Note: adding #sponsors only works some of the time for some reason, directly going to https://json-schema.org/#sponsors does not open sponsors instantly)
2. Scroll down to "Sponsors"
3. The buttons mentioned in the bug description are visible

### Expected Behavior

Typically, users should expect that the entire button be responsive, perhaps also adding a target=blank or _blank to open in a new tab (not necessary, just personal opinion), but most of the button is unresponsive and does not go to the contribute url

### Screenshots

https://github.com/user-attachments/assets/ba6af677-b2bd-430c-8c07-4c17d79de842

### Device Information [optional]

```markdown
- OS: Ubuntu 22.04
- Browser: edge
- version: 22
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by DhairyaMajmudar** [comment]
Good find @IyaadDev the whole button should be acting as a redirecting link

**Comment by IyaadDev** [comment]
ready to merge 👍

**Comment by IyaadArshad** [comment]
Will send new pr soon

**Comment by IyaadArshad** [comment]
ready to merge 👍

**Comment by IyaadArshad** [comment]
ready to merge 👍
