### ISSUE TITLE
🐛 Bug: Minimum, maxItem, maxlength, minContain, format(Assertion) and format (Annotation) are not found in keyword documentation

### ISSUE THREAD

**Issue by techmannih** [json-schema-org/website#1068]
### Describe the bug

Describe the bug
I noticed that Minimum, maxItem, maxlength, minContain, format(Assertion) and format (Annotation) are not listed in the documentation. Could you please check it here: [JSON Schema Keywords](https://json-schema.org/understanding-json-schema/keywords)?

### Steps To Reproduce

1. Understand the code.
2. Add the Minimum, maxItem, maxlength, minContain, format(Assertion) and format (Annotation).
3. Also, add a redirect link for the description of the Minimum, maxItem, maxlength, minContain, format(Assertion) and format (Annotation).

### Expected Behavior

1. The code should correctly implement the Minimum, maxItem, maxlength, minContain, format(Assertion) and format (Annotation).
, allowing for the specified maximum number of properties.
2. The redirect link should direct users to the appropriate description for the Minimum, maxItem, maxlength, minContain, format(Assertion) and format (Annotation).
, providing clear and useful information.

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

Yes

**Comment by DhairyaMajmudar** [comment]
Hi @techmannih can you pls. list down the references of mentioned keywords

**Comment by DhairyaMajmudar** [comment]
Thank you @techmannih assigning the issue to you 🚀
