### ISSUE TITLE
The old blog repo incorrectly links to this repo

### ISSUE THREAD

**Issue by jaller94** [json-schema-org/website#1069]
### Describe the bug

The archived blog repo has an invalid link to this repo.

### Steps To Reproduce

1. Go to the README of https://github.com/json-schema-org/blog
2. Click on the 2nd link
3. HTTP 404

### Expected Behavior

The link the should link to "website" instead of "websitem".

https://github.com/json-schema-org/blog/compare/main...jaller94:blog:patch-1

### Screenshots

![2024-10-27_13-46](https://github.com/user-attachments/assets/1d56c5f2-abdd-42b0-a2f6-ccf56bb8746f)

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by benjagm** [comment]
Hi @jaller94 thanks a lot for filling this issue. Unfortunately the repo is archived, therefore in read-only status and we can't change its content.

**Comment by benjagm** [comment]
Closing it as not planned.
