### ISSUE TITLE
🐛 Bug: Bad contrast in the blog's dark theme in info boxes

### ISSUE THREAD

**Issue by jaller94** [json-schema-org/website#1070]
### Describe the bug

The text in info boxes cannot be read.

### Steps To Reproduce

0. Set your browser to prefer the dark theme.
1. Go to https://json-schema.org/blog/posts/applicability-json-schema-fundamentals-part-1#putting-everything-together-avoiding-oneof-pitfalls
2. Look for any of the many info boxes.
3. The text is not legible.

### Expected Behavior

Proper contrast of the font and the background for the dark theme

### Screenshots

![2024-10-27_13-49_1](https://github.com/user-attachments/assets/3065ec9e-a50b-4ca5-8d04-1214d4b28a29)

The light theme looks ok:

![2024-10-27_13-49](https://github.com/user-attachments/assets/36cfc39a-81f0-4581-9ecb-2b0772d98c6a)

### Device Information [optional]

```markdown
- OS: Manjaro
- Browser: Firefox
- version: 131.0.2
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by DhairyaMajmudar** [comment]
Thanks for reporting the issue @jaller94

**Comment by pavanydg** [comment]
@DhairyaMajmudar pl assign me.

**Comment by DhairyaMajmudar** [comment]
Go ahead @pavanydg 🚀

**Comment by ayushk-1801** [comment]
please assign me

**Comment by souvikjs01** [comment]
if the issue is still open, can you assign me @DhairyaMajmudar

**Comment by ritwik-69** [comment]
@DhairyaMajmudar can i work on this issue?

**Comment by DhairyaMajmudar** [comment]
Sure @ritwik-69 looking forward for your PR

**Comment by ritwik-69** [comment]
![image](https://github.com/user-attachments/assets/9ef0638d-9268-4841-8650-98edef478106)
@DhairyaMajmudar I am getting this error while committing can you tell me how t o fix this?

**Comment by DhairyaMajmudar** [comment]
It's causing since you're using yarn V1 whereas the repo supports yarn V4, you can install latest yarn version by following the [guide](https://github.com/json-schema-org/website/blob/main/INSTALLATION.md#corepack-configuration)

**Comment by ritwik-69** [comment]
> It's causing since you're using yarn V1 whereas the repo supports yarn V4, you can install latest yarn version by following the [guide](https://github.com/json-schema-org/website/blob/main/INSTALLATION.md#corepack-configuration)

`on yarn --version` I am getting 4.4.0 and also my corepack is not getting enabled and is showing operation not permitted
