### ISSUE TITLE
[📝 Docs]: Typos and grammatical errors in README.md

### ISSUE THREAD

**Issue by IyaadArshad** [json-schema-org/website#1080]
### What Docs changes are you proposing?

Quick update to the README.md, there are quite a few grammatical errors and typos

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IyaadDev** [comment]
will submit a pr with fixes soon

**Comment by IyaadDev** [comment]
and issues will be mentioned here

**Comment by IyaadDev** [comment]
Potentially incorrect information:
- 23: contains the **sources** of the JSON Schema website:

Typos:
- 27: **build** and deployed with Netlify.

Grammatical errors:
- 31: Please refer to **the** INSTALLATION.md **file** for ...
- 60: **Design** (Omitted words)
- 63: **Add a new** (Unnecessary words)

There's quite a couple of them, I'll just submit a pr and the improvements can be viewed in the diff section

**Comment by DhairyaMajmudar** [comment]
Thank you so much @IyaadDev looking forward for your PR

**Comment by IyaadDev** [comment]
looking through more issues now...

**Comment by IyaadDev** [comment]
so far so good,
will continue checking later this wek

**Comment by IyaadArshad** [comment]
That looks to be about it 👍
