### ISSUE TITLE
🐛 Bug: Disable Tooling Page analytics posting during dev mode to ensure accurate trend reports

### ISSUE THREAD

**Issue by DarhkVoyd** [json-schema-org/website#1096]
### Describe the bug

Currently, analytics posting tooling page trends is active regardless of the environment (development or production), which can skew reports when development activity generates data that is irrelevant to real-world usage. To improve the accuracy of these reports, we should disable analytics tracking during development mode.

### Steps To Reproduce

1. Run the website in development mode.
2. On `/tools` Tooling Page, trigger any event that would typically call the `postAnalytics` function, such as opening details modal for a tool or executing a search query for a tool.

### Expected Behavior

- During **development**, no analytics data should be posted to the endpoint.
- During **production**, the analytics data should be posted as expected.

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by saurabhraghuvanshii** [comment]
@DarhkVoyd can i Work on this

**Comment by saurabhraghuvanshii** [comment]
@DarhkVoyd can you assign me , I want to work on this

**Comment by DarhkVoyd** [comment]
Hey @saurabhraghuvanshii, thanks for your interest. This issue is currently in the `Status: Triage` phase. Once it’s been discussed and approved to take on, it’ll be moved to the `Status: Available` phase and then you can work on it.

**Comment by saurabhraghuvanshii** [comment]
@DarhkVoyd thanks sir for informing

**Comment by benjagm** [comment]
Thanks @DarhkVoyd @saurabhraghuvanshii . This makes sense to me. Let's do it.

**Comment by saurabhraghuvanshii** [comment]
hii @benjagm @DarhkVoyd so, can I start working on it

**Comment by DarhkVoyd** [comment]
Sure! @saurabhraghuvanshii please go ahead.
