### ISSUE TITLE
Protocol buffer plugin for jsonschema

### ISSUE THREAD

**Issue by uanid** [json-schema-org/website#1102]
### Tool Name

protoc-gen-jsonschema

### Tool Description

JsonSchema generator plugin for Google Protocol Buffers

### Action Type

- [X] Add Tool
- [ ] Modify Tool

### Tooling Types

- [ ] validator
- [ ] hyper-schema
- [ ] benchmarks
- [ ] documentation
- [ ] LDO-utility
- [ ] code-to-schema
- [ ] data-to-schema
- [X] model-to-schema
- [ ] schema-to-types
- [ ] schema-to-code
- [ ] schema-to-web-UI
- [ ] schema-to-data
- [ ] util-general-processing
- [ ] util-schema-to-schema
- [ ] util-draft-migration
- [ ] util-format-conversion
- [ ] util-testing
- [ ] editor
- [ ] editor-plugins
- [ ] schema-repository
- [ ] linter
- [ ] linter-plugins

### Languages

Protocol Buffers

### Maintainers

Uanid ([@uanid](https://github.com/uanid))

### License

Apache-2.0

### Source Repository URL

https://github.com/pubg/protoc-gen-jsonschema

### Supported Dialects

- [ ] 1
- [ ] 2
- [ ] 3
- [X] 4
- [ ] 5
- [X] 6
- [X] 7
- [X] 2019-09
- [X] 2020-12

**Comment by Adi-204** [comment]
I would like to work on in this issue @DarhkVoyd can you please assign me.
