### ISSUE TITLE
🐛 Bug: redirecting issue in the "Getting started page" 

### ISSUE THREAD

**Issue by arpitkuriyal** [json-schema-org/website#1111]
### Describe the bug

there is a broken link

### Steps To Reproduce

1. Go to the main page of the JSON Schema website and click on "Getting Started."
2. Scroll down and click on "Edit this page on GitHub."
3. It redirects to a non-existent page: https://github.com/json-schema-org/website/blob/main/pages/learn/_index.md.

### Expected Behavior

no broken links

### Screenshots

https://github.com/user-attachments/assets/195bfd97-3bb4-4472-9321-be1228238438

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by DarhkVoyd** [comment]
Hey @arpitkuriyal , thank you for reporting this bug. This should be fixed by #1046.

**Comment by saurabhraghuvanshii** [comment]
hi @DarhkVoyd , as you mention Pr #1046 is closed and new Pr raised with #1117 with improvement .

**Comment by Yashwanth1906** [comment]
@saurabhraghuvanshii I have opened new pr for it #1117 which already fixes this issue.

**Comment by Yashwanth1906** [comment]
#1117 This pr already resolves this issue. Thank U.
