### ISSUE TITLE
Update node.js version

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/website#113]
Currently the node.js version is pinned at `16.0.0`.
This means we are working on versions with known and fixed bugs.
(I haven't seen any evidence that anything is broken because of this however.)

Node.js 16 has reached end of life.
The active LTS is 18.
LTS will move to 20 on 2023-10-24.

My suggestion, if we can, is to move to version 20, although this might require upgrading some of the dependencies. If that proves to be challenging (like, it takes more than 30mins), then moving to version 18 might be easeir.

I'm happy to look into this, but also happy if someone beats me to it.

As an aside, and maybe this should be a separate issue, we are using Cloudflare pages builder version 1, and version 2 is available, with updated underlying OS to current TLS, and updated underlying tooling. We should additionally look to see if we can use that. This requires manually changing settings in the Cloudflare admin area.

**Comment by jdesrosiers** [comment]
It would be smart to come up with a plan for regularly updating dependencies. The more often we do it, the smaller and easier the job will be.
