### ISSUE TITLE
🐛 Bug: Blog page Table of Content is Broken 

### ISSUE THREAD

**Issue by DhairyaMajmudar** [json-schema-org/website#1142]
### Describe the bug

Table of contents (on this page section) is found broken for the [blog ](https://json-schema.org/blog/posts/applicability-json-schema-fundamentals-part-1)

While checking for other pages its found that mentioned component is working as expected  

### Steps To Reproduce

1. Visit https://json-schema.org/blog/posts/applicability-json-schema-fundamentals-part-1
2. Broken component can be seen there

### Expected Behavior

It should not be broken and must be fixed maintaining the consistency with other blog pages

### Screenshots

![image](https://github.com/user-attachments/assets/f3d69d16-e05e-43fe-ac71-a7f5fc071711)

### Device Information [optional]

```markdown
- OS: Linux (Debian)
- Browser: Firefox
- version: Latest
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by arpitkuriyal** [comment]
@DhairyaMajmudar can I work on this?

**Comment by DhairyaMajmudar** [comment]
> @DhairyaMajmudar can i work on this issue?

Yeah sure, pls. go ahead

**Comment by DhairyaMajmudar** [comment]
Yeah sure, assigning the issue to @arpitkuriyal as he commented first, @ritwik-69 until then you can look for other open issues, Thank you : )

**Comment by arpitkuriyal** [comment]
hello @DhairyaMajmudar , As i am going through this,  i observe that blue dot markers are also not align with the reference link  should i  also correct them ?

**Comment by DhairyaMajmudar** [comment]
> hello @DhairyaMajmudar , As i am going through this, i observe that blue dot markers are also not align with the reference link should i also correct them ?

Yeah pls. do so

**Comment by Utkarsh-123github** [comment]
@DhairyaMajmudar  I think we can close this issue because my PR already solved this issue 
Link to the PR : https://github.com/json-schema-org/website/pull/1180
