### ISSUE TITLE
🐛 Bug: "Used by" companies don't have linked pages

### ISSUE THREAD

**Issue by IyaadArshad** [json-schema-org/website#1155]
### Describe the bug

When clicking on the logos of the companies using JSON schema on the homepage, nothing happens, it may be better to link their websites on the home page and make it so that it opens on a new tab

### Steps To Reproduce

1. Go to https://json-schema.org/
2. Look at the section starting "Build more"
3. Try and click on the logo of any company using JSON Schema

### Expected Behavior

In a new tab, the website of the company with the matching logo should open up

### Screenshots

![image](https://github.com/user-attachments/assets/8f08bd0b-e48e-4cf7-919c-769a3d7c6172)

### Device Information [optional]

```markdown
- OS: Arch Linux x86_64
- Browser: firefox
- version: 133.0 (64-bit)
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by IyaadArshad** [comment]
Note: will be using ```index.page.tsx``` from #1154 pull request to avoid merge conflicts when merging that pr

**Comment by IyaadArshad** [comment]
Note: Merge #1154 before merging this one

**Comment by benjagm** [comment]
Hi @IyaadArshad . This was done on purpose, trying to drive traffic to the adopters/landscape link.  Let's leave this way for now. Thanks a lot for the idea.

**Comment by benjagm** [comment]
Closed as not planned.

**Comment by IyaadArshad** [comment]
👍
