### ISSUE TITLE
Cookpad case study missing from case study page

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/website#1159]
We have a case study page!
https://json-schema.org/overview/case-studies

It's missing the case study with Cookpad: https://json-schema.org/blog/posts/cookpad-case-study-en

**Comment by MohdAbdulSami** [comment]
hi @Relequestual shall i contribute for this

**Comment by heysujal** [comment]
@MohdAbdulSami are you working on this?
If not I would like to work on this. Please let me know.

**Comment by MohdAbdulSami** [comment]
@heysujal 
I am not working on this issue

**Comment by heysujal** [comment]
Hi @MohdAbdulSami, thanks for the response. I have raised a PR for this issue.
