### ISSUE TITLE
🐛 Bug: Padding of button in Become a JSON Schema Ambassador (Mobile view)

### ISSUE THREAD

**Issue by Pavankumar07s** [json-schema-org/website#1160]
### Describe the bug

Everything is fine up to the tablet view, but in the mobile view, the "Become Ambassador" text is spilling out of the button. We need to adjust the padding to fix this.

### Steps To Reproduce

1.Go to the mobile view of the page.
2.Locate the "Become Ambassador" button.
3.Observe how the text overflows or spills out of the button.

### Expected Behavior

The "Become Ambassador" text should remain properly contained within the button, with appropriate padding and alignment for a clean and responsive design.

### Screenshots

![json](https://github.com/user-attachments/assets/3e89927a-043d-4d4d-af14-768573e38340)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

Yes

**Comment by saurabhraghuvanshii** [comment]
@Pavankumar07s can i working on it.

**Comment by Pavankumar07s** [comment]
@saurabhraghuvanshii it will be a great help but as i created these components i will able to do it fast and effectively. Thankyou.

**Comment by Pavankumar07s** [comment]
@benjagm @DhairyaMajmudar shall i start working on this bug🐛 .

**Comment by DhairyaMajmudar** [comment]
assigned the issue to you @Pavankumar07s

**Comment by Pavankumar07s** [comment]
@DhairyaMajmudar alright, lets make this perfect.
