### ISSUE TITLE
🐛 Bug: Social media links Ambassadors in "Become a JSON Schema Ambassador"

### ISSUE THREAD

**Issue by Pavankumar07s** [json-schema-org/website#1161]
### Describe the bug

There is an issue with some ambassador card components where certain ambassador links redirect to incorrect URLs. The problem arises because the JSON file containing the ambassador information includes a mix of full URLs for social links and usernames.

In the ambassador card component, there is a formatting feature designed to standardize the URLs, but it is not effectively handling the inconsistency in the data. For example:

If the JSON contains only a username (e.g., "username": "example"), the component should prepend the base URL (e.g., https://twitter.com/) to construct the full link.
If the JSON already contains the full URL (e.g., "url": "https://twitter.com/example"), the component should use it directly without modification.

### Steps To Reproduce

1.Go to the page where the ambassador cards are displayed.
2.Click on an ambassador's social link (e.g., Twitter, GitHub).
3.Scroll down to inspect other ambassador cards and try clicking their links.
4.Observe that some links redirect to incorrect URLs or fail to open properly.

### Expected Behavior

All social links should redirect to the correct pages based on the provided information in the JSON file. Links should work regardless of whether they are full URLs or usernames.

### Screenshots

![Screenshot from 2024-12-14 11-37-29](https://github.com/user-attachments/assets/a4ea310d-0b41-4934-aa21-e5ecc82424f2)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

Yes

**Comment by officeneerajsaini** [comment]
@Pavankumar07s, I found an issue with Esther Okafor's social links and Ege Korkan's Mastodon link in the other cards. All the other social links for the ambassadors are working well.

**Comment by Pavankumar07s** [comment]
@officeneerajsaini correct

**Comment by Pavankumar07s** [comment]
@benjagm @DhairyaMajmudar shall i start working on this?

**Comment by DhairyaMajmudar** [comment]
Sure!! looking forward for your PR

**Comment by Pavankumar07s** [comment]
Alright @DhairyaMajmudar

**Comment by DhairyaMajmudar** [comment]
issue will be resolved after merging https://github.com/json-schema-org/community/pull/843  and https://github.com/json-schema-org/website/pull/1173

**Comment by Pavankumar07s** [comment]
Alright @DhairyaMajmudar 👍

**Comment by officeneerajsaini** [comment]
LGTM ✅✨
