### ISSUE TITLE
🐛 Bug: Blog content List in Sidebar is broken

### ISSUE THREAD

**Issue by heysujal** [json-schema-org/website#1172]
### Describe the bug

Related to https://github.com/json-schema-org/website/issues/1142
The content list on the left side is distorted and shows a bullet at the end of list item.

### Steps To Reproduce

1. Go to [JSON Schema joins the OpenJS Foundation and 2022 updates](https://json-schema.org/blog/posts/json-schema-joins-the-openjsf#json-schema-is-hiring!-(at-postman)) blog
2. Observe the left sidebar in desktop view.

### Expected Behavior

For this blog to be consistent with other blogs, the bullet points should not show up at the end of every list item and it should be visible clearly on the screen without getting cut off.

### Screenshots

![image](https://github.com/user-attachments/assets/6f493e2f-cd35-4f68-85a7-f216ddc50d94)

### Device Information [optional]

```markdown
- OS: MacOS
- Browser: Chrome
- version: 131.0.6778.140
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by heysujal** [comment]
@DhairyaMajmudar can you assign me this issue?

**Comment by sksmagr23** [comment]
@heysujal I am newbie to this repo and found this issue beginner friendly, can you assign this issue ?

**Comment by heysujal** [comment]
@Utkarsh-123github I hope you saw my message asking for claiming this issue. It would be great if you could please tell first if you are working on this issue instead of making a PR directly.

**Comment by Utkarsh-123github** [comment]
@heysujal  Thank you for your comment. I completely understand your concern, and I’ll make sure to communicate before making a PR. I’ll confirm if I’m working on an issue to avoid any overlaps in the future.

Thanks for bringing this up! 😊
