### ISSUE TITLE
🐛 Bug: Remove Next.js build cache from preview.yml.

### ISSUE THREAD

**Issue by aialok** [json-schema-org/website#1178]
### Describe the bug

- We are facing an issue with the Next.js build cache, which we are using for preview deployments. Due to this, CSS changes are not being updated as expected, and the older cache from the previous builds is causing the problem.

- Removing the cache step will fix the issue.

Discussion : https://json-schema.slack.com/archives/C8C4UBXDF/p1734423225071989?thread_ts=1734410032.558099&cid=C8C4UBXDF

### Steps To Reproduce

1. Create a PR.  
2. After that, push a commit to the PR with the CSS changes.  

### Expected Behavior

- It should work as expected.

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

Yes

**Comment by saurabhraghuvanshii** [comment]
@aialok  i can work on this. can you assign to me

**Comment by aialok** [comment]
sure go ahead @saurabhraghuvanshii.

**Comment by saurabhraghuvanshii** [comment]
@aialok why docker is not working I tried every thing it failed to create  image

**Comment by aialok** [comment]
> @aialok why docker is not working I tried every thing it failed to create  image . but yarn dev work

@DhairyaMajmudar can you please check docker thing.

You can easily setup using yarn things.

**Comment by saurabhraghuvanshii** [comment]
@aialok review pr . If changes more to done. I will do

**Comment by saurabhraghuvanshii** [comment]
solves branch issue therefore closed prev pr
