### ISSUE TITLE
http://json-schema.org/schema 404

### ISSUE THREAD

**Issue by 6nv** [json-schema-org/website#118]
Hi all,

I've been getting a 404 not found error code from http://json-schema.org/schema in VS Code and in multiple different browsers, and on different networks. Additionally, VS code no longer provides intellisense when I use that schema URL.

<img width="1263" alt="Screenshot 2023-10-09 at 11 54 40 AM" src="https://github.com/json-schema-org/website/assets/91281131/b500e8cd-e50c-44ed-a689-3195c2f3f862">

Sample code to reproduce:
```json
{
    "$schema": "http://json-schema.org/schema"
}
```

**Comment by gregsdennis** [comment]
Hey @6nv.

There are a couple problems here.

First, we are only serving HTTPS from the website now.

Second, meta-schemas should be packaged with the editor/implementation rather than downloaded as needed.  That's an issue with the editor.  We expected this.

There have been [other reports](https://github.com/jimblackler/jsonschemafriend/issues/29) of implementations doing this, and our response is the same.  You're welcome to follow the [conversation in Slack](https://json-schema.slack.com/archives/C5CF75URH/p1696249012584239) as well.

I'll open an issue with VSCode.

**Comment by gregsdennis** [comment]
@6nv you might try `http://json-schema.org/draft-07/schema#`.  This would be a better option than that URI.

**Comment by benjagm** [comment]
Hi everyone! I just deployed a new rule on cloudflare to create that redirect for https://json-schema.org/schema. 
This was a missing redirection rule in the migration process. @6nv Could you please try again and let us know?

**Comment by jdesrosiers** [comment]
Keep in mind that the use of `http://json-schema.org/schema#` is deprecated and should not be used. Consider this outage a dress rehearsal for when we stop serving it altogether :wink:.

> In Draft 4, a `$schema` value of `http://json-schema.org/schema#` referred to the latest version of JSON Schema. This usage has since been deprecated and the use of specific version URIs is required. - https://json-schema.org/understanding-json-schema/basics#declaring-a-json-schema

> we are only serving HTTPS from the website now.

I just want to clarify that the website does respond to `http:` requests, it will just give a 301 redirect to the `https:` address. As long as the client (vscode in this case) handles HTTP redirects the way it should, you shouldn't notice any difference.

**Comment by 6nv** [comment]
FYI, issue created with VS Code here: https://github.com/microsoft/vscode/issues/195189

**Comment by gregsdennis** [comment]
That VSCode issue has been closed via PR.

@6nv are you happy closing this?

**Comment by benjagm** [comment]
As per the Open Community Working Meeting of 2023-10-30 this is going to be deprecated in the future.
https://github.com/json-schema-org/community/issues/505

**Comment by benjagm** [comment]
Closed as completed.
