### ISSUE TITLE
🐛 Bug: typo in draft-06 link

### ISSUE THREAD

**Issue by karenetheridge** [json-schema-org/website#1191]
### Describe the bug

On the page: https://json-schema.org/draft-06/ the link "Validation: draft-wright-json-schema-validation-01" contains a typo in the URI: it is https://json-scheclsma.org/draft-06/draft-wright-json-schema-validation-01.html which is an invalid hostname.

### Steps To Reproduce

--

### Expected Behavior

Host should be json-schema.org.

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by DhairyaMajmudar** [comment]
Thank you @karenetheridge for reporting this issue.

The actual link goes like this https://json-schema.org/draft-06/draft-wright-json-schema-validation-01
