### ISSUE TITLE
KSail Cluster Schema

### ISSUE THREAD

**Issue by devantler** [json-schema-org/website#1205]
### Tool Name

KSail

### Tool Description

An SDK for operating GitOps enabled Kubernetes clusters.

### Action Type

- [X] Add Tool
- [ ] Modify Tool

### Tooling Types

- [ ] validator
- [ ] hyper-schema
- [ ] benchmarks
- [ ] documentation
- [ ] LDO-utility
- [ ] code-to-schema
- [ ] data-to-schema
- [X] model-to-schema
- [ ] schema-to-types
- [X] schema-to-code
- [ ] schema-to-web-UI
- [X] schema-to-data
- [ ] util-general-processing
- [ ] util-schema-to-schema
- [ ] util-draft-migration
- [ ] util-format-conversion
- [ ] util-testing
- [ ] editor
- [ ] editor-plugins
- [X] schema-repository
- [ ] linter
- [ ] linter-plugins

### Languages

C#

### Environments

OSes: MacOS, Linux

Kubernetes Distributions: Kind, K3d

### Creators

@devantler

### Maintainers

@devantler

### License

Apache2

### Source Repository URL

https://github.com/devantler/ksail

### Homepage URL

https://devantler.github.io/ksail/

### Supported Dialects

- [ ] 1
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [X] 7
- [ ] 2019-09
- [ ] 2020-12

**Comment by devantler** [comment]
My schemas are in `schemas/*`, and it currently just contains the ksail-cluster-schema.json` to provide intellisense and validation when working with the ksail configuration file.

**Comment by jdesrosiers** [comment]
This doesn't appear to be an implementation of JSON Schema. This appears to be a tool that uses JSON Schema. That's great, but that's not the kind of thing we list on the tools page. Tools that take JSON Schemas as input or produce JSON Schemas as output are the kinds of things we list here.

Let me know if I missed something, but if not, we have a page for [JSON Schema adopters](https://landscape.json-schema.org/) that I think your tool would be a good fit for.

**Comment by devantler** [comment]
Hmm, I am probably creating this issue the wrong place.

I am creating a JSON Schema that I want to make available for all via a JSON Schema registry, so when they open a YAML file with the APIVersion and Kind matching KSail, they will be provided intellisense for the configuration file for my tool.

I think what I am looking for is `https://github.com/SchemaStore/schemastore`. I am still interested in sharing the tools on similar schema registries or in ways you suggest.

Are you aware of other major schema registries? And how/where would i register KSail as a JSON Schema adopter?

**Comment by jdesrosiers** [comment]
> I think what I am looking for is https://github.com/SchemaStore/schemastore.

Yes, it sounds like SchemaStore is what you want. That's what's used in most IDEs and editors that support JSON Schema based config validation and completions. I'm not aware of any other registries you'd want to add your schema to.

> And how/where would i register KSail as a JSON Schema adopter?

On that page I linked to before there's a github logo in the top right corner. That will take you to the repo where you can request to be added as a JSON Schema adopter.
