### ISSUE TITLE
Docs request: adding dates to Specification Links

### ISSUE THREAD

**Issue by jamesbraza** [json-schema-org/website#123]
JSON schema 2019-09 and 2020-12 use [CalVer](https://calver.org/), so their release date is self explanatory.

It would be useful if the [Specification Links](https://json-schema.org/specification-links.html) page documented release dates for versions (e.g. draft 6, draft 7) before JSON schema started using CalVer.

Something like in the [Draft 7 section here](https://json-schema.org/specification-links.html#draft-7), just adding a bullet for the release date

**Comment by benjagm** [comment]
Thanks for the proposal @jamesbraza this is a great idea and well implement it ASAP.

**Comment by praveen-rikhari** [comment]
@benjagm this has not been picked yet can i work on this one??

**Comment by Sanket-0510** [comment]
@benjagm Where can I find the release dates for all the drafts (eg. draft 6, draft 7)

**Comment by benjagm** [comment]
You will find the dates in the header of each spec version. The links to the spec version are available here: https://json-schema.org/specification-links

For examples for Draft 2020-12:

<img width="749" alt="Screenshot 2024-02-24 at 16 20 19" src="https://github.com/json-schema-org/website/assets/40007659/c30dd6d7-3fce-4a79-b4e0-c484c9248e41">

**Comment by benjagm** [comment]
@praveen-rikhari please go ahead with this issue
