### ISSUE TITLE
Include links to other tutorials/papers/resources

### ISSUE THREAD

**Issue by awwright** [json-schema-org/website#124]
- http://spacetelescope.github.io/understanding-json-schema/index.html
- http://cswr.github.io/JsonSchema/spec/introduction/
- http://www2016.net/proceedings/proceedings/p263.pdf

**Comment by benjagm** [comment]
It would be great to create a youtube list in our channel putting together video resources.

**Comment by benjagm** [comment]
Added to the docs strategy #158

**Comment by benjagm** [comment]
Closed in favour of #282
