### ISSUE TITLE
Include test suite results for validator implementations

### ISSUE THREAD

**Issue by awwright** [json-schema-org/website#125]
It might be useful if we include a brief summary of what features different validators support, and indicate test suite compliance.

This might be a task better handled by someone else, though.

**Comment by gregsdennis** [comment]
I think Bowtie properly covers this.  It doesn't yet have all of the implementations, but the framework is there.

**Comment by benjagm** [comment]
We'll have this covered in the new version of the implenmeters page #160 

Closed in favour of #160
