### ISSUE TITLE
Links to similar technologies

### ISSUE THREAD

**Issue by awwright** [json-schema-org/website#126]
Things to probably include:
- http://codalogic.github.io/jcr/
- https://datatracker.ietf.org/doc/draft-cordell-jcr-co-constraints/
- https://tools.ietf.org/html/draft-greevenbosch-appsawg-cbor-cddl-08

**Comment by benjagm** [comment]
Added to  the docs strategy #158

**Comment by Sanket-0510** [comment]
@benjagm can you please elaborate where do I need to add these links and whats the significant

**Comment by benjagm** [comment]
@Sanket-0510 As per the docs strategy described in #158, the goal is to create a new page into the overview section to introduce some other technologies similar to JSON Schema. Adding some introductory text, providing this list and inviting people to submit a pr if they know more technologies that should be added here.

**Comment by Michael-Obele** [comment]
Hey, @benjagm. This looks amazing, and I would love to do this.

**Comment by benjagm** [comment]
@Michael-Obele go ahead. Thanks.

**Comment by benjagm** [comment]
Closed as completed
