### ISSUE TITLE
add links to openapi website

### ISSUE THREAD

**Issue by karenetheridge** [json-schema-org/website#127]
e.g. from the implementations page to theirs, but there are other pages we should link to too.

```
ether  12:58
all the goodies are listed at https://json-schema.org/implementations.html
12:59
(there are probably others as well, listed on the openapi website, that are openapi-specific.)

ether  12:59
@relequestual we should maybe link to their page from ours

relequestual  27 minutes ago
log an issue =]

ether  < 1 minute ago
you need a slack bot for opening GH issues from the command line
```

**Comment by DhairyaMajmudar** [comment]
@benjagm I would like to work on this, can you pls. assign.

**Comment by benjagm** [comment]
@DhairyaMajmudar please go ahead!

**Comment by DhairyaMajmudar** [comment]
Thanks for issue the assignment @benjagm , can you pls. share in which files I have to do changes and give a bit more background of the work to be done.

**Comment by benjagm** [comment]
The initial scope of this issue is to link to https://www.openapis.org/ every occurrence of OpenApi in the page:
https://json-schema.org/implementations

**Comment by DhairyaMajmudar** [comment]
Thank you for help, looking forward to open a PR.
