### ISSUE TITLE
Add "Edit this page on GitHub" link to each page

### ISSUE THREAD

**Issue by awwright** [json-schema-org/website#128]
To make it easier for people to contribute to the website, there should be a link to edit the source file on GitHub.

Some details:

* https://milanaryal.com/adding-edit-on-github-links-to-github-pages-using-jekyll/

Additional examples (look for "Edit this page" links):

* https://home-assistant.io/getting-started/

**Comment by benjagm** [comment]
This should be much easier to be implemented with the new version of the website. We'll priorize it.

**Comment by JeelRajodiya** [comment]
Can I work on this issue?

**Comment by benjagm** [comment]
> Can I work on this issue?

Thanks for your interest @JeelRajodiya ! We are going to close this issue in favour of #151 worked by @DarhkVoyd

**Comment by benjagm** [comment]
We are reopening this issue to complement the component created as part of #151.

The expected outcome will be change the text and destination of the button "Make a contribution" for:

- Text :  "Edit this page on Github"
- Action : Link to the file on github. 

![Screenshot 2024-03-11 at 11 01 57](https://github.com/json-schema-org/website/assets/40007659/6277f426-e57f-4daf-b0e8-637cd6f69535)

**Comment by DhairyaMajmudar** [comment]
Shall I take this up : )

**Comment by Sahil-Shadwal** [comment]
Please assign me this issue

**Comment by benjagm** [comment]
All yours Sahil!

**Comment by satyabarghav** [comment]
Hi there! Can you please assign me this issue.
