### ISSUE TITLE
Review algolia search implementation

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#13]

**Comment by OlliesWorld** [comment]
@benjagm is there something specific I should look for?

**Comment by benjagm** [comment]
Just do some end user testing to check the behavior

**Comment by OlliesWorld** [comment]
The search is bringing up pages for everything I am typing. And pages seem to be correct.
I would give it a ✅

**Comment by benjagm** [comment]
Thanks Roni. I'll take another look. I am going to create a new api key for JSON Schema organization because we don't own the current keys.

**Comment by benjagm** [comment]
I requested new credentials of https://docsearch.algolia.com/

**Comment by benjagm** [comment]
We are now part of team owning the current docsearch app.

**Comment by benjagm** [comment]
Completed
