### ISSUE TITLE
Link from YAML file to Schema

### ISSUE THREAD

**Issue by guettli** [json-schema-org/website#139]
The yaml language server uses this pattern to specify the schema of a file:

```
# yaml-language-server: $schema=<urlToTheSchema>
```

https://github.com/redhat-developer/yaml-language-server#using-inlined-schema

I think it would be useful to provide this hint on your web site.

**Comment by benjagm** [comment]
We'll implement this ASAP. Thanks again.

**Comment by praveen-rikhari** [comment]
Hey @benjagm i don't understand this issue completely is this about adding a hint to the json-schema readme that for a yaml server the json schema is specified as mentioned above or to the website and if this has to go to the website what is the right place for it??

**Comment by benjagm** [comment]
@praveen-rikhari that hint is not for the readme, is for the website but we need to find the best place to place it. @jdesrosiers is working on developing a new JSON Schema Language Server. When it is available and we create some documentation, maybe we can add this note there.

**Comment by Gaurav-Verma07** [comment]
Hey @benjagm, are we ready to add this note on the new JSON server?

**Comment by benjagm** [comment]
I am closing this issue for now. As of now we don't have a section for Yaml specific notes.
Thanks everyone.
