### ISSUE TITLE
please update with fixes to 2019-09 schemas

### ISSUE THREAD

**Issue by karenetheridge** [json-schema-org/website#140]
Recently some changes have been merged in json-schema-spec to some 2019-09 schemas. Please could they be updated on the website, as implementations pull from here for validation against metaschemas?  Also, ~~two~~ one of them is not yet merged (but I just created it).

They are:

- json-schema-org/json-schema-spec#923 (fixes to output/schema.json)
- ~~json-schema-org/json-schema-spec#883 (fixes to meta/applicator.json for unevaluatedProperties)~~ looks like this one is on the website already
- ~~json-schema-org/json-schema-spec#804 (fixes to meta/core.json for $id)~~ looks like this one is on the website already
- json-schema-org/json-schema-spec#940 (not yet merged; another fix to output/schema.json)

However, do *not* include all the changes to these files, because some only have relevance to 2020-0X and involve parallel changes to the specification documents, such as:
- json-schema-org/json-schema-spec#938 (changes in semantics to output properties)
- json-schema-org/json-schema-spec#928 (regex fix in $anchor pattern)

thanks!

edit: I double-checked each PR and it looks like the only undeployed changes are to output/schema.json, which is far less of a big deal than fixes to the spec metaschema itself. so this is much less higher priority than I thought it should be when I filed it. sorry! -ether

**Comment by benjagm** [comment]
@jdesrosiers Do you think we can close this issue with the work you did for the github submodules and symlinks in the website repo with this PR: #210 ?
