### ISSUE TITLE
Build a JSON Schema Landscape

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#144]
It's great that we have the implementations and tooling page but that is just a portion of JSON Schema ecosystem. There are other players like adopter organizations or maybe partners that need's to be mapped.

It would be great to have a JSON Schema Landscape web space to visualize the real dimension of JSON Schema and the linux foundation actually provide a tool for that: https://lfx.linuxfoundation.org/tools/landscape/

We can make it very simple like the GraphQL Landscape:
https://landscape.graphql.org/

I'd essentially have these categories:
- Everything present in our implementations page:
  - Adopters
  - Sponsors
  - Partners
  - The tools will be managed in the implementations page

Resources:
 - [Linux Foundation landscape project](https://lfx.linuxfoundation.org/tools/landscape/) that should make it easy to start mapping our ecosystem. 
 - List of published landscape: https://landscapes.dev/

**Work Detail**:

- [x] List of work
- [x] To be done

**Comment by benjagm** [comment]
Now that we launched adopters, this issues is going to be replaced by #160

**Comment by Relequestual** [comment]
Reopening.
Landscape diagram includes...
adopters, implementations, sponsors, projects, consuming standards, and probably a few other things I forget.

I think eventually we might use a single data source, but that will take some time.

**Comment by praveen-rikhari** [comment]
Hello @benjagm i have seen similar landscapes in https://landscape.cncf.io/ cncf project list as well

**Comment by praveen-rikhari** [comment]
can i start working on this??

**Comment by benjagm** [comment]
Please do!

**Comment by benjagm** [comment]
Hi @praveen-rikhari, I am going to leave this issue free for other contributors. If you finally prefer to continue working on it let me know.

**Comment by deveshidwivedi** [comment]
Hi, I'd like to take this up

**Comment by praveen-rikhari** [comment]
@benjagm I already started working on it. Please reassign this to me.

**Comment by benjagm** [comment]
Making this issue available for others as there as been no progress in the last weeks

**Comment by DarhkVoyd** [comment]
Mind if I work on this?

**Comment by VivekJaiswal18** [comment]
I can collab on this with you if you don't mind

**Comment by aialok** [comment]
I love to collaborate on building JSON-schema landscape, and I believe it requires a significant amount of time and effort. I checked out the CNCF landscape and found out that we need a diverse range of peopel in different technology stacks, including frontend, backend, and DevOps, to create a comprehensive landscape.

**Comment by benjagm** [comment]
Let's create a working group to work together on this. Please thumbs up/down if you are interested.

**Comment by DhairyaMajmudar** [comment]
I would also like to collabrate on this : D

**Comment by bhavukkalra** [comment]
I would love to collaborate on this as well, It looks amazing as an approach. Can contribute with Technical Writing Docs and Frontend

**Comment by Michael-Obele** [comment]
Hey, I'd love to join too.✌️

**Comment by benjagm** [comment]
Hi folks! I just created our pilot working group here: https://github.com/json-schema-org/community/issues/701

Please join the [JSON Schema Slack server](https://json-schema.org/slack) and join the [wg-landscape](https://json-schema.slack.com/archives/C06V339TS1X) channel so we can sync for our first meeting.

We are so excited about working on this together.

**Comment by benjagm** [comment]
Closed as completed: https://landscape.json-schema.org/

Now the work will continue here: https://github.com/json-schema-org/landscape
