### ISSUE TITLE
https://json-schema.org/latest/json-schema-core.html is now a 404

### ISSUE THREAD

**Issue by Nadreck** [json-schema-org/website#147]
Previously, [this URL](https://json-schema.org/latest/json-schema-core.html) had a redirect set up to whatever the latest version of the core schema was. It would be nice if this functionality could be brought back - it's super handy for when you don't want to lock your links to a specific version, and just want to link to whatever the latest version is.

**Comment by benjagm** [comment]
Thanks for opening the issue @Nadreck . I'll work on bringing it back ASAP.

**Comment by benjagm** [comment]
Hi @Nadreck. Can you please check if the 404 is now fixed?

**Comment by Nadreck** [comment]
Still 404ing.

**Comment by benjagm** [comment]
Thanks @Nadreck. I made some additional tweaks in the rules and now should be working again.

**Comment by Nadreck** [comment]
Yep, appears to be working now. Thanks!
