### ISSUE TITLE
``unevaluatedItems`` tutorial missing from new site

### ISSUE THREAD

**Issue by micshar92** [json-schema-org/website#149]
Hey! New website is looking spiffy. I noticed you're sunsetting the old repo, so let me add this tiny issue here.

I wrote the ``unevaluatedItems`` tutorial [back in June](https://github.com/json-schema-org/understanding-json-schema/pull/205), and while it shows up on the old repo's site, it's still "Documentation Coming Soon" on this new site.

That tutorial is a helpful piece of my portfolio. So if it's all right with you, I want to reformat it (no writing changes) so the style fits this new repo.

**Comment by micshar92** [comment]
Well, shoot. I'm running into the same problem as before with [Windows changing line endings on scripts.](https://github.com/json-schema-org/understanding-json-schema/pull/209) Which is weird because I'm running ``yarn`` on Windows Subsystem for Linux (WSL), not the Windows command line.

Every file has multiple lines of this:

<img width="574" alt="Screenshot 2023-10-11 172121" src="https://github.com/json-schema-org/website/assets/112581105/e79aebe4-518b-418e-8813-c57040aa17f6">

As far as I can tell, my redesign of the file looks like it'll work, but I can't test it. Sure, I can change the end of line sequence in VS Code, but that saves a different version of every file, so when I upload even just this one Markdown file, it'll be a different type than the one I cloned. Probably not good.

So.... @jdesrosiers you fixed this last time. I need your help on it again. Thanks.

**Comment by Relequestual** [comment]
Hey @micshar92. It looks like you just need to duplicate the change made in the PR you referenced. This file: https://github.com/jdesrosiers/understanding-json-schema/blob/main/.gitattributes

Happy to accept a PR with that change here if you want to make it.

Additionally, happy if you want to copy over the documentation content in a follow up PR (which it looks was already your plan! woo! Thank you!)

**Comment by jdesrosiers** [comment]
@micshar92 Sorry this slipped through the cracks. Thanks for letting us know! And thanks for volunteering to port over the change.

**Comment by micshar92** [comment]
PR is done. See #157.

**Comment by benjagm** [comment]
Merged. Huge thanks @micshar92 !
