### ISSUE TITLE
No sitemap.xml

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/website#152]
Google is upset that many URLs that don't exist, result in a 404 status. (I'm not so upset by this!)

It does note that such upsets can be avoided if we provide a sitemap!

We might be able to use a module such as https://www.npmjs.com/package/next-sitemap to provide a sitemap with minimal effort, but I've not looked into this very deeply.

**Comment by benjagm** [comment]
I am going to explore this other package: https://www.npmjs.com/package/globby

**Comment by benjagm** [comment]
Finally I am using your package. It was easy to make it work in local but I found some challenges in Cloudflare. Finally it is working in this PR: https://github.com/json-schema-org/website/pull/155

**Comment by benjagm** [comment]
Closed as completed.
