### ISSUE TITLE
Consider using Cloudflare font over Google fonts

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/website#153]
Details: https://blog.cloudflare.com/cloudflare-fonts-enhancing-website-privacy-speed/

**Comment by benjagm** [comment]
This is something nice to have. FYI the feature is still in beta.
https://developers.cloudflare.com/speed/optimization/content/fonts/

**Comment by benjagm** [comment]
I enabled this setting in cloudflare. Are you ok in clossing it?

**Comment by benjagm** [comment]
Closed as completed.
