### ISSUE TITLE
Migrate Cloudflare redirects from UI configuration to using `_redirects` file

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/website#161]
Currently redirects are configured through the Cloudflare admin area for redirect rules.
Given we are using Cloudflare pages, we can specifiy redirects using a Cloudflare Pages function, a `_redirects` file.

Ideally, we should use a file in the repo over admin area configuration where possible.

Documentation: https://developers.cloudflare.com/pages/platform/redirects

**Comment by prajjwalyd** [comment]
Hello! Can you please provide details about the existing redirects?

**Comment by prajjwalyd** [comment]
Yes Sure! I have sent you a DM on Slack.
My Display name is 'Prajjwal Yadav'.

**Comment by benjagm** [comment]
@prajjwalyd I just sent you a DM with the details of the redirect.

**Comment by benjagm** [comment]
We merged #406 but the redirect didn't worked Well need to review this behaviour.

**Comment by prajjwalyd** [comment]
@benjagm can you provide some more details on why it didn't work?

**Comment by benjagm** [comment]
I't seemed a problem with the slack redirect only. Basically, in the recording I shared that redirect rule was not using URI Paths what made it confusing to translate to the plain _redirects file. I did some changes and tests and now it seems to work.

Huge thanks @prajjwalyd
