### ISSUE TITLE
Modify the top menu to include the content buckets

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#17]
Modify the top menu to include the content buckets:
* Specification : Link to specification.md
* Docs : Link to : Link to /learn/getting-started-step-by-step.md
* Implementations : Link to implementations.md
* Blogs : Link to blogs
* Community : Link to the Community section of the Landing Page

**Comment by OlliesWorld** [comment]
I can work on this issue.

**Comment by benjagm** [comment]
done.
