### ISSUE TITLE
Fix getting started internal links

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#18]
Make it work the internal links of the index section of getting-started-step-by-step.md. "Intro", "Defining the properties" and "Nesting data structures" internal links to sections don't work. 

https://website-2v2.pages.dev/learn/getting-started-step-by-step

**Comment by OlliesWorld** [comment]
@benjagm I have a fix in for this issue with ^ PR #27

**Comment by benjagm** [comment]
Hi Roni. I left some comments in the PR. To fix this we can't change the internal links because that will break the backwards compatibility.

There is a bug with some of the links of that page and we need to find the root cause.
