### ISSUE TITLE
Add repo status badge

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/website#184]
We uses these badges on our repos. We should use one for this repo too.
https://www.repostatus.org

**Comment by Julian** [comment]
We also have a CoC badge (see e.g. https://github.com/json-schema-org/json-schema-spec badges) and for some reason it looks like the license badge that's already used here isn't picking up the license -- haven't diagnosed why though.

**Comment by gregsdennis** [comment]
I don't know... they use JSON-LD instead of JSON Schema... 😜

> These status descriptions and the URLs to the corresponding icons are also available in a [JSON file](https://www.repostatus.org/badges/latest/badges.json) or in a more formal ontology using [SKOS](https://www.w3.org/TR/skos-reference/), defined in a [JSON-LD file](https://www.repostatus.org/badges/latest/ontology.jsonld).

**Comment by benjagm** [comment]
U just pushed this PR to add this: #205

**Comment by Relequestual** [comment]
> for some reason it looks like the license badge that's already used here isn't picking up the license -- haven't diagnosed why though.

I assume it's because we have dual licence in this repo, the same as the spec repo.
I'm not sure if we want that or if we need it.

Additionally, we may need to comply with the licence from the old USJ repo. I do not think the same applies for the old blog repo though, as the content and source are different. IANAL.
