### ISSUE TITLE
lazy regex occurence number

### ISSUE THREAD

**Issue by wyfo** [json-schema-org/website#188]
In the [specifications](https://json-schema.org/understanding-json-schema/reference/regular_expressions.html) about regex, in the last four lines : 
```
{x}: Match exactly x occurrences of the preceding regular expression.
{x,y}: Match at least x and at most y occurrences of the preceding regular expression.
{x,}: Match x occurrences or more of the preceding regular expression.
{x}?, {x,y}?, {x,}?: Lazy versions of the above expressions.
```
a lazy version of `{x}` is mentioned. However, this lazy version has no meaning because `{x}` matches **exactly** x occurrences.

**Comment by benjagm** [comment]
Hi @wyfo! Our apologies for the extremely late response. Thanks a lot for the suggestion. You are totally right with your comment. We'll add it the next wave of changes to the new json-schema website.

Thanks a lot for your patience! 🙏 and please accept our apologies for not having replied earlier.

**Comment by Sanket-0510** [comment]
@benjagm you can assign this to me.

**Comment by gregsdennis** [comment]
I don't know. `{x}?` seems valid to me. It matches exactly x or zero.

**Comment by notEthan** [comment]
Interesting - it is not what I expected, but in Ruby the `?` modifier on the `{x}` quantifier does what you say. But trying it on various regex flavors on https://regex101.com/ it seems not to do that.
Also, to me `(expr){x}?` making the quantified expression _optional_ seems distinctly different than the greedy/lazy modification you get with `(expr)+?` or `(expr){x,y}?`, so would warrant rewording or clarification. But given this section is suggesting a widely-supported subset of regex syntax, I think better to exclude `{x}?` given the inconsistency.

> I'd go so far as to add {,y} ("no more than y") and {,y}? which means "no more than y, or zero".

That seems like normal greedy/lazy modification, though - `{,y}` already allows zero.

**Comment by gregsdennis** [comment]
I've tried `v(abc){4}?` at several online processors, and it doesn't appear that any of them matched on a string with just a `v` in it like `waevaweae`.  (I'd expect a match: the `v` and zero `abc`s.)

What I find particularly odd is that they're picking up the `?` as part of the quantity specifier, not as its own token.

<img width="283" alt="image" src="https://github.com/json-schema-org/website/assets/2676804/30e4a8f1-3933-4ee6-91c5-466933aa55f5">

> {,y} already allows zero.

True, but interestingly, I notice that it's not supported in any online processors (JS or .Net).

---

I'm fine leaving these out.  Confused, but fine.  (Seems like they should be a thing.)
