### ISSUE TITLE
Interlink terms in UJS with the glossary

### ISSUE THREAD

**Issue by Julian** [json-schema-org/website#192]
It seems these two resources would benefit a lot from each other, [the latter](https://json-schema.org/learn/glossary.html) as a reference for terms used in UJS, and UJS obviously as an expository resource to link to from the glossary.

Assuming others agree, I wrote a [Sphinx plugin](https://sphinx-json-schema-spec.readthedocs.io/en/latest/) which this repository could use via [intersphinx](https://docs.readthedocs.io/en/stable/guides/intersphinx.html) and am happy to send a PR adding some initial interlinks.

CC @jdesrosiers since I see it's mostly you helping move this repo along lately :)

**Comment by Atharva-Kanherkar** [comment]
hello, @benjagm I would like to work on this issue if you allow!

**Comment by benjagm** [comment]
please go ahead @Atharva-Kanherkar !!

**Comment by Atharva-Kanherkar** [comment]
Hello @benjagm, Can i get a little more context on UJS and integrating it to glossary? I kinda got lost while understanding the core issue. i Would love a little help!

**Comment by benjagm** [comment]
> Can i get a little more context on UJS and integrating it to glossary?

UJS stands for Understanding JSON Schema which is our documentation:
https://json-schema.org/understanding-json-schema

**Comment by Atharva-Kanherkar** [comment]
> > Can i get a little more context on UJS and integrating it to glossary?
> 
> UJS stands for Understanding JSON Schema which is our documentation: https://json-schema.org/understanding-json-schema
> 
> Basically this issue intends to make glossary terms used in the docs contain a link to the glossary.

So my understanding is as follows : Let's take an example such as a term : instance. We have to update the docs such that wherever the word instance occurs (wherever it is actually referring to the technical definition  of instance) we have to attach a link (here, it goes as `https://json-schema.org/learn/glossary#instance`) to the word?

**Comment by benjagm** [comment]
> So my understanding is as follows

That's my understanding as well. @Julian is this your intend with this issue?

**Comment by Julian** [comment]
> We have to update the docs such that wherever the word instance occurs (wherever it is actually referring to the technical definition of instance) we have to attach a link

Basically yes! Though not *every* time it occurs, that's quite noisy -- the point is to have a way to indicate when helpful information is available in the glossary -- a good first order approximation is "any *first* time the word occurs on a page, and generally on a page where a beginner may encounter it".

Think about Wikipedia as a good example of this, which probably even has a fancy policy for how and where to do it, but the above is probably a decent start :)

But yes that's the idea!

**Comment by Atharva-Kanherkar** [comment]
> > We have to update the docs such that wherever the word instance occurs (wherever it is actually referring to the technical definition of instance) we have to attach a link
> 
> Basically yes! Though not _every_ time it occurs, that's quite noisy -- the point is to have a way to indicate when helpful information is available in the glossary -- a good first order approximation is "any _first_ time the word occurs on a page, and generally on a page where a beginner may encounter it".
> 
> Think about Wikipedia as a good example of this, which probably even has a fancy policy for how and where to do it, but the above is probably a decent start :)
> 
> But yes that's the idea!

Alright, will start working on it asap!

**Comment by benjagm** [comment]
@Atharva-Kanherkar ok. I'll assign this to @lalitkumawat1m

**Comment by lalitkumawat1m** [comment]
Hey @benjagm,
I have a little doubt 
Which link format is preferred (../../learn/glossary#instance) or (https://json-schema.org/learn/glossary#instance)?

**Comment by benjagm** [comment]
> Which link format is preferred

Relative path navigation will be preferred.

**Comment by lalitkumawat1m** [comment]
Hey @benjagm,
Okay I understand your comments in pr that JSON Schema one single thing but I did not find one single glossary term for JSON schema. JSON and schema are separate glossary term in glossary page. How do I interlink them to single glossary term ? Could you please give me idea about that?

Sorry for mentioning again but my confusion should be clear for making changes.

Thank you

**Comment by benjagm** [comment]
The whole site is explaining JSON Schema. We'll don't link at all the concept of JSON Schema.

**Comment by lalitkumawat1m** [comment]
Thank you for clarifying my doubts

**Comment by lalitkumawat1m** [comment]
Hey @benjagm,
I have made all the changes you want. Could you please review my pull request ?
