### ISSUE TITLE
UX/UI Enhancements

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#20]
- [x] **Branding support to help expand the brand.**
- [x] Brandmark and logtype refresh.
- [x] Develop primary and secondary colour palettes.
- [x] **Design creative collateral to support the text/documentation in line with the brand.**
- [x] Contextual illustrations.
- [x] Hero image.
- [x] Design theme icons.
- [x] Responsive navigation
- [x] **Responsive Landing Page mock up.**
- [x] **Figma file**
- [x] Add new brand assets to the Figma file to collate all new assets.
- [x] Annotate interactions.
- [x] Revised Doc page Design
- [x] Revised Blog page Design
- [x] Share Figma file.
- [x] **Brand repo**
- [x] Design and set up assets for JSON Schema GitHub brand repo.
- [x] Incorporate ‘Build more, break less, empower others’ strapline.

**Comment by PaulWaller** [comment]
Branding support. Revised brandmark and logotype - 1st draft 
Here we started to look at refreshing the brand. We took the existing JSON Schema brandmark and logotype and redrew and revised the geometry, so the mark and logotype are combined. We haven’t made radical changes but merely enhanced the collateral that is alrady there. We've also adjusted the cut and size of the logotype. The first page shows a colour palette, existing mark, and initial alternative ideas. This is followed by a series of pages developing one option and how that might work in the new site. 

[JSON-Schema-Brand-Refresh-V1.pdf](https://github.com/json-schema-org/website/files/11270412/JSON-Schema-Brand-Refresh-V1.pdf)

**Comment by PaulWaller** [comment]
Branding support. Design creative collateral to support the text/documentation - 1st draft.
Here we have taken keywords such as Comunity, Ai, Implentation, Integration and Validation to use as a starting point for our illustrative content. We have worked up x5 illustration that could be used to support text content on the landing page.
[Contextual Illustrations x5 - Draft.pdf](https://github.com/json-schema-org/website/files/11270446/Contextual.Illustrations.x5.-.Draft.pdf)

**Comment by benjagm** [comment]
I created a new repo for all things branding:

https://github.com/json-schema-org/brand

**Comment by PaulWaller** [comment]
For comments and feedback. This week we revised the first draft of the responsive landing page mock up to include new theme icons, stronger colours for accessibility, revised footer, updated taxonomy and provided a series of alternative hero options with the trusted section relocated.

- The theme icons have been redesigned and simplified so they contrast against the contextual illustrations and layer the information. 
- The ‘Trusted by’ section has been moved to the hero for better visibility.
- We have updated the taxonomy and footer designs. 


![Image](https://user-images.githubusercontent.com/2253876/235114279-2f7e1b3d-192a-4e10-ba43-d770c304c845.png)


![Image](https://user-images.githubusercontent.com/2253876/235114301-3b47baca-e973-496e-9b53-10e9cb85aaf2.png)

**Comment by PaulWaller** [comment]
These header and hero options explore the balance between colour, line, text, graphics. We performed accessibility check on the colours and opted for a stronger contrast which we have incorporated into the logotype refresh. 

![Image](https://user-images.githubusercontent.com/2253876/235115592-13f4035f-1112-4967-aa9e-d3a31b09cdcf.png)
![Image](https://user-images.githubusercontent.com/2253876/235115593-9628f7d4-625e-4387-84b9-6d319fc80f68.png)
![Image](https://user-images.githubusercontent.com/2253876/235115591-45159997-3c02-48b5-a62b-faec299dca76.png)
![Image](https://user-images.githubusercontent.com/2253876/235115594-1ff48c1d-f49b-4a2f-8923-2b063958ecb1.png)
![Image](https://user-images.githubusercontent.com/2253876/235115595-2d980098-50b4-49be-bf51-b321883654e2.png)
![Image](https://user-images.githubusercontent.com/2253876/235115590-90e88d44-d941-4fae-a082-b97cbfab51ef.png)

**Comment by PaulWaller** [comment]
Update Brandmark and logotype

![Image](https://user-images.githubusercontent.com/2253876/235117040-725641e8-34ce-43a8-97c6-a669f0f2d59f.png)
![Image](https://user-images.githubusercontent.com/2253876/235117050-3af31672-d985-491c-b82d-8da7a0d2a562.png)
![Image](https://user-images.githubusercontent.com/2253876/235117256-a0aa19fb-876d-43a2-b0b9-e74c5c19d86e.png)

**Comment by gregsdennis** [comment]
I think I prefer the [slanted line with blue fill](https://user-images.githubusercontent.com/2253876/235115593-9628f7d4-625e-4387-84b9-6d319fc80f68.png).  It feels cleaner and less busy but still provides a pop of color.

**Comment by benjagm** [comment]
We have a new version of the prototype considering the last feedback received here and in Slack.
Thoughts? 

![Desktop-V3](https://user-images.githubusercontent.com/40007659/236253723-c1a46472-22f4-4ff2-ac47-36cf40b7f9fe.png)

**Comment by Julian** [comment]
I'm resisting "true" bikeshedding as much as possible (which I think everyone should at this point :) -- and even doing so, feel free to ignore any of the below as being too specific for now, as I say, to me the most important thing is getting live, and there's nothing completely bad about what's there, it's good even as is for a v1 -- great even.

In fact maybe the only thing I'll say at the minute is I think it needs ~50px at least more padding!

But yeah anything else is very minor and subjective, so I'll keep it for now even.

**Comment by benjagm** [comment]
My only comment is change the 4 points of Why JSON Schema section from the current 3 + 1 to a 2 x 2 layout like the [grpc](https://grpc.io/) page, but we can fine tune that during the development of the page.

**Comment by PaulWaller** [comment]
Hi @benjagm we have incorporeated the latest comments up to the Friday 12th into the this link to the [Figma file](https://www.figma.com/file/khNXlsxKXkLwolnl16kmzI/Site-Mock-up?type=design&node-id=6%3A113&t=jKVr6DAX7gWvNoPy-1) which has all the brand and design collateral recently developed.

Here's a brief recap of what we did interms of developing the JSON Schema Brand  .
We began the brand refresh work item by looking at the existing JSON Schema brandmark and logotype with a view to adjusting the proportions. We have taken the mark and revised the geometry, so the mark and logotype are equally weighted. We adjusted the cut and size of the logotype. We took the existing mark as our base because this is already an established brand and developed the geometry and proportions in line with the logotype. For the logotype we have utilised the 'Inter' font but used a a stronger cut. This is the first step in terms of pulling all recently developed branding collateral together and progress in this area. 

Whilst reviewing the brandmark and logotype we set out a colour palette based on strong blues and complementary colours.

These colours were then utilised within the supporting graphic collateral developed to help expand on the JSON Brand.

**Comment by benjagm** [comment]
Great work @PaulWaller !! Huge thanks.

**Comment by gregsdennis** [comment]
Questions about the color:

Why blue, and why that particular shade?

**Comment by PaulWaller** [comment]
> Questions about the color:
> 
> Why blue, and why that particular shade?

Hi, We took the to the original blue and updated the tonal range for better accessibility and contrast ratio when reversing graphic and text out of a base colour.

**Comment by gregsdennis** [comment]
> We took the to the original blue

This is where my confusion lies.  What original blue?  Or website has only ever been black and white.

I'm not complaining, just curious why blue was chosen.

**Comment by benjagm** [comment]
> What original blue?

The new landing page design started taking as input the new website development available in this same repo and (deployed [here](https://website-2v2.pages.dev/)). We discovered that the blue present there hasn't been requested by anyone and has no link with JSON Schema but we decided to explore with and without using and asked for feedback it in this slack [thread](https://json-schema.slack.com/archives/C8C4UBXDF/p1682696675868109).

I personally like it but I am sure I'll like other colors as well.

> why that particular shade?

Just to confirm: Do you mean the gradient blue or the grey shades in Why JSON Schema?

<img width="608" alt="Screenshot 2023-05-23 at 23 41 48" src="https://github.com/json-schema-org/website/assets/40007659/51751ca0-cb2e-4f47-9e0c-971cc98d461c">

If is that grey shade, we can definitely remove it.

**Comment by gregsdennis** [comment]
> Do you mean the gradient blue or the grey shades in Why JSON Schema?

I mean why this particular HSV and not something (anything) else?  Was there research that went into it, or was it just a decision by someone?  I note that it's considerably more saturated and a bit darker than the example in your linked deployed site.

**Comment by Relequestual** [comment]
@gregsdennis I think @PaulWaller means THIS repo as it was when he started collaborating with us =]

The previous person who worked on the site just decided to try some colour and picked that one. As to why, you'd have to ask @musemind.

**Comment by benjagm** [comment]
Hi everyone! I just created this collaborative [document](https://docs.google.com/document/d/1KfqVmLSXhyDVmG15eCus7LTATq4n4wovhUm8uFvMAMc/edit?usp=sharing) to build together the messaging of the new landing page. 

**Do you have experience with documentation? 
Are you talented to craft inspiring messages?** 

We need your support... we are actively looking for contributors.

**Comment by PaulWaller** [comment]
Hi Benjamin, I have updated the brand banner with redueced bottom margin and alos worked up a second version to reflect the heor on the nwe site. Here are the PNGs and SVGs. Let me know your thoughts.

![JSO-Schema-Brand-Brand-Header-V2](https://github.com/json-schema-org/website/assets/2253876/0b8e140d-97cf-4337-a879-ee8e0c09ed81)
![JSO-Schema-Brand-Brand-Header](https://github.com/json-schema-org/website/assets/2253876/02635003-2d2f-44cf-99dd-1fff635d4045)
![JSO-Schema-Brand-Brand-Header](https://github.com/json-schema-org/website/assets/2253876/dd4b11b4-9117-4e93-a239-5d77e547188e)
![JSO-Schema-Brand-Brand-Header-V2](https://github.com/json-schema-org/website/assets/2253876/5d46e973-4a8d-4ea7-88d0-eb8f8e334d6c)

**Comment by PaulWaller** [comment]
Revised Blog layout for desktop and mobile.
![Desktop-Blogs-V2](https://github.com/json-schema-org/website/assets/2253876/0ca76305-29b4-4027-b372-04eb54fdbbdd)
![Mobile-Blog-V2](https://github.com/json-schema-org/website/assets/2253876/3d29f304-5aa8-4033-8570-1e0eaec1ea5d)

**Comment by PaulWaller** [comment]
Revised layout for docs and side nav.
![Desktop-Docs-V1](https://github.com/json-schema-org/website/assets/2253876/fddcc196-25ee-4d05-b004-a0b75cb91a46)
![Mobile-Doc-V1-Overview-Nav-Open](https://github.com/json-schema-org/website/assets/2253876/73a75784-2cb3-4740-8c42-6cf59538a36c)
![Mobile-Doc-V1-Overview-Nav-Closed](https://github.com/json-schema-org/website/assets/2253876/7a0f8e6b-362a-4270-96a7-559f8aeaddfb)
