### ISSUE TITLE
Example of biredirectional relationship

### ISSUE THREAD

**Issue by snimavat** [json-schema-org/website#202]
https://spacetelescope.github.io/understanding-json-schema/structuring.html
Relations can be expressed using $ref and definitions. Can you put an example of how to handle bidirectional relationships such as below

```
class Person {
  Nose nose
}

Class Nose {
  Person person
}

```

When generating schema for person, we can have $ref and defintion for person.. but how should the person reference in nose should be handled.

Also, How many levels deep, Human > Head > Brain > Nerves etc

**Comment by benjagm** [comment]
@Relequestual @gregsdennis is it ok to close this issue?
