### ISSUE TITLE
How to create new pages

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#21]
Create a brief step by step guide to help with the creation of new pages.

Example:
https://github.com/json-schema-org/website/tree/main/pages/draft/2020-12

**Comment by OlliesWorld** [comment]
Current structure for adding pages is a bit confusing.
Typically the file name matches the title of the page and the folder for pages matches the Menu item.

You can look at the path of the url and that gives you the folders
example - `/learn/getting-started-step-by-step` - path for **Creating a schema**, its in the `learn folder`

- adding **Docs page** - depends on where it is on the left nav
   - under **Basic concepts**  create a page `page -> understanding-json-schema -> reference -> create .md file`
   - under **Advanced Concepts** create a page `page -> understanding-json-schema -> create .md file`
   - **except the **Structuring a complex schema page**

- Adding **Learn page** - depends on where it is on the left nav
   - under **Examples & studies** create a page - `page -> learn -> create .md file`
   - under **Getting started** create a page - `page -> understanding-json-schema -> create .md file`
  
- Adding **Implementation page** create a page - `page -> implementation  -> create .md file`

- Adding **Blog post** - create a page -  page > blog -> create .md file

- Adding **Specification page** currently is in the root of the` page folder`
   - if there are more pages, my suggestion would be to make a folder for **Specification pages**

As far as the `draft folders` they are mostly filled with Release notes. I would create a `release-notes` folder and move the files into there. There can be sub-folders if notes need to be broken by date or version as well.

**Comment by benjagm** [comment]
Do I need to create a .tsx page to be able to expose new .md in new folders? The md part it's clear but I am unsure about what cases requires a tsx page and what is the best tsx template to use.

**Comment by OlliesWorld** [comment]
The `.tsx` is the template for layout. When creating new page if it follows the same layout as the other pages in the section/folder, no other `.tsx` file is needed.
A new `.tsx` file is need if the layout changes or there is a new folder/section of pages.
