### ISSUE TITLE
Copying code snippets includes line numbers

### ISSUE THREAD

**Issue by gregsdennis** [json-schema-org/website#214]
For example, copying the first code block from [this page](https://json-schema.org/understanding-json-schema/reference/conditionals) and pasting directly into this text field gives

```
{
2
  "type": "object",
3


4
  "properties": {
5
    "name": { "type": "string" },
6
    "credit_card": { "type": "number" },
7
    "billing_address": { "type": "string" }
8
  },
9


10
  "required": ["name"],
11


12
  "dependentRequired": {
13
    "credit_card": ["billing_address"]
14
  }
15
}
```

The line numbers should be cosmetic and not part of the code content.  I should be able to copy this, paste it directly into an editor, and get just the schema.

---

OS: Windows 11
Browser: Chrome (latest) - Version 119.0.6045.124 (Official Build) (64-bit)

**Comment by jdesrosiers** [comment]
For reference, this is the component that's being used, https://github.com/ianstormtaylor/slate.

**Comment by benjagm** [comment]
Thanks everyone. We'll work on this as soon as possible.
