### ISSUE TITLE
White overlay text for blog preview is hard to read depending on the image

### ISSUE THREAD

**Issue by gregsdennis** [json-schema-org/website#215]
For my post, I chose an image that has some white areas, making the title really hard to read.  I don't think that just making the text black will fix this as some images are generally darker.

<img width="869" alt="image" src="https://github.com/json-schema-org/website/assets/2676804/d02cdad2-c97e-4f2b-97aa-8c0b2647b0b6">

**Comment by Julian** [comment]
(This is a common problem I think in web design) -- https://blog.iamsuleiman.com/techniques-to-display-text-overlay-background-images/ has some notes from a quick Google. I'm pretty sure I've seen scrims before even as a relative ignorant person about frontend, maybe we want one of those for all the header images.

**Comment by Relequestual** [comment]
There are only words over the image on the blog index page.
A scrim seems like a good solution.
I often add dropshadow and text border, but I can't see how to have both with CSS.

**Comment by benjagm** [comment]
I hope this PR #219 fix this.
