### ISSUE TITLE
List text is a different color from paragraph text

### ISSUE THREAD

**Issue by gregsdennis** [json-schema-org/website#216]
<img width="490" alt="image" src="https://github.com/json-schema-org/website/assets/2676804/91c3cbca-e780-4561-8eb1-901324c9be2b">

It's less apparent there, but it's _very_ noticeable when I turn on my dark-mode extension:

<img width="464" alt="image" src="https://github.com/json-schema-org/website/assets/2676804/7a5d8f9b-7df8-4cb5-a28e-c8a1a066a405">

**Comment by benjagm** [comment]
Thanks Greg. I'll work on fix this tomorrow.

**Comment by benjagm** [comment]
The PR #244 will fix this.
