### ISSUE TITLE
Implement the new website docs structure

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#22]
This is the new content taxonomy agreed in #9 

- Overview
    * What is JSON Schema? (New - Create an empty md page)

- Getting Started (Create an empty md page)
    * [Creating your first schema](https://github.com/json-schema-org/website/blob/main/pages/learn/getting-started-step-by-step.md) 
    * Examples
        * Miscellaneous examples 
        * Modelling a file system 
        * Other examples 

- Reference:
    * JSON Schema Glossary 
    * Learn JSON Schema   (Link to https://www.learnjsonschema.com)
    * Understanding JSON Schema (Existing - The structure of the book)
       * Conventions used in this book
       * What is a schema?
       * The basics
         * Hello, World!
         * The type keyword
         * Declaring a JSON Schema
         * Declaring a unique identifier
       * JSON Schema Reference
         * Type-specific keywords
         * string
         * Regular Expressions
         * Numeric types
         * object
         * array
         * boolean
         * null
         * Generic keywords
         * Media: string-encoding non-JSON data
         * Schema Composition
         * Applying Subschemas Conditionally
         * Declaring a Dialect
       * Structuring a complex schema
         * Schema Identification
         * Base URI
         * $ref
         * $defs
         * Recursion
         * Extending Recursive Schemas
         * Bundling

- Specification (Existing but poorly structured with multiple embedded sections. Requires analysis and break it into pieces)

**Comment by benjagm** [comment]
This issue is ready for implement @OlliesWorld

**Comment by OlliesWorld** [comment]
I can get started on this next week!

**Comment by OlliesWorld** [comment]
@benjagm question about which are just titles and which are pages. Are Overview, Getting Started and Reference the only titles? Every thing else are links to pages?

**Comment by benjagm** [comment]
Overview and Reference are just Titles, but Getting Started  will be the title of a main section and with new page associated if that is possible.

**Comment by benjagm** [comment]
That sounds great. 

FYI in the screenshot The Basics, JSON Schema Reference and Structuring a Complex Schema should be at same level than What is a Schema.... and if possible not using bold letters. I'll prefer to keep bold for top level sections.

**Comment by benjagm** [comment]
Let's keep bold **only** for **top level section**.  For Titles of subsections we can try:
a. Not using bold
b. Use bold but with a less intense font colour.

You can try and decide for what option works best.

**Comment by OlliesWorld** [comment]
@benjagm Here are 2 screenshots for the subtitles. Let me know what yo think. I can push up if you want to see it full browser.
first -I kept the bold and decrease the color by 200> bold-text-slate-700

![Image](https://user-images.githubusercontent.com/51091185/234407461-ce6029f7-f047-4455-90fc-1c4ce4f0ddab.png)

Second - took off bold and left the text color the same

![Image](https://user-images.githubusercontent.com/51091185/234407479-0826df60-5a33-4525-9c55-fa4fe093e2b9.png)
