### ISSUE TITLE
Table of contents on implementations page

### ISSUE THREAD

**Issue by gregsdennis** [json-schema-org/website#224]
The implementations page is large.  While there's a language index for validators (\*), there needs to be a TOC to navigate to the other sections.  The validators section itself is long enough that a viewer may not even know other sections exist.

_\* Should "online" be it's own section instead of a language?_

**Comment by Relequestual** [comment]
Agreed. I know @benjagm is working on a redesign of the implementations page. This should be taken into account.

This could be a sub-issue of https://github.com/json-schema-org/website/issues/160

**Comment by benjagm** [comment]
This is the prototype we are working on: https://docs.google.com/presentation/d/1cCjQO0tdUqf74iEtYYv7E2dHxYyZbbzL_sEQ1_64W1Y/edit?usp=sharing

**Comment by benjagm** [comment]
Closed in favour of #160
