### ISSUE TITLE
Identify tech stack

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#23]
Identify the project Tech Stack.

**Comment by OlliesWorld** [comment]
Here are the main packages in the repo currently:
React - 17
Next.js - 12
Typescript
TailwindCSS - CSS framework
Feed - syndicate feeds
Gray-matter - front matter -> jsx is-yaml - human-friendly data serialization language
markdown-to-jsx - markdown -> jsx
PostCSS - lint CSS
reading-time - estimates time to read article
Slate/slate-react - framework build rich text editor
zero-fill -Zero-fill a number to the given size
zustand - bearbones state-management solution

**Comment by benjagm** [comment]
Thanks @OlliesWorld. This is exactly what we were looking for.
