### ISSUE TITLE
UJS arrays reference needs content work

### ISSUE THREAD

**Issue by gregsdennis** [json-schema-org/website#231]
https://json-schema.org/understanding-json-schema/reference/array

There's a lot that's confusing here.  A lot of the examples use `prefixItems` when talking about pre-2020-12 versions.

Related to https://github.com/orgs/json-schema-org/discussions/535

**Comment by jdesrosiers** [comment]
Can you be more specific? There aren't any examples using pre-2020-12 versions. UJS covers only the latest release, but also includes "Draft Specific" boxes where necessary to give information about how previous versions were different.

**Comment by gregsdennis** [comment]
Looks like it might be a rendering issue.

Here's the intended format of the draft-specific info.  It's isolated to the yellow block.

<img width="657" alt="image" src="https://github.com/json-schema-org/website/assets/2676804/36b8baa8-7987-47a1-ab45-507095afda1d">

Here's later down the page.  The container doesn't render, and it looks like the code below it is related.

![image](https://github.com/json-schema-org/website/assets/2676804/b08be121-be63-4f4b-85ec-29cbcdeaf0d4)

---

> UJS covers only the latest release

There is a blurb at the beginning of the "book."  But since it's only online now and people can navigate directly to where they want to go, it's likely that a reader will never see it (as the person to started the discussion probably did).

**Comment by jdesrosiers** [comment]
Agreed. That draft-specific box should be rendered like the other one. It should be more clear that it's an aside and not part of the main content.

**Comment by srini047** [comment]
@benjagm I would like to take up this issue.
So to my understanding, this Draft-specific info of the latter image needs to be formatted to display like the actual one referenced.

**Comment by benjagm** [comment]
> I would like to take up this issue.

You are right. A pointer for you: Please check **TabsGroup** component inside components/StyledMarkdown.tsx.

**Comment by benjagm** [comment]
@srini047 are you still working on this?

**Comment by srini047** [comment]
> @srini047 are you still working on this?

Yes @benjagm , will make PR soon.
