### ISSUE TITLE
Who's using JSON Schema / logos of companies

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/website#235]
It would be great to have a logo wall of companies or orgs that use JSON Schema.
For a good example, see https://www.fastify.io

Requirements:

- [ ] Data drive using a JSON file
- [ ] Logos will be colour
- [ ] Logos link to a URL defined in JSON data
- [ ] Can tag orgs as company or project (or both)
- [ ] Page with instructions on how to add your own (via PR)
- [ ] Date driven selection of logos for the home page
- [ ] Stand alone page which shows all the logos

Postman is confirmed as the first logo we can use. Approved.

The website repo is located at https://github.com/json-schema-org/json-schema-org.github.io
You will need docker to build it locally.

**Comment by benjagm** [comment]
It is ok if close this in favour of the Adopters list and #144 ?

**Comment by Relequestual** [comment]
Closing in favour of #144
