### ISSUE TITLE
How to modify the content taxonomy

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#24]
Create a quick guide to explain the optimal way to modify the docs structure of Learn Section in the left side area (see image)

![Image](https://user-images.githubusercontent.com/40007659/233005447-0fb49a7a-3baf-4bbe-a1a4-ba9e42d289ea.png)

**Comment by OlliesWorld** [comment]
This is updated in the `Layout.tsx` file under the `DocsNav` section starting at line 195.
here is the first 2 sections as an example:
```html
<div suppressHydrationWarning={true} className='pt-2 pr-2'>
    <SegmentHeadline label='Overview' />
        <DocLink uri='/welcom' label='Welcome' />
      <SegmentHeadline label='Getting started' />
        <DocLink uri='/creating-a-schema' label='Creating a schema' />
      <div className='pl-4 pb-1 pt-1'>
      <SegmentHeadline label='Examples and Studies' />
        <DocLink uri='/miscellaneous-examples' label='Miscellaneous Examples' />
        <DocLink uri='/example-file-system' label='Example &apos;File system&apos;' />
        <DocLink uri='/more-exampples' label='More Examples' />
      </div>
        <DocLink uri='/glossary' label='Glossary' />
</div>
``` 

When you have a sub section like `Examples` , wrap that section in the `<div className='pl-4 pb-1 pt-1'>`. Otherwise every section just starts with a `SegmentHeadline` and followed by `DocLink`

**Comment by benjagm** [comment]
Is there a limitation in the number of hierarchies?
Is there an option to change the style of the sections to make them dropdown in the future? I am asking just in case this menu grows so much.

**Comment by OlliesWorld** [comment]
There is not a limitation to hierarchies, from a user experience 2-3 is usually the most without getting confusing.
Yes, changing to dropdown is an option but would mean some code would need to change.

**Comment by benjagm** [comment]
Done.
