### ISSUE TITLE
Add a newsletter subscribe form to the Landing Page

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#243]
Related Issue: [/community#440](https://github.com/json-schema-org/community/issues/440)

#### Reason/Context
In order to start using the newsletter we need to add a subscribe form to the landing page. This will be created inside the section currently used with a call to action to Contribute. We'll replace with a call to action to subscribe.

<img width="1512" alt="Screenshot 2023-11-24 at 10 32 54" src="https://github.com/json-schema-org/website/assets/40007659/666ebb37-169b-4194-943d-acb84a371457">

#### Description
- This is not a breaking change, the section already exists in the landing page, we just need to replace it with the form details.
- The form and fields ids are the ones used in this Mailchimp sign-up form: http://eepurl.com/iDbuEk
- Follow [this guide](https://mailchimp.com/help/host-your-own-signup-forms/) to extract the key information from the Mailchimp sign-up form.
- Use the asyncAPI approach as inspiration.
<img width="1197" alt="Screenshot 2023-11-24 at 10 36 48" src="https://github.com/json-schema-org/website/assets/40007659/0eb79a9e-8d66-492e-8230-bb7b26bd2c77">

**Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No

**Comment by benjagm** [comment]
We can also use a different approach and add the form in the footer like https://mui.com/

<img width="1512" alt="Screenshot 2023-11-27 at 10 20 16" src="https://github.com/json-schema-org/website/assets/40007659/fab1e906-36e2-4ce2-9869-0a93e4516774">

**Comment by ayushnau** [comment]
@benjagm should i start working on this.

**Comment by ayushnau** [comment]
https://github.com/json-schema-org/website/pull/308

**Comment by ayushnau** [comment]
@benjagm on clicking on subscribe button should the user go to another page or remain in that page only.

**Comment by benjagm** [comment]
@ayushnau one big favour. Can you please rebase? I am going to merge this.

**Comment by benjagm** [comment]
Can you please change the target branch to https://github.com/json-schema-org/website/tree/web-release-3?

Reference docs: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by DhairyaMajmudar** [comment]
@ayushnau do you need any help for the pr, feel free to ask : )

**Comment by benjagm** [comment]
Completed.
