### ISSUE TITLE
Blog filters by querystring

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#251]
#### Reason/Context
This feature will help to create links to show specific categories of articles like case studies.

#### Description
Just enable filtering with querysting by url.

**Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No

**Comment by nikhilyadav24** [comment]
Hey @benjagm , Please assign this to me.

**Comment by jayprakash25** [comment]
Hey @benjagm , I would like to work on this!

**Comment by benjagm** [comment]
Thanks  @jayprakash25 . @utnim2 will continue the work done in #289

**Comment by jayprakash25** [comment]
@benjagm should I start working on this or was this assigned to @utnim2 . Should I start working on something else? I'm keen to contribute anywhere needed.

**Comment by utnim2** [comment]
> @benjagm should I start working on this or was this assigned to @utnim2 . Should I start working on something else? I'm keen to contribute anywhere needed.

You can check #130 @jayprakash25
