### ISSUE TITLE
Reference pages broken on iOS safari (invalid Regular Expression)

### ISSUE THREAD

**Issue by anttiviljami** [json-schema-org/website#255]
#### Describe the bug
<img src="https://github.com/json-schema-org/website/assets/6105650/e249e07a-79cf-44c1-a4de-1573523bac0d" height="500" />

#### How to Reproduce
Launch any reference page on iOS Safari, e.g. https://json-schema.org/understanding-json-schema/reference/string

#### Expected behavior
Should render the page on iOS safari

#### Details
![Screenshot 2023-12-02 at 11 04 49](https://github.com/json-schema-org/website/assets/6105650/dcffad33-dfbe-4152-87b2-c66a087ea177)
![Screenshot 2023-12-02 at 11 05 40](https://github.com/json-schema-org/website/assets/6105650/aa1c26a6-ef2a-42fc-a0c3-6e3d4384fbae)

**Comment by Relequestual** [comment]
Hey @anttiviljami 
Firstly thanks for reporting.
Secondly, can you let me know specifically what version of iOS you're using here please? =]

**Comment by anttiviljami** [comment]
![5A928B24-5BEA-4E6D-9799-5DB6168BDD4F](https://github.com/json-schema-org/website/assets/6105650/940f6451-617f-4f89-9d18-cfb9d9968d60)

**Comment by kayx23** [comment]
I experience the same in my MacBook air Safari. None of the navbar items can be rendered:

![image](https://github.com/json-schema-org/website/assets/39619599/43912afc-30bc-4838-a588-4ac3f8559a32)

In Chrome it works fine.

I'm on Catalina (...yes still).

**Comment by benjagm** [comment]
Thanks @anttiviljami and @kayx23 ! Can you please check if the issue has been fixed here:
https://6ca79aae.website-2v2.pages.dev/understanding-json-schema/reference/string

**Comment by kayx23** [comment]
@benjagm still happening for me

![image](https://github.com/json-schema-org/website/assets/39619599/09ea85e6-8526-416b-bc12-f72ea71bcf70)

**Comment by Relequestual** [comment]
It looks like lookbehind support was added in Safari 16.4. I assume this means iOS 16.4 onwards too.
Relevant PR: https://github.com/WebKit/WebKit/pull/7109

If are are able to update, this would be ideal.
If anyone else is able to identify and fix the problem, we would welcome a further PR.

**Comment by MonalSD** [comment]
@benjagm It would be great if you can assign this issue to me. i’ll start on it

**Comment by benjagm** [comment]
This is a difficult one @MonalSD . All yours.

I tried myself in this draft PR but it didn't work: https://github.com/json-schema-org/website/pull/257

**Comment by MonalSD** [comment]
@benjagm I tried but couldn't reach to the desired solution. Thankyou

**Comment by vickywane** [comment]
Hello @benjagm, 

Has there been any other release to fix this bug? 
I'd love to give it s shot. 

Starting with reproducing the error across my devices.

**Comment by benjagm** [comment]
> Has there been any other release to fix this bug?

No. We could not fix it. Thanks a lot for your interest on this one.
