### ISSUE TITLE
Add the "Join the Slack" button to the hero

### ISSUE THREAD

**Issue by Julian** [json-schema-org/website#261]
#### Reason/Context
If we're trying to drive users to engage with us on Slack it seems like making the Slack button even more prominent may help. I had to dig for it just now slightly in trying to send a link to a user.

#### Description

![Screenshot 2023-12-14 at 11 17 44 AM](https://github.com/json-schema-org/website/assets/329822/36e77110-ab8f-480a-a1e0-091996c81812)

There's 2 options presumably -- one is to add a fourth button. The other is to *replace* the "Community" link with a "Join the Slack" button, and to let someone interested in the rest of the community links just find them by scrolling down the page.

I'd possibly lean towards the latter, but it doesn't seem either is clearly better to me.

**Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

Yes/No
No

**Comment by gregsdennis** [comment]
I think it could be valuable to have both.  Most people who engage with us will mostly likely have a GH account, but I bet a non-trivial number will not have or want a Slack account.  Giving them the option of where to engage seems a bit more welcoming to me.

**Comment by Relequestual** [comment]
We could add a GitHub link under the bow Slack link. Want to make a new issue @gregsdennis ?

**Comment by gregsdennis** [comment]
Why pose the question and then create a PR that doesn't take responses into consideration?

I'm not creating a new issue for this. I'm reopening this one as not completed.

**Comment by benjagm** [comment]
> Why pose the question and then create a PR that doesn't take responses into consideration?

Hi everyone. After the holiday break I worked on several issues and PR and this was one of them and with the bulk of changes I missed you last comment @gregsdennis , my apologies for that.

If you guys like to add Github and Slack buttons in the Hero section I am concerned that seems to call to actions there.

I suggest 2 options:
1. Leave the slack button there and add a github icon in the top menu like [AsyncAPI](https://www.asyncapi.com/).
2. revert the change and leave a community button like it was before and add Slack and Github button in the top menu like [ArgoCD](https://argoproj.github.io/).

**Comment by Min2who** [comment]
cc @Relequestual @benjagm

**Comment by benjagm** [comment]
@Min2who That sound good to me ... feel free to proceed with a PR.

**Comment by benjagm** [comment]
Hi @Min2who. We have been trying to iterate the PR #300 with you but we haven't receive any response, this is why we have proceed with other solution for this issue that is now fixed in production.

Thanks a lot for starting the work on this and let's keep working on your other PRs.

**Comment by Min2who** [comment]
Hii @benjagm sorry for late response i am having exam at the moment and thats why was not that active

**Comment by benjagm** [comment]
@Min2who I hope the exams want well!

**Comment by Sanket-0510** [comment]
Hey @Min2who are you still working over this? If you are having exams then I can address this further works?
