### ISSUE TITLE
Host the Code of Conduct in the website

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#278]
#### Description
It would be great to have the [code of conduct](https://github.com/json-schema-org/.github/blob/main/CODE_OF_CONDUCT.md) hosted in the website. This will provide a better url and also will increate the consistency and quality of the website's content. 

Ideally, we'll use Github submodules.

* The location of the code of conduct will be: pages/overview/coc/_index.md
* The location inside the docs menu will be: overview->Code of Conduct

**Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No

**Comment by Min2who** [comment]
@benjagm we want to place the submodule in the root of the project right?

**Comment by benjagm** [comment]
Thanks for your interest @Min2who!! The resulting output of this issue will be very similar to the result of this [PR](https://github.com/json-schema-org/website/pull/246) in which we published the sponsors packages available in the community repo using a symlink.

**Comment by benjagm** [comment]
I just added some additional details to the body of the issue.

**Comment by Min2who** [comment]
> I just added some additional details to the body of the issue:
> 
> * The location of the code of conduct will be: pages/overview/coc/_index.md
> * The location inside the docs menu will be: overview->Code of Conduct

@benjagm thnx. Working on it
