### ISSUE TITLE
Create a new page for Community inside the Overview Section of the Docs.

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#280]
#### Description
Create a new page for Community inside the Overview Section of the Docs.
 * Explaining all community channels.
 * All community meetings.
 * Blog.
 * All community programs.
 * Members of the tsc, contributors and ambassadors.

**Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No

**Comment by Min2who** [comment]
@benjagm working on it

**Comment by benjagm** [comment]
Thanks @Min2who ! We didn't have a design yet but in my mind this is the a great example of Community page: https://www.asyncapi.com/community

Happy to provide a low-level prototype of the page.

**Comment by Min2who** [comment]
> Thanks @Min2who ! We didn't have a design yet but in my mind this is the a great example of Community page: https://www.asyncapi.com/community
> 
> Happy to provide a low-level prototype of the page.

@benjagm i should work on this or not as you have assigned it to yourself

**Comment by praveen-rikhari** [comment]
Hii @benjagm do you have the low level prototype ready, if yes can you please share it here, i would like to work on this and atleast have a foundation set up for the page

**Comment by benjagm** [comment]
This is the prototype of the new page I'd love to have. Sections:

1. Hero
2. Section with 2 columns
2.1 Card for Roadmap 
2.2 Card for contributing guidelines
3. Card Section for slack 
4. Card for ambassadors program
5. Card for events (reuse code from the landing page) (content of future events is dynamic. see landing)
6. Card for blog (In the right side well show the last blog published like we do in the landing page)

![Image](https://github.com/json-schema-org/website/assets/40007659/1daf2b70-535a-4dfd-851a-67af1a1a8f54)
![Image](https://github.com/json-schema-org/website/assets/40007659/e8326061-0a76-47eb-ad5a-151125407769)

For this prototype I used screenshot from others sites so you will need to adapt colours and styles to JSON Schema.

Please leave fake text for all sections and as soon we are fine with the design I'll complete the PR with the real texts/links.

**Comment by pi600** [comment]
can i get assigned and work on it @benjagm

**Comment by benjagm** [comment]
Thanks for your interest @pi600 All yours. The prototype is just low fidelity. You'll need to adjust all the styles to JSON Schema and be creative. Reach out to me in Slack anytime if you have doubts.

For the text, please use fake text for all sections and as soon we are fine with the design I'll complete the PR with the real texts/links.

This new page will go under the overview section in the sidebar of the docs.

Thanks!

**Comment by benjagm** [comment]
@pi600 let us know if you need support. @varunsh17 offered help with this one. @utnim2 Could you please join me as reviewer of the PR?

**Comment by benjagm** [comment]
Hi @pi600 we'll need to increate the priority of this issue because there are others depending on it. I will make this available for others to work on this. Thanks.

**Comment by officeneerajsaini** [comment]
I want to work on this issue

**Comment by benjagm** [comment]
Thanks helping with this one. All yours.

**Comment by officeneerajsaini** [comment]
Thanks for assign to me 🫠@benjagm

**Comment by benjagm** [comment]
Hey @officeneerajsaini When creating the border/shadow effects for each big card/section please use the same format we are using in the landing page for this section:

<img width="876" alt="Screenshot 2024-03-03 at 23 40 43" src="https://github.com/json-schema-org/website/assets/40007659/254f5d13-a9c6-4358-b691-192f81e99afe">

**Comment by officeneerajsaini** [comment]
@benjagm  maybe this issue related to Json Scheme Docs ? Because i need  to done 1 Doc Contribution for Qualification Task .

**Comment by benjagm** [comment]
> @benjagm maybe this issue related to Json Scheme Docs ? Because i need to done 1 Doc Contribution for Qualification Task .

I am sorry but I dont fully understand this comment. Can you please clarifty?

**Comment by officeneerajsaini** [comment]
@benjagm Sorry for any confusion, I'm just asking if this issue is related to documentation.

**Comment by utnim2** [comment]
> 1. Hero
> 2. Section with 2 columns
>    2.1 Card for Roadmap
>    2.2 Card for contributing guidelines
> 3. Card Section for slack
> 4. Card for ambassadors program
> 5. Card for events (reuse code from the landing page) (content of future events is dynamic. see landing)
> 6. Card for blog (In the right side well show the last blog published like we do in the landing page)
> 

Hey @officeneerajsaini you need to implement the above components for creating a new community page

**Comment by officeneerajsaini** [comment]
@utnim2 yes

**Comment by officeneerajsaini** [comment]
@benjagm 
"'
46:3   error  'blocks' is defined but never used                                                                                                                                                                                                                                              @typescript-eslint/no-unused-vars
   47:3   error  'validators' is defined but never used                                                                                                                                                                                                                                          @typescript-eslint/no-unused-vars
   48:3   error  'hyperLibaries' is defined but never used                                                                                                                                                                                                                                       @typescript-eslint/no-unused-vars
   70:22  error  Replace `"md:hidden·mt-15"` with `'md:hidden·mt-15'`                                                                                                                                                                                                                            prettier/prettier
   70:22  error  Unexpected usage of doublequote                                                                                                                                                                                                                                                 jsx-quotes
   73:22  error  Replace `"overflow-hidden·orbits"` with `'overflow-hidden·orbits'`                                                                                                                                                                                                              prettier/prettier
   73:22  error  Unexpected usage of doublequote                                                                                                                                                                                                                                                 jsx-quotes
   74:24  error  Replace `"orbit-container"·data-testid="orbit-div"` with `'orbit-container'·data-testid='orbit-div'`                                                                                                                                                                            prettier/prettier
   74:24  error  Unexpected usage of doublequote                                                                                                                                                                                                                                                 jsx-quotes
   74:54  error  Unexpected usage of doublequote                                                                                                                                                                                                                                                 jsx-quotes
   75:19  error  Replace `"first-orbit"·className="orbit"·data-testid="Hero-first"` with `'first-orbit'·className='orbit'·data-testid='Hero-first'`                                                                                                                                              prettier/prettier
   75:19  error  Unexpected usage of doublequote                                                                                                                                                                                                                                                 jsx-quotes
   75:43  error  Unexpected usage of doublequote                                                                                                                                                                                                                                                 jsx-quotes
   75:63  error  Unexpected usage of doublequote                                                                                                                                                                                                                                                 jsx-quotes
   78:21  error  Replace `·src={orbit.img}·alt={orbit.alt}·className="orbit-img"·data-testid="Hero-firstimg"` with `⏎··················src={orbit.img}⏎··················alt={orbit.alt}⏎··················className='orbit-img'⏎··················data-testid='Hero-firstimg'⏎···············`  prettier/prettier
   78:64  error  Unexpected usage of doublequote                                                                                                                                                                                                                                                 jsx-quotes
   78:88  error  Unexpected usage of doublequote                                                                                                                                                                                                                                                 jsx-quotes
   81:28  error  Replace `"w-full·absolute·h-full·flex·justify-center·z-40·top-12"` with `'w-full·absolute·h-full·flex·justify-center·z-40·top-12'`                                                                                                                                              prettier/prettier
   81:28  error  Unexpected usage of doublequote                                                                                                                                                                                                                                                 jsx-quotes
   85:19  error  Replace `"second-orbit"·className="orbit"·data-testid="Hero-second"` with `'second-orbit'·className='orbit'·data-testid='Hero-second'`                                                                                                                                          prettier/prettier
   85:19  error  Unexpected usage of doublequote                                                                                                                                                                                                                                                 jsx-quotes
   85:44  error  Unexpected usage of doublequote                                                                                                                                                                                                                                                 jsx-quotes
   85:64  error  Unexpected usage of doublequote                                                                                                                                                                                                                                                 jsx-quotes
   88:21  error  Replace `·src={orbit.img}·alt={orbit.alt}·data-testid="Hero-secondimg"` with `⏎··················src={orbit.img}⏎··················alt={orbit.alt}⏎··················data-testid='Hero-secondimg'⏎···············`                                                              prettier/prettier
   88:66  error  Unexpected usage of doublequote                                                                                                                                                                                                                                                 jsx-quotes
   92:19  error  Replace `"third-orbit"·className="orbit"·data-testid="Hero-third"` with `'third-orbit'·className='orbit'·data-testid='Hero-third'`                                                                                                                                              prettier/prettier
   92:19  error  Unexpected usage of doublequote                                                                                                                                                                                                                                                 jsx-quotes
   92:43  error  Unexpected usage of doublequote                                                                                                                                                                                                                                                 jsx-quotes
   92:63  error  Unexpected usage of doublequote                                                                                                                                                                                                                                                 jsx-quotes
   95:21  error  Replace `·src={orbit.img}·alt={orbit.alt}·data-testid="Hero-thirdimg"` with `⏎··················src={orbit.img}⏎··················alt={orbit.alt}⏎··················data-testid='Hero-thirdimg'⏎···············`                                                                prettier/prettier
   95:66  error  Unexpected usage of doublequote                                                                                                                                                                                                                                                 jsx-quotes
  106:10  error  'ImplementationTable' is defined but never used                                                                                                                                                                                                                                 @typescript-eslint/no-unused-vars
  226:1   error  Delete `··`                                                                                                                                                                                                                                                                     prettier/prettier

""
Why does this error occur: 'Unexpected usage of doublequote'?

**Comment by officeneerajsaini** [comment]
> @benjagm """ 46:3 error 'blocks' is defined but never used @typescript-eslint/no-unused-vars 47:3 error 'validators' is defined but never used @typescript-eslint/no-unused-vars 48:3 error 'hyperLibaries' is defined but never used @typescript-eslint/no-unused-vars 70:22 error Replace `"md:hidden·mt-15"` with `'md:hidden·mt-15'` prettier/prettier 70:22 error Unexpected usage of doublequote jsx-quotes 73:22 error Replace `"overflow-hidden·orbits"` with `'overflow-hidden·orbits'` prettier/prettier 73:22 error Unexpected usage of doublequote jsx-quotes 74:24 error Replace `"orbit-container"·data-testid="orbit-div"` with `'orbit-container'·data-testid='orbit-div'` prettier/prettier 74:24 error Unexpected usage of doublequote jsx-quotes 74:54 error Unexpected usage of doublequote jsx-quotes 75:19 error Replace `"first-orbit"·className="orbit"·data-testid="Hero-first"` with `'first-orbit'·className='orbit'·data-testid='Hero-first'` prettier/prettier 75:19 error Unexpected usage of doublequote jsx-quotes 75:43 error Unexpected usage of doublequote jsx-quotes 75:63 error Unexpected usage of doublequote jsx-quotes 78:21 error Replace `·src={orbit.img}·alt={orbit.alt}·className="orbit-img"·data-testid="Hero-firstimg"` with `⏎··················src={orbit.img}⏎··················alt={orbit.alt}⏎··················className='orbit-img'⏎··················data-testid='Hero-firstimg'⏎···············` prettier/prettier 78:64 error Unexpected usage of doublequote jsx-quotes 78:88 error Unexpected usage of doublequote jsx-quotes 81:28 error Replace `"w-full·absolute·h-full·flex·justify-center·z-40·top-12"` with `'w-full·absolute·h-full·flex·justify-center·z-40·top-12'` prettier/prettier 81:28 error Unexpected usage of doublequote jsx-quotes 85:19 error Replace `"second-orbit"·className="orbit"·data-testid="Hero-second"` with `'second-orbit'·className='orbit'·data-testid='Hero-second'` prettier/prettier 85:19 error Unexpected usage of doublequote jsx-quotes 85:44 error Unexpected usage of doublequote jsx-quotes 85:64 error Unexpected usage of doublequote jsx-quotes 88:21 error Replace `·src={orbit.img}·alt={orbit.alt}·data-testid="Hero-secondimg"` with `⏎··················src={orbit.img}⏎··················alt={orbit.alt}⏎··················data-testid='Hero-secondimg'⏎···············` prettier/prettier 88:66 error Unexpected usage of doublequote jsx-quotes 92:19 error Replace `"third-orbit"·className="orbit"·data-testid="Hero-third"` with `'third-orbit'·className='orbit'·data-testid='Hero-third'` prettier/prettier 92:19 error Unexpected usage of doublequote jsx-quotes 92:43 error Unexpected usage of doublequote jsx-quotes 92:63 error Unexpected usage of doublequote jsx-quotes 95:21 error Replace `·src={orbit.img}·alt={orbit.alt}·data-testid="Hero-thirdimg"` with `⏎··················src={orbit.img}⏎··················alt={orbit.alt}⏎··················data-testid='Hero-thirdimg'⏎···············` prettier/prettier 95:66 error Unexpected usage of doublequote jsx-quotes 106:10 error 'ImplementationTable' is defined but never used @typescript-eslint/no-unused-vars 226:1 error Delete `··` prettier/prettier
> 
> """
 Why does this error occur: 'Unexpected usage of doublequote'?

**Comment by utnim2** [comment]
Hey @officeneerajsaini have you faced this error while running `yarn build` ?

**Comment by benjagm** [comment]
With the issue https://github.com/json-schema-org/website/issues/322 we added specific checks for linting error, format fix and typechecks. This is important when we have this high number of contributors.

You will need to fix it manually or use prettier to fix it for you with a command like this:
````
npx prettier --write path-of-the-file-to-format
````

**Comment by officeneerajsaini** [comment]
Thank You @benjagm

**Comment by benjagm** [comment]
Can you please change the target branch to https://github.com/json-schema-org/website/tree/web-release-3?

Reference docs: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by officeneerajsaini** [comment]
> Can you please change the target branch to https://github.com/json-schema-org/website/tree/web-release-3?
> 
> Reference docs: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

so I need to submit my pull request in the following format: https://github.com/json-schema-org/website/tree/web-release-3/my-branch. ? am i right ?

**Comment by officeneerajsaini** [comment]
> #### Description
> Create a new page for Community inside the Overview Section of the Docs.
> 
> * Explaining all community channels.
> * All community meetings.
> * Blog.
> * All community programs.
> * Members of the tsc, contributors and ambassadors.
> 
> **Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**
> 
> No

I think we can add this to the community section in the navbar. That should be a good place for it. What do you say about this, Benjagm?

**Comment by officeneerajsaini** [comment]
> > #### Description
> > Create a new page for Community inside the Overview Section of the Docs.
> > 
> > * Explaining all community channels.
> > * All community meetings.
> > * Blog.
> > * All community programs.
> > * Members of the tsc, contributors and ambassadors.
> > 
> > **Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**
> > No
> 
> I think we can add this to the community section in the navbar. That should be a good place for it. What do you say about this, Benjagm?

@benjagm

**Comment by radhesh1** [comment]
is this open?

**Comment by officeneerajsaini** [comment]
yes , i am still working on it .

**Comment by benjagm** [comment]
This is now merged into the dev branch.
