### ISSUE TITLE
Improve the CI/CD pipeline to add linting in the repository

### ISSUE THREAD

**Issue by utnim2** [json-schema-org/website#289]
As there is no workflow for linting in the repository, it will be really helpful

**Comment by benjagm** [comment]
There is a workflow part of the website code using ES Lint. It is disabled  for local development and it is enabled for deployments to Cloudflare. It will be beneficial to have it enabled for local development so we can anticipate deployment problems.

**Comment by benjagm** [comment]
@aialok and @Min2who could you please confirm if there is overlapping between #335 and #296 ? #335 seems to cover some more scope and more consistently.

**Comment by aialok** [comment]
> @aialok and @Min2who, could you please confirm if there is overlapping between #335 and #296? #335 seems to cover some more scope and more consistently.

No, the functionality in #335 and the functionality in this PR are completely different. Both are performing the same task, but they serve different purposes. This functionality adds the same checks, but in the Continuous Integration Pipeline, specifically in our GitHub Actions workflow, whereas the husky one will be a local check only. The husky one will check these conditions only when we try to commit locally.

There are cases where contributors bypass husky checks somehow. This is why we need to set up a CI pipeline in GitHub Actions for each PR to review whether it has passed the checks or not. This is crucial for the overall stability and safety of the project.

I have already discussed  in this issue: https://github.com/json-schema-org/website/issues/340#issuecomment-1961270454

This issue and #340 are addressing the same things, but #340 also includes checking for linting and type checking.

**Comment by benjagm** [comment]
Closed in favour of #340. Thanks a lot for your patience @utnim2 !
