### ISSUE TITLE
Fix broken links 

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/website#295]
We have a pending PR for a link checker GitHub Action.
This is great, but it has identified a number of links we need to fix.
They should be fixed before that PR is merged to avoid blocking further PRs due to failing checks.

https://github.com/json-schema-org/website/pull/291

**Comment by DarhkVoyd** [comment]
Hey, may I pick up this issue?

**Comment by Relequestual** [comment]
> Hey, may I pick up this issue?

Feel free @DarhkVoyd!
You can see the broken links found by the link checker in the checks for the linked PR: https://github.com/json-schema-org/website/pull/291/checks

In the cases where links are relative, such as [this one](https://github.com/json-schema-org/website/pull/291/checks#step:3:335), you'll need to work out the best solution, as this is a false positive.

**Comment by DarhkVoyd** [comment]
@Relequestual Hey, I am not sure if linkinator is the right tool for checking broken links for our use-case.
