### ISSUE TITLE
Problem with Slack redirection

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#30]
The slack redirection configured in next.config.js works in local environment (http://localhost:3000/slack) but not once deployed at [cloudflare](https://website-2v2.pages.dev/slack) and it returns 404

![Image](https://user-images.githubusercontent.com/40007659/234554454-58b2d723-4f22-478a-ba3d-b4af9488fc86.png)

**Comment by OlliesWorld** [comment]
The redirect is for the the link in the community text above.
I will push up the correct link for the `Open Slack Workspace` section

**Comment by benjagm** [comment]
I Roni. Sorry for not having provided more details about the issue. The problem wasn't the link in the community section, the problem is the the redirect to slack in the page "/slack". This works in local environment but returns 404 in cloudflare https://website-2v2.pages.dev/slack and we need to identify the reason and fix it.

This redirect is required and is already in production in the old site this way: https://json-schema.org/slack
