### ISSUE TITLE
Fragment links to e.g. the glossary obscure the heading

### ISSUE THREAD

**Issue by Julian** [json-schema-org/website#302]
#### Describe the bug
If you visit https://json-schema.org/learn/glossary#meta-schema (e.g. via a link to there), the heading (i.e. the term you've been linked to) is obscured off the top of the page.

#### How to Reproduce

Click https://json-schema.org/learn/glossary#meta-schema or any other fragment link

Here (Firefox 123 on macOS) I see:

![Screenshot 2024-02-11 at 9 31 35 AM](https://github.com/json-schema-org/website/assets/329822/c8336b8f-7c23-4479-89b8-98abfc1d6da1)

where the heading (`meta-schema`) has been obscured by the navbar.

#### Expected behavior
Some margin should push the heading downward so it's at the top of the viewport rather than just above it / behind the navbar.

**Comment by Relequestual** [comment]
May be able to fix with something like this: https://stackoverflow.com/questions/23651942/css-single-column-layout-centered-fixed-width-100-height-w-header-and-footer 
Although I expect this can be done with tailwind classes as opposed to needing to specify the CSS directly.

**Comment by Akshaybagai52** [comment]
Hey @Julian it will be quick fix with " scroll-margin-top: 100px;" can i work on this issue 
Thanks

**Comment by benjagm** [comment]
> Hello there! @benjagm Can I work on this issue?

@Codesmith28 please go ahead! Thanks!

**Comment by Codesmith28** [comment]
Hello there!
I have worked on this bug and resolved it.

Here is the screenshot showing the same:

![image](https://github.com/json-schema-org/website/assets/117557273/0de33928-4fe8-4e28-87e9-b573939dff3d)

When shall I create a pull request for the same?

**Comment by VivekJaiswal18** [comment]
@benjagm I think it would be a good first issue for me can I work on this. 
Good Day!

**Comment by benjagm** [comment]
Closed as completed.
