### ISSUE TITLE
Highlight fragment headings when clicked

### ISSUE THREAD

**Issue by Julian** [json-schema-org/website#303]
#### Reason/Context
When visiting https://json-schema.org/learn/glossary#meta-schema or some other link to a fragment on the site, it would be nice if some highlighting indicated the active fragment / heading.

#302 is related inasmuch as when you visit a fragment link where the heading is one of the *bottom* ones of the page, they may *not* be at the top of the viewport, so highlighting is nice to make it clear where someone should look

#### Description
Highlight the active heading in some highlight color when the heading is clicked, or when visited via a fragment.

**Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

Yes/No
No

**Comment by DhairyaMajmudar** [comment]
@benjagm if it is available shall I pick this up ?

**Comment by DhairyaMajmudar** [comment]
@benjagm can you pls. assign this issue to me : )

**Comment by VivekJaiswal18** [comment]
@benjagm hey can I take this issue I am willing to work on this issue. 
@DhairyaMajmudar can i take up on this issue

**Comment by DhairyaMajmudar** [comment]
sure @VivekJaiswal18 how's about working in collaboration for this issue

**Comment by dauinh** [comment]
@DhairyaMajmudar @VivekJaiswal18 I'd love to help out as well!

**Comment by nikhilyadav24** [comment]
Hey @benjagm , Please assign this to me.

**Comment by benjagm** [comment]
@divyaxdv this issue is being worked by @utnim2 in #304 . Feel free to join the discussion in that PR and suggest improvements in the code.

**Comment by Community-Programmer** [comment]
I want to work on this if no one is working, Please assign me.

**Comment by Khaleeq01** [comment]
@benjagm Would you assign this issue to me.

**Comment by benjagm** [comment]
Go ahead @Khaleeq01 !

**Comment by Community-Programmer** [comment]
@benjagm 
Please assign me

**Comment by benjagm** [comment]
> With all the PRs closed, I believe this issue is no longer in progress status.

Thanks for the heads up DV. I think nobody implemented it so this is available for contributors to implement it.

**Comment by DhairyaMajmudar** [comment]
Shall I take this up : )

**Comment by Adity20** [comment]
Can I work on this @benjagm ?

**Comment by benjagm** [comment]
Dhairya thanks! Go ahead.
