### ISSUE TITLE
Add Test For broken Links, Covering whole website. 

### ISSUE THREAD

**Issue by ayushnau** [json-schema-org/website#307]
#### Reason/Context

So Currently there are no Tests Written for Broken Links For websites. Adding this will ensure that the website works seamlessly without any broken links, which otherwise might not be good for the website.

#### Description
We can use puppeteer and jest For Implementing the tests. 

No this will not require any Architectural Changes as this is a completely different module on its own.

**Comment by ayushnau** [comment]
@Relequestual please review this pr.

**Comment by benjagm** [comment]
Closed in favour of #103
