### ISSUE TITLE
[ Help Needed ] Expected linebreaks to be 'LF' but found 'CRLF' On Windows

### ISSUE THREAD

**Issue by JeelRajodiya** [json-schema-org/website#313]
I have just cloned the repo and opened it in vscode. 

If I open any file, this ESLint error pops up. 
![image](https://github.com/json-schema-org/website/assets/63534268/ff808559-dd17-4465-844f-c0d06c9c7292)

![image](https://github.com/json-schema-org/website/assets/63534268/eda01476-43da-4fe2-bb51-8d5df2f064b4)

I can resolve this issue by modifying the **linebreak-style** to **windows** in .eslintrc.js, However I don't think that is the correct solution. 

![image](https://github.com/json-schema-org/website/assets/63534268/82170534-177a-4299-b960-d179766a8884)

Can anyone help me resolve this problem ?

**Comment by JeelRajodiya** [comment]
This Solutions seem to work, Can anyone please let me know if this is the right way to do it or not? 
![image](https://github.com/json-schema-org/website/assets/63534268/db9d4849-516a-4a32-aeec-64a99ee7d865)

**Comment by Gaurav-Verma07** [comment]
I also get this issue on windows.
your solution works for me.
Not sure if we can further optimize it.

**Comment by Relequestual** [comment]
You might find this article useful: https://markoskon.com/line-endings-in-vscode-with-git-and-eslint

**Comment by JeelRajodiya** [comment]
# Solved it 

## First, Change the EOL setting to \n in vscode 
![image](https://github.com/json-schema-org/website/assets/63534268/98b6dab5-29c2-4c9e-996c-c3c24e6a34de)

## Then, run the following commands 
```
git rm -rf --cached .
git reset --hard HEAD
```

## and then restart vscode
