### ISSUE TITLE
Feature : Update Twitter logo

### ISSUE THREAD

**Issue by DhairyaMajmudar** [json-schema-org/website#324]
#### Reason/Context

Since X ( Formerly Twitter) updated its logo and company name it's a good idea to update it in the website footer also.

#### Description

Updating Twitter logo and company name to new logo.

**Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No
Since its a very small feature change.

**Comment by DhairyaMajmudar** [comment]
@benjagm what are your views for this change ?

**Comment by benjagm** [comment]
Sound good. Please go ahead.

**Comment by benjagm** [comment]
Merged. Nice job @DhairyaMajmudar !
