### ISSUE TITLE
Header components alignment seems inconsistent mobile view.

### ISSUE THREAD

**Issue by Mvishal123** [json-schema-org/website#328]
#### Describe the bug
The header components right elements (Search and Menu) can we

#### How to Reproduce
Click this link: [https://json-schema.org/](https://json-schema.org/)

![Incorrect](https://github.com/json-schema-org/website/assets/113995907/e5a2db59-d535-473a-abf3-c2f1cf785230)

https://github.com/json-schema-org/website

components/layout.tsx

#### Expected behavior
It's a minor fix but still creates a great impact for mobile users by making the spacing consistent.

**Comment by Mvishal123** [comment]
I made a fix for this issue. What do you all think about it?

**Comment by benjagm** [comment]
Thanks for opening this issue. Please proceed with the PR.

**Comment by benjagm** [comment]
Closed as completed.
