### ISSUE TITLE
Get previews for PRs from forks

### ISSUE THREAD

**Issue by gregsdennis** [json-schema-org/website#330]
#### Describe the bug
Currently, it seems that preview sites are not generated for PRs from forks.  This is annoying.

#### How to Reproduce
Example: https://github.com/json-schema-org/website/pull/314

#### Expected behavior
It should generate a preview site, like [this](https://github.com/json-schema-org/website/pull/277#issuecomment-1922165611).

**Comment by benjagm** [comment]
This is how Cloudflare works. Preview only works with deployments from branchs:

https://developers.cloudflare.com/pages/configuration/preview-deployments/

**Comment by benjagm** [comment]
Maybe you can add a note in the CONTRIBUTING.md file?

**Comment by Min2who** [comment]
Hey @benjagm working on it

**Comment by benjagm** [comment]
> Hey @benjagm working on it

Thanks for your interest and proactivity. Please wait until @gregsdennis have time to reply and share more thoughts.

**Comment by Relequestual** [comment]
It is possible but requires additional setup.
We would have to create a new CloudFlare Pages project, and use the API to make the deployments.

We would need to make a CI script which would...

- Run the build locally.
- Direct upload using the [Wrangler API tool](https://developers.cloudflare.com/pages/get-started/direct-upload/) making sure to specify it's a preview.

There's a guide here: https://developers.cloudflare.com/pages/how-to/use-direct-upload-with-continuous-integration/

If we agree it's worth doing, I'm happy to at least start off that work.

**Comment by benjagm** [comment]
> Please have a look at #297

What is the relationship of that issue with this one @Min2who ?

**Comment by benjagm** [comment]
> If we agree it's worth doing

I think having the previews will for PRs from forks will be great.

**Comment by Min2who** [comment]
> > If we agree it's worth doing
> 
> I think having the previews for PRs from forks will be great.

@benjagm please look at the discussion [here](https://github.com/json-schema-org/website/pull/297#discussion_r1486017558)

**Comment by gregsdennis** [comment]
@Min2who I think that's only tangentially related.  This issue is for having the CI generate preview sites for PRs from forks like it does for PRs from this repo.

While that PR would benefit from resolving this issue, I don't think it addresses this issue at all.

**Comment by ashu8912** [comment]
Hii Folks I was looking at https://github.com/json-schema-org/website/tree/main/.github/workflows but I don't see the workflow for creating previews for PRs when they are created through a branch, how do we achieve that??

**Comment by utnim2** [comment]
> Hi everyone! Cloudflare does not provide preview for PRs opened from forks, only from branches of the same org so we'll need to do some work in cloudflare for this. @Relequestual and I are working on this.

Hey @benjagm have you and @Relequestual have given thought of deploying it to `vercel` as vercel does give a previews of PR

**Comment by benjagm** [comment]
> have given thought of deploying it to `vercel` as vercel does give a previews of PR

I think it is ok what we have now. We just need some time to do this setup in cloudflare.

**Comment by benjagm** [comment]
Thanks Alok! All yours.

**Comment by gregsdennis** [comment]
Please be aware that this will likely require tasks in Cloudflare, which will require someone with access.

**Comment by aialok** [comment]
Hey !!
I've spent the past few days trying to figure out how to get previews for PRs from the fork repository. Unfortunately, none of the configurations I tried seemed to work.
 However, I finally found a solution in the GitHub Marketplace.
[Refined Cloudflare Pages Action](https://github.com/marketplace/actions/refined-cloudflare-pages-action) is being used by several well-known open-source projects, some with over 3k stars:

- https://github.com/huntabyte/shadcn-svelte
- https://github.com/melt-ui/melt-ui
- https://github.com/huntabyte/bits-ui

I reached out to the maintainer of this GitHub action about security concerns, and he confirmed that it's safe to use.


![image](https://github.com/json-schema-org/website/assets/66772290/ee2f408e-e341-4211-895e-5284ea22a5b9)

While testing this in my organization's dummy repository, I encountered a major bug. I notified the maintainer through Discord, and  he have fixed this now.
However,  there is one downside of this as we have to remove native cloudflare github-apps support from this and we need to write our own workflow for productions and preview.

Here's a preview of my PR:

PR URL: https://github.com/AuroraBenzyl/Testing-Cloudflare-Pages/pull/22

Preview URL: https://761499e4.testing-cloudflare-pages-7wt.pages.dev/

Production URL: https://testing-cloudflare-pages-7wt.pages.dev/

Workflow : https://github.com/AuroraBenzyl/Testing-Cloudflare-Pages/blob/master/.github/workflows/preview.yaml

![Screenshot from 2024-05-16 21-34-11](https://github.com/json-schema-org/website/assets/66772290/1a369182-f8fe-4666-8419-901887afc3a9)


Also, this is a known issue to Cloudflare they might fix this in future:
https://developers.cloudflare.com/pages/platform/known-issues/#builds-and-deployment

Looking for your thought on this!!!

Thank you  : )

**Comment by benjagm** [comment]
What do you think @Relequestual ? This ok for me.
