### ISSUE TITLE
Adding multi-language support.

### ISSUE THREAD

**Issue by deveshidwivedi** [json-schema-org/website#334]
#### Reason/Context

Adding multi-language support to a website enhances its accessibility and usability by allowing users to interact with the content in their preferred language. This improvement is motivated by the need to cater to a diverse user base, demonstrating a commitment to inclusivity and diversity.
#### Description

- Implementation of language switching functionality in the user interface.
- Updating text content across the website to support multiple languages. 
- Implement language switching using a dropdown menu, flags, or text links.
- Ensure proper handling of translated content, including text expansion/contraction.

**Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

Yes

**Comment by deveshidwivedi** [comment]
If this issue can be worked upon at present, I'd like to contribute to it.

**Comment by benjagm** [comment]
This is a huge amount of work and I don't think our website structure is ready for it. I think we need first to make a lot of work with our current docs before we can consider this as something to start working on. What do you think @Relequestual ?

**Comment by benjagm** [comment]
We have decided to close this issue for now @deveshidwivedi . Thanks a lot for opening it! We think we need first hard work with the current version of docs and make sure they are great. In the future maybe we can revisit this proposal.
