### ISSUE TITLE
ci: Add a pr naming convention

### ISSUE THREAD

**Issue by utnim2** [json-schema-org/website#338]
#### Reason/Context
With the current inflowing of PR it is very hard to track which PR target what type of issue it want to solve for eg( a bug, feature request, workflow, docs )
![image](https://github.com/json-schema-org/website/assets/127925465/c7cea16e-0f3a-468f-b1de-a20e00e9fc57)

#### Description
To implement the PR naming convention, I propose the following guidelines

-  PR titles should start with a prefix indicating the type of change being made, such as "feat:", "fix:", "docs:", "chore:", etc.
-  Following the prefix, there should be a concise description of the change in the PR title.
- If the pr does not follow the naming convention a comment on the PR to edit the PR title to follow the naming convention
**Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No
[JUSTIFICATION]

**Comment by benjagm** [comment]
I am concerned about adding so much processes and rules here that can create friction with new contributors. We just launched the new triage process and before going with something like this I think we need to adopt the new process.

I'd love to hear more opinions before proceeding with a change like this.

**Comment by satyam-x10** [comment]
@benjagm maybe we can do this : add the issue_hash in the PR naming. with the issue hash we can track what the issue is. for example for this same problem we can name this PR : ```Enhancement: PR Naming Convention #338```

**Comment by benjagm** [comment]
We'll prefer to keep the naming totally free for now. Thanks!
