### ISSUE TITLE
Specification and specification-links pages to show the docs sidebar

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#34]
We need the specification and specifications-links pages to show the docs left sidebar and probably other pages in the future. For this issue we need:
- [ ] Make those two pages show the docs sidebar.
- [ ] Prepare docs and code to make it easy to do the same for other existing or new pages.

**Comment by OlliesWorld** [comment]
Any slug.page.tsx page needs 
`import { SectionContext } from '~/context'` and the ` <SectionContext.Provider value={frontmatter.section || null}>` wrapper.
then the `.md` page needs the `section: docs` callout in the frontmatter for which sidebar to display. i.e. docs, learn
