### ISSUE TITLE
Feature: CI(Github Actions) -  Performs linting, formatting, and type-checking 

### ISSUE THREAD

**Issue by aialok** [json-schema-org/website#340]
Feature: CI - Performs linting, formatting, and type-checking

#### Reason/Context
- **Why we need this improvement?**  
  We need to enforce code quality standards consistently across the project to maintain readability, maintainability, and consistency. This ensures that our codebase remains clean and free of errors.

- **How will this change help?**  
  This change will automate the process of checking code quality during the CI (Continuous Integration) pipeline. It will catch potential issues early in the development process, reducing the chances of bugs slipping into production.

- **What is the motivation?**  
  The motivation behind this improvement is to streamline the development workflow and improve overall code quality. By integrating linting, formatting, and type-checking into our CI pipeline, we can enforce coding standards and catch errors before they impact users.

#### Description
- **What changes have to be introduced?**  
  We need to set up tools such as ESLint, Prettier, and TypeScript in our CI pipeline. These tools will be configured to perform linting, code formatting, and type-checking automatically on every code change. Already setup this in my previous issue.

- **Will this be a breaking change?**  
  This change should not be breaking as it focuses on improving the development process rather than introducing new features or altering existing functionality.

- **How could it be implemented/designed?**  
  Implementation involves adding appropriate scripts and configurations to our CI setup. We will configure our CI workflow to run commands for linting, formatting, and type-checking on every pull request or code push. Additionally, we may need to update our documentation to inform contributors about these CI checks and how to resolve any issues that arise.

**Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

Yes/No
[JUSTIFICATION]

**Comment by benjagm** [comment]
How this differ or complement #322 ?

**Comment by Min2who** [comment]
Linting is already there in #296

**Comment by aialok** [comment]
> Linting is already there in #296.
> 
> @benjagm, this issue is a subset of the GSoC project. Should this be tackled now?

@benjagm, @Min2who, I think we need to add at least this feature as soon as possible because we are going to have lots of PRs as `GSoC` is nearing. If we have this CI setup, we can easily track potential bugs.

**Comment by benjagm** [comment]
@aialok lets proceed with this.

**Comment by aialok** [comment]
Please assign this to me.

Thank you @benjagm : )

**Comment by Min2who** [comment]
can i work on it @benjagm

**Comment by Min2who** [comment]
so we should close this #296 pr and the attached issue 

 @benjagm

**Comment by ayushtiwari110** [comment]
Hello @benjagm , I would like to work on this issue. I have some experience working with CI/CD Pipelines on Github Actions. I have worked on a similar CI/CD Pipeline in the past, you can have a look at that here: [CI/CD Pipeline](https://github.com/BacPacNet/web-app-client/commit/d2fbd219736b40e9ebe46e3fc3bb010704ec69ce)

**Comment by nikhilyadav24** [comment]
Hey @benjagm , Please assign this to me.

**Comment by aialok** [comment]
Thank you @nikhilyadav24 @ayushtiwari110 for your interest in this.
For working on this we need to setup prettier and eslint together which is being setup in PR #335 .
Once this PR get merge then only we can work on this.
I am already working on the above PR and setup all the above things.
I am just waiting for the PR to get merge then I will raise PR for this issue.

Till then you people can see other issues or create your own issue.

Happy Coding!

Thank you : )

**Comment by benjagm** [comment]
@ayushtiwari110 still interested on this issue?

**Comment by ayushtiwari110** [comment]
@benjagm Yeah I'm still interested!

**Comment by benjagm** [comment]
@ayushtiwari110 please go ahead.

**Comment by ayushtiwari110** [comment]
Thanks for assigning!

**Comment by ayushtiwari110** [comment]
👋 Hey there! @benjagm I thought to ask a few things...
Will the CI workflow run on every push, or shall we include/exclude some other events as well..? For example, I guess we can exclude the workflow if it is a draft PR...
And under this issue, shall we include any other checks in workflow alongwith linting , formatting and type checks? For example, we can include build check or run the jest tests in the workflow, if needed.

**Comment by aialok** [comment]
Bassically, this CI workflow will run for pull request.

Jobs need to run :

### formatting Linting and typechecking
- Linting : It will cover both formatting and Linting as we have already setup eslint-plugin-prettier.
- Typechecking

### Build
- Setup Build

Till now we have setup these things only.

For testing thing we don't have setup anything in our repo.

Later once we setup for testing we will update the workflow.

@benjagm anything extra ?

**Comment by benjagm** [comment]
What Alok described sounds good to me.

**Comment by ayushtiwari110** [comment]
Sure! Thanks @aialok and @benjagm for confirming. I'll work on the CI workflow accordingly...

**Comment by ayushtiwari110** [comment]
Hey there @benjagm  @aialok ,
I have created a draft PR for this issuse, where I have setuo the initial workflow based on the jobs mentioned in this issue. kindly have a look at it and let me know possible improvements or changes required.
