### ISSUE TITLE
Make sure all the new issues are created with the label "Status: Triage"

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#341]
#### Reason/Context
it will be great to make sure all the new issues are created with the label "Status: Triage". This can improve collaboration and help with the adoption of the new triage process. Ideally we'll use Github actions.

For reference:
https://docs.github.com/en/actions/managing-issues-and-pull-requests/adding-labels-to-issues

**Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No

**Comment by gregsdennis** [comment]
Issue templates are also a great way of handling this.

---

If you're set on using Actions, there's GitHub's issue labeler

Example usage:

https://github.com/gregsdennis/json-everything/blob/master/.github%2Fworkflows%2Fissue-labeler.yml

I have a config in the .github folder.

**Comment by Min2who** [comment]
> Issue templates are also a great way of handling this.
> 
> If you're set on using Actions, there's GitHub's issue labeler
> 
> Example usage:
> 
> https://github.com/gregsdennis/json-everything/blob/master/.github%2Fworkflows%2Fissue-labeler.yml
> 
> I have a config in the .github folder.

Thanks @gregsdennis 

But the provided solution seems to work

**Comment by gregsdennis** [comment]
> But the provided solution seems to work

That's fine, but it's better that the maintainers agree on an approach than to just have something that works.

**Comment by Min2who** [comment]
> @Min2who are you ok with changing the implementation to use Greg's approach?

Done @gregsdennis

**Comment by DhairyaMajmudar** [comment]
Also, @benjagm one thing that can be done is to divide issue triaging work, since several new issues have been created in the last few days, and quickly triaging all of them can be made easy if that work is distributed with several other community members also.

Would like to get your views on this : )

**Comment by gregsdennis** [comment]
I think the maintainers need to keep the responsibility of triaging issues since we are governing the direction of the project as a whole.

**Comment by princerajpoot20** [comment]
@benjagm I would like to work on this
