### ISSUE TITLE
Search button is not as expected in responsive mode.

### ISSUE THREAD

**Issue by DhairyaMajmudar** [json-schema-org/website#345]
#### Describe the bug

In the tablet and mobile view, the search button is not as expected which needed to be corrected.

#### How to Reproduce

1. Open the JSON Schema website 
2. Use developer tools access the tablet and mobile view 

**Screenshots**

- Tablet
![Screenshot from 2024-02-23 23-47-31](https://github.com/json-schema-org/website/assets/124715224/cad447bb-bffa-4a7b-af49-55d81d711528)

- Mobile 
![Screenshot from 2024-02-23 23-47-18](https://github.com/json-schema-org/website/assets/124715224/7438da6a-c8dd-41f7-b93f-d68225483827)

#### Expected behavior

The search button must be the same as in the desktop view.

**Comment by DhairyaMajmudar** [comment]
@benjagm pls. have a look on this bug.

**Comment by benjagm** [comment]
@DhairyaMajmudar Please see [this comment](https://github.com/json-schema-org/website/issues/355#issuecomment-1964722093) in #355 355

**Comment by officeneerajsaini** [comment]
Hey @DhairyaMajmudar , maybe we need to change the text on this button. Instead of displaying 'Search,' we can display 'Quick Search (Ctrl + K)' to inform the user that they can use this key combination for quick search.

![Screenshot from 2024-03-12 10-20-31](https://github.com/json-schema-org/website/assets/118799941/71d644b1-0c29-48c4-9b4e-de6bb6732b4b)

**Comment by DhairyaMajmudar** [comment]
Good idea Neeraj, but by adding more text in search bar will increase its width as you can see in the image above.

**Comment by officeneerajsaini** [comment]
Yes Dhairya

**Comment by benjagm** [comment]
The idea is to convert the search button in a single lens icon button like AsyncAPI does. https://www.asyncapi.com/en

This is in progress as part of #130
