### ISSUE TITLE
It would be great to use github actions to notify first time contributors

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#346]
#### Reason/Context
We'd love to improve the experience for first time contributors and to do it so we'd love to thank contributors opening and issue or PR for the first time.

Some examples:

- [Notify first issue](https://github.com/asyncapi/spec/blob/master/.github/workflows/welcome-first-time-contrib.yml)
- [First issue and first PR](https://dev.to/hidaytrahman/greet-to-the-new-pr-and-issue-creator-in-github-action-1-k89)

**Comment by JeelRajodiya** [comment]
Please assign this to me

**Comment by benjagm** [comment]
Go ahead @JeelRajodiya !
