### ISSUE TITLE
[📑 Docs]: It will be great to create a Markdown style guide with the custom annotations we have

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#352]
### What Docs changes are you proposing?

I'd like to propose creating a md style guide documenting all the custom tags we have working in our website so the people can create better docs and we avoid creating unnecessary new tags. This improve discoverability and contributors experience.

- Example : https://github.com/couchbaselabs/docs-style-guide/blob/master/md-style-guide.md
- All the custom tags could be identified in this file: components/StyledMarkdown.tsx 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DhairyaMajmudar** [comment]
@benjagm shall I take this up

**Comment by benjagm** [comment]
For reference #314

**Comment by benjagm** [comment]
please go ahead @DhairyaMajmudar. Thanks!

**Comment by DhairyaMajmudar** [comment]
> @DhairyaMajmudar if you need any help regarding reference #314 feel free to ask.

Thanks if any help needed, I will surely ask : )
