### ISSUE TITLE
[📑 Docs]: Typo in pages/draft/2020-12/release-notes.md

### ISSUE THREAD

**Issue by kalivtrope** [json-schema-org/website#360]
### What Docs changes are you proposing?

In the section `Embedded Schemas and Bundling` of [2020-12 release notes](../blob/master/pages/draft/2020-12/release-notes.md#embedded-schemas-and-bundling), there's a few properties whose `"type"` has a string value associated which hovewer describes a reference.
This causes the described snippets to become invalid JSON schemas. 

I believe the docs should change occurrences of those invalid type validations to references, e.g. should be changed from
```json
"postalCode": { "type": "/schema/common#/$defs/usaPostalCode" },
```
to
```json
"postalCode": { "$ref": "/schema/common#/$defs/usaPostalCode" },
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Thanks for posting this.  We should also check for other similar typos.  (There's one for `state` in the next line.)
