### ISSUE TITLE
Extra Width on the pages

### ISSUE THREAD

**Issue by Saumya40-codes** [json-schema-org/website#363]
#### Describe the bug

There appears to be extra width on the pages which is causing horizontal ruler to appear
#### Current behavior

https://github.com/json-schema-org/website/assets/115284013/edaca748-d807-4db8-a733-94e3cefcd31f

#### Expected behavior

https://github.com/json-schema-org/website/assets/115284013/3fb2868b-d8a0-4f5e-94db-293ae19d6208

If you are ok with this, then I will like to fix this bug.
Thanks!

**Comment by benjagm** [comment]
This is being worked in the PR #359

**Comment by benjagm** [comment]
Thanks for finding this! Available to send a PR with a fix?

**Comment by Saumya40-codes** [comment]
Hey @benjagm 
Yeah I will send the PR as soon as I fix it

**Comment by jayprakash25** [comment]
Hey @benjagm , Can I work on this issue?
