### ISSUE TITLE
Extra space after the footer 

### ISSUE THREAD

**Issue by JeelRajodiya** [json-schema-org/website#364]
#### Describe the bug

if you go to the docs or specifications pages, there is some extra spaces after the footer. 
I am not sure if this is intentional or not. 
![image](https://github.com/json-schema-org/website/assets/63534268/fecb8f83-de57-4577-9c69-8de2445a0bce)

#### Expected behavior
The footer should look like this 
![image](https://github.com/json-schema-org/website/assets/63534268/5966b893-406a-4fbb-ab25-ea7ec0437eaa)

**Comment by benjagm** [comment]
Let's do it. Thanks @JeelRajodiya. Issue accepted.

**Comment by JeelRajodiya** [comment]
Hey @benjagm, I am closing this issue in favor of #375 which is same as this issue, and already have a PR ready to review

**Comment by officeneerajsaini** [comment]
> Hey @benjagm, I am closing this issue in favor of #375 which is same as this issue, and already have a PR ready to review

You also does a great job in this contribution , I appricate  your work @JeelRajodiya
