### ISSUE TITLE
[Bug]: under the Supported by section  comman room and slack not have same icon and text size

### ISSUE THREAD

**Issue by officeneerajsaini** [json-schema-org/website#366]
#### Describe the bug
under the Supported by section  comman room and slack not have same icon and text size , we need to fix this by give same size

#### How to Reproduce

![Screenshot from 2024-02-26 21-37-52](https://github.com/json-schema-org/website/assets/118799941/96841edd-e8b7-4995-847f-bceff6132e1d)

![Screenshot from 2024-02-26 21-49-25](https://github.com/json-schema-org/website/assets/118799941/ea84cb6a-47f0-42d7-9f4f-2c1fb5a2741b)

#### Expected behavior
both have same size

**Comment by benjagm** [comment]
@officeneerajsaini Thanks! i have assigned you the issue. Please open the PR with you proposed solution. 

Thanks!!

**Comment by officeneerajsaini** [comment]
Thank you ❤️ , @benjagm , for assigning this issue to me. I am excited to work on this task as it marks my first contribution. I anticipate creating more issues and merging pull requests in the future. Additionally, I am thrilled to share that I have chosen to participate in GSoC 2024, and I have been selected for my preferred organization, JSON Schema.

**Comment by officeneerajsaini** [comment]
this issues status  showing in progress , @benjagm   you need to close this as completed
