### ISSUE TITLE
Code formatting issue in the release notes of Draft 2020-12 

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#371]
#### Describe the bug
When accessing to the release notes of Draft 2020-12:
https://json-schema.org/draft/2020-12/release-notes

There is a problem with missing formatting of the json code of the section "$dynamicRef and $dynamicAnchor": 
https://json-schema.org/draft/2020-12/release-notes#dollardynamicref-and-dollardynamicanchor

![Screenshot 2024-02-27 at 00 47 02](https://github.com/json-schema-org/website/assets/40007659/4f5c6979-8a6e-472c-bc3b-a0836cb8e6d7)

#### How to Reproduce
Access the url: https://json-schema.org/draft/2020-12/release-notes#dollardynamicref-and-dollardynamicanchor

#### Expected behavior
Formatted code like other sections: 
![Screenshot 2024-02-27 at 00 49 53](https://github.com/json-schema-org/website/assets/40007659/88b39219-9b59-4bba-b6f5-467aebbdc4e1)

**Comment by Akshaybagai52** [comment]
Hey @benjagm can I work on this issue

**Comment by DhairyaMajmudar** [comment]
@benjagm Shall I take this up ?

**Comment by gregsdennis** [comment]
I think this is due to the comments (which need to stay).  Try a `jsonc` format.

**Comment by Adity20** [comment]
@benjagm Can I work on this issue??

**Comment by jayprakash25** [comment]
Hi @benjagm , I've submitted PR #379  addressing this issue. Could you please review it at your convenience? Thank you!

**Comment by Adity20** [comment]
Hi @benjagm, I am done with the work alloted to me for this issue. Kindly review the PR #381 addressing the issue #371

**Comment by benjagm** [comment]
Tested jsonc and seems to work. Please Adity20. Add the changes.
<img width="729" alt="Screenshot 2024-03-02 at 14 44 15" src="https://github.com/json-schema-org/website/assets/40007659/c25edf36-b23c-4355-8bae-098c8743d87a">

**Comment by Adity20** [comment]
Is this how the changes should be introduced using 



![Image](https://github.com/json-schema-org/website/assets/119804372/c2ca7cd8-2793-466c-8b2e-5656320f40c4)

**Comment by Adity20** [comment]
Done @benjagm .
