### ISSUE TITLE
box shadow when the hamburger menu in mobile design is open

### ISSUE THREAD

**Issue by Akshaybagai52** [json-schema-org/website#374]
#### Reason/Context

We need this improvement for better user experience 

#### Description

go to this url :-https://json-schema.org/ and turn on mobile responsive 
then you can see there is drop shadow on navbar when it is not open so it is looking good
![Screenshot 2024-02-27 at 10 02 40 AM](https://github.com/json-schema-org/website/assets/100753870/1af97bab-6565-4f2d-aa7d-2eda8dc5a794)

but when the navbar is open on clicking of hamburger menu then the box shadow removed and it is merging with the white background of the content as can be seen in the screenshot
![Screenshot 2024-02-27 at 10 04 06 AM](https://github.com/json-schema-org/website/assets/100753870/c93ed407-993f-4cb3-a403-d72be186a8de)

so there is no separation between navbar and content.

**Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

Yes/No
[JUSTIFICATION]

I would love to work on this issue

**Comment by DhairyaMajmudar** [comment]
@benjagm shall I incorporate this small change in my existing PR #359 

**Screenshot after changes**

![image](https://github.com/json-schema-org/website/assets/124715224/2cfd4960-eae2-4871-897b-8f37667c1029)

**Comment by benjagm** [comment]
thanks @DhairyaMajmudar ! Issue accepted.
