### ISSUE TITLE
[Bug]: The Footer Section requires some design enhancements for a more polished appearance.

### ISSUE THREAD

**Issue by officeneerajsaini** [json-schema-org/website#375]
#### Describe the bug
The footer section requires some design enhancements, including alignment issues and excess space below the footer.

####Issue No. #376 

#### How to Reproduce
![Screenshot from 2024-02-27 10-55-54](https://github.com/json-schema-org/website/assets/118799941/05dadcee-daef-42fe-80e0-3224f2a54989)

#### Expected behavior
![Screenshot from 2024-02-27 10-56-10](https://github.com/json-schema-org/website/assets/118799941/645f589d-2d7e-47a8-9f70-896b4bfa8266)

**Comment by JeelRajodiya** [comment]
Please check issue #364

**Comment by officeneerajsaini** [comment]
> Please check issue #364

Yes, I checked that issue before opening it. I have provided a good design for the footer section. You can review my design and code, and if you have any suggestions to improve it further, please let me know

**Comment by benjagm** [comment]
Thanks for opening this @officeneerajsaini . Honestly I can identify the difference. Can you please enumerate the changes you'd like to introduce so I can check with your design proposal?

**Comment by officeneerajsaini** [comment]
The social icon div in the footer section had some extra white spaces, which I initially removed using spaces. Additionally, I modified the footer background color style with the following CSS class:

```css
.clip-top {
  clip-path: polygon(0 15%, 0 100%, 0% 100%, 100% 100%, 100% 0);
}
```

This class flattens the footer bottom, and I also applied a regular style with some angle at the top. You can observe this style on elements such as "Start learning JSON Schema" and "Start contributing to JSON Schema." My design now effectively fills all available space.

Furthermore, I ensured vertical center alignment within the footer by using the appropriate properties on the inner div. I also resolved issues by removing the `w-screen` code, eliminating any unnecessary extra width. Additionally, I addressed concerns from the previous pull request.

**Comment by benjagm** [comment]
Ok. Thanks. Let's do it.

**Comment by officeneerajsaini** [comment]
I have made changes to the footer section. Is there anything else I can improve in it?

**Comment by officeneerajsaini** [comment]
I believe that in our GitHub repository, we should add Vercel so that we can visualize the changes I made in my code. This way, maintainers can easily verify the contributions made by contributors. It will save both of us time.

**Comment by officeneerajsaini** [comment]
> Ok. Thanks. Let's do it.

i already done my work before it assign to me
