### ISSUE TITLE
Feat: Dockerising the codebase.

### ISSUE THREAD

**Issue by DhairyaMajmudar** [json-schema-org/website#378]
#### Reason/Context

Dokerising the codebase will help contributors to setup the codebase easily , saving their time and machine resources 

#### Description

What changes have to be 

Adding docker setup to the codebase.

Tasks to be done 

- [ ] Adding docker setup by their native commands 
- [ ] Creating make commands
- [ ]  Updating the installation readme file 

**Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No

**Comment by benjagm** [comment]
Thanks @DhairyaMajmudar. Please go ahead!

**Comment by gregsdennis** [comment]
@DhairyaMajmudar I don't think that this adds anything immediately valuable, and given that we have a lot of activity right now, I wonder if this will just get in the way.  Maybe we can hold off on this until things calm down a bit?

**Comment by DarhkVoyd** [comment]
I agree! I believe dockerisation is mostly effective for larger and more complex codebases requiring to run long & multiple instructions to spin up the local development. It's an overkill for a simple Next.js project with submodules.

**Comment by DhairyaMajmudar** [comment]
> I agree! I believe dockerisation is mostly effective for larger and more complex codebases requiring to run long & multiple instructions to spin up `local instances of a program`. It's an overkill to set it up as a `development solution` for a simple Next.js project with submodules.
> 
> Most importantly, this doesn't do any `simplification` and even makes the setup more complex. We'll definitely need bind mounts and probably something else too. So, we'll basically switch from simpler commands setup to longer docker commands and eventually `docker compose`.

The commands will be not that much longer since I will also add makefile file shorten long docker commands.

As of it requires around 5 to 6 commands for setting up whole codebase but after using the make commands docker setup it will be reduced to only two commands which are:
1. `make install` to  install dependencies and git sub modules
2. `make run` to run the website for preview in browser.

**Comment by DarhkVoyd** [comment]
Please go ahead. I simply don't understand why are we even considering this. We neither need this abstraction nor the trade off that comes with it.

**Comment by gregsdennis** [comment]
We had a conversation in slack, and it was determined that adding docker setup isn't going to hinder running it without docker, so... sure, I guess.

**Comment by Mickyverma24** [comment]
> I agree! I believe dockerisation is mostly effective for larger and more complex codebases requiring to run long & multiple instructions to spin up `local instances of a program`. It's an overkill to set it up as a `development solution` for a simple Next.js project with submodules.
> 
> Most importantly, this doesn't do any `simplification` and even makes the setup more complex. We'll definitely need bind mounts and probably something else too. So, we'll basically switch from simpler commands setup to longer docker commands and eventually `docker compose`.

fully agreed.......
