### ISSUE TITLE
Feat: Update issue template for repo.

### ISSUE THREAD

**Issue by DhairyaMajmudar** [json-schema-org/website#392]
#### Reason/Context

Currently the issue template in the repo is very basic ask 
Very less information related to issue. It will be a good feature if new issue template asking screenshots , links and steps to reproduce the issue is implemented.

#### Description

For improving the issue template ita existing .yml files need to be updated and after implementing the new issue template it might look 
 like below attached screenshot.

**Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

Yes/No
[JUSTIFICATION]

**Comment by DhairyaMajmudar** [comment]
Referenced screenshot

![IMG_20240229_124457](https://github.com/json-schema-org/website/assets/124715224/ae5c06aa-3548-408b-a665-0f05b1ba9fad)


@benjagm @gregsdennis pls. give your views on this enhancement.

**Comment by gregsdennis** [comment]
Please hold development until assigned.

**Comment by DhairyaMajmudar** [comment]
> I'm happy with this, but I expect we'll also need other templates, e.g. for ideas (like this one).

True would be happy to know more about this .

**Comment by officeneerajsaini** [comment]
yeah , that's a great idea @DhairyaMajmudar

**Comment by benjagm** [comment]
Sound good. Let's make sure we add at least one template more for ideas.

**Comment by DhairyaMajmudar** [comment]
> yeah , that's a great idea @DhairyaMajmudar

Sure and thanks for assignment : )
