### ISSUE TITLE
Bug: Overflow in blogs page.

### ISSUE THREAD

**Issue by DhairyaMajmudar** [json-schema-org/website#393]
#### Describe the bug

There's an overflow seen in the blogs page of the website, this overflow needs to be removed since it hinders user experience.

#### How to Reproduce

1. Visit the website in production.
2. Navigate to blogs page.

![image](https://github.com/json-schema-org/website/assets/124715224/27d24b35-dd5f-479c-8465-0b05949b57ba)

#### Expected behavior 
There must be no overflow in the website

**Comment by DhairyaMajmudar** [comment]
@benjagm pls. have a look in this bug.

**Comment by JeelRajodiya** [comment]
Can you highlight the part where there is overflow ?

**Comment by DhairyaMajmudar** [comment]
> Can you highlight the part where there is overflow ?

overflow is in the body and footer

**Comment by DhairyaMajmudar** [comment]
nope those are the margins , from overflow I mean when you try to scroll  the website in x direction it can shift.

**Comment by benjagm** [comment]
Good finding @DhairyaMajmudar . Can we leave this issue to someone new and you act as PR reviewer?

**Comment by DhairyaMajmudar** [comment]
Yes pls. this can help new contributors.

**Comment by Adity20** [comment]
Can you assign this to me please @benjagm

**Comment by benjagm** [comment]
Go ahead @Adity20 !

**Comment by Adity20** [comment]
@benjagm @DhairyaMajmudar I created a PR related to this issue kindly review it #418
