### ISSUE TITLE
Bug : Update route from /implementations to /tools

### ISSUE THREAD

**Issue by aialok** [json-schema-org/website#394]
#### Describe the bug
- Basically we have updated our implementation page to tools but we have not updated the corresponding route.
#### How to Reproduce
- Go to json-schema-website
- Navigate to tools section and see the URL

![Screenshot from 2024-02-29 23-33-39](https://github.com/json-schema-org/website/assets/66772290/b2bba38b-43c5-4f22-b319-14d403adaf9d)

#### Expected behavior

- URL should be updated to https://json-schema.org/tools

**Comment by DhairyaMajmudar** [comment]
Good find @aialok : D

**Comment by officeneerajsaini** [comment]
Yeah, that's great, @aialok . We need to change the route from 'implementation' to 'tools' and also create a redirection route so we can redirect '/implementation' to '/tools.

**Comment by aialok** [comment]
> Yeah, that's great, @aialok . We need to change the route from 'implementation' to 'tools' and also create a redirection route so we can redirect '/implementation' to '/tools.

Yupp @officeneerajsaini , we are also facing page not found error in mobile phone. Because of this only.

**Comment by officeneerajsaini** [comment]
It  issue not only occur in mobile it also occur in any other devices because we try to  get request  from a route that not exits so , we need to make changes in route and also need to make a redirect link so if someone try to get request  on "/implementations" route it will redirect to "/tools"
@aialok

**Comment by benjagm** [comment]
The implementations url is probably being used from hundreds of sites se we can't just remove the link. The ideal solution is rename this page to tools but also create a redirect in cloudflare to make sure all call to implementations end up in tools.

**Comment by aialok** [comment]
> The implementations url is probably being used from hundreds of sites se we can't just remove the link. The ideal solution is rename this page to tools but also create a redirect in cloudflare to make sure all call to implementations end up in tools.

@benjagm, yes, this is the good to go but cloudflare work will be done by you only. 
Additionally, I noticed a few typos on the "Tools" page.  I think Instead of "implementation," we need to use "tools" everywhere.


![Screenshot from 2024-03-01 15-19-03](https://github.com/json-schema-org/website/assets/66772290/e35568f0-c105-4390-bc0e-c91259efef94)
![Screenshot from 2024-03-01 15-18-32](https://github.com/json-schema-org/website/assets/66772290/b2918198-712e-40c9-8854-0a30e46d41ec)

**Comment by AdityaSingh-02** [comment]
> The implementations url is probably being used from hundreds of sites se we can't just remove the link. The ideal solution is rename this page to tools but also create a redirect in cloudflare to make sure all call to implementations end up in tools.


@benjagm, Yes I completely agree with you, changing the route is not an Ideal Solution since many sites/clients must be using /implementation URLs, the possible solution is fix the page content and change it from tooling to implementations

@benjagm I was Wondering if I could work on this issue.🚀

**Comment by divyaxdv** [comment]
> @benjagm, Yes I completely agree with you, changing the route is not an Ideal Solution since many sites/clients must be using /implementations URLs, the possible solution is fix the page content and change it from tooling to implementations
> 
> And I am not sure but implementations page needed a redesign to improve UX #160
> 
> @benjagm I was Wondering if I could work on this issue.🚀

@AdityaSingh-02 ,changing the content of the page from tool to implementation is not viable i guess, I dont think that is how this should be proceeded as the implementation page has been updated to Tools knowingly.
The solution suggested by @benjagm is the most ideal but cloudfare work can be done by him only.

**Comment by benjagm** [comment]
@AdityaSingh-02 @divyaxdv . We will need to review the in the whole site the usage of implementations to adopt the new term tools and we all of that is done, well proceed with:

- Rename the page from implementations to /tools
- Creating a redirect from /implementations to /tools

**Comment by officeneerajsaini** [comment]
> It issue not only occur in mobile it also occur in any other devices because we try to get request from a route that not exits so , we need to make changes in route and also need to make a redirect link so if someone try to get request on "/implementations" route it will redirect to "/tools" @aialok

@benjagm Yeah, I already mentioned that. However, we need to carefully change the route. We need to check every link to ensure they work properly because there are a lot of links.

**Comment by Danimoz** [comment]
Can I work on this?

**Comment by benjagm** [comment]
Completed.
