### ISSUE TITLE
Bug : 404 Error on Mobile Tools Button Navigation

### ISSUE THREAD

**Issue by kx412764776** [json-schema-org/website#396]
#### Describe the bug

- When the page is scaled down to mobile size, clicking the tools button under the menu will display 404 Not found.

#### How to Reproduce

- Change the redirect URL of the tools button under the menu. / Update URL of Tools page to <a>https://json-schema.org/tools</a>.

![json-schema-bug](https://github.com/json-schema-org/website/assets/117196993/39421fa1-efea-4bb1-8bc0-f999f21a4e7a)

#### Expected behavior
- The tools button on the mobile web page navigates and displays the correct content

**Comment by officeneerajsaini** [comment]
@kx412764776  Are you referring to the 'Tools' button on the navbar?

**Comment by JeelRajodiya** [comment]
### Chaning the uri from "/tools" to "/implementations" will fix this ( in Layout.tsx line 198 )
![image](https://github.com/json-schema-org/website/assets/63534268/2647f375-eb9c-4675-a960-b4e4b2d92dae)

**Comment by benjagm** [comment]
Good finding. This bug was because of me! Available to fix it? @kx412764776

**Comment by kx412764776** [comment]
@benjagm Sure, Can you assign this task to me?

**Comment by abhishek-403** [comment]
created a pr for this issue please have a look. @benjagm

**Comment by benjagm** [comment]
Completed!
