### ISSUE TITLE
Top menu - Community link navigation is sub-optimal

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#402]
#### Describe the bug
When in the landing page, if I click in community that is a section in the same page, the content location is suboptimal when we expect the title of the community section appearing on top. See image.

Current:
<img width="1510" alt="Screenshot 2024-03-01 at 13 46 57" src="https://github.com/json-schema-org/website/assets/40007659/0565e89c-9f20-4158-a254-66a4fd7ae198">

Desired:
<img width="1512" alt="Screenshot 2024-03-01 at 13 50 29" src="https://github.com/json-schema-org/website/assets/40007659/32154a87-da81-4d92-9d6f-c3b2bf3e831b">

**Comment by TamannaVerma99** [comment]
Hey @benjagm!
Can I work on this issue?7

**Comment by benjagm** [comment]
Of course @TamannaVerma99 !! Thanks. All yours!
