### ISSUE TITLE
Gap between mobile navbar and main navbar on tools/blog page

### ISSUE THREAD

**Issue by kx412764776** [json-schema-org/website#407]
#### Describe the bug
There is a gap between the mobile navbar and the main navbar on the tools, blog and posted blog pages.

#### How to Reproduce

![image](https://github.com/json-schema-org/website/assets/117196993/f8e8b984-d14c-4ebe-8272-ae1ac58d8455)
![image](https://github.com/json-schema-org/website/assets/117196993/8482a476-7bef-4241-9170-e5c9ce2280f8)
![image](https://github.com/json-schema-org/website/assets/117196993/c7500f00-85fb-4a23-a05b-1bd69de26c6a)

#### Expected behavior
Show mobile navbar under tools and blog pages properly

**Comment by Maykkkk** [comment]
@benjagm I would love to work on this issue. Please assigned it to me.  
Thank you

**Comment by TamannaVerma99** [comment]
@benjagm can you please assign this issue to me?

**Comment by officeneerajsaini** [comment]
@kx412764776 i think this issue no longer exits

**Comment by kx412764776** [comment]
@officeneerajsaini Great, this issue will close when your pr #410 passes and fixes it

**Comment by officeneerajsaini** [comment]
@kx412764776, no, I didn't address that issue. As you mentioned, my pull request is still open and not merged into the code. Maybe @DhairyaMajmudar has resolved that issue.

**Comment by DhairyaMajmudar** [comment]
Hi @officeneerajsaini , I haven't addressed any such issue in my recent PRs .

**Comment by officeneerajsaini** [comment]
Okay @DhairyaMajmudar, it seems someone else may have resolved this issue.

**Comment by benjagm** [comment]
I can't reproduce this issue.

**Comment by officeneerajsaini** [comment]
@benjagm because this issue no longer exits

**Comment by benjagm** [comment]
Thanks everyone. I'll close it.
