### ISSUE TITLE
Feat: Configuring Dependabot Version Updates

### ISSUE THREAD

**Issue by DhairyaMajmudar** [json-schema-org/website#408]
#### Reason/Context

Several packages updates to newer version to keep a watch on them dependabot is configured which opens a pull request for version updates. THe frequency of pull request can be configured 

#### Description

Adding dependabot will help the repository to update its packages and avoids breaking the application due to outdated packages.

[Dependabot Reference](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates)

**Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No
[JUSTIFICATION]

**Comment by DhairyaMajmudar** [comment]
@benjagm @gregsdennis configuring dependabot can be beneficial for the repository. Pls. give your inputs on this : )

**Comment by benjagm** [comment]
Thanks for the proposal Dharya. I agree it will be beneficial. I think we'll implement this as part of the GSoC Project for not adding more complex feature now with such a high number of active contributors.

**Comment by DhairyaMajmudar** [comment]
> Thanks for the proposal Dharya. I agree it will be beneficial. I think we'll implement this as part of the GSoC Project for not adding more complex feature now with such a high number of active contributors.
> 
> So issue is accepted but to work on it in some weeks.

Yes, you are correct this is not the correct time to implement this proposal.

**Comment by benjagm** [comment]
Let's setup this live in our next 1:1 @aialok

**Comment by benjagm** [comment]
Closed as completed. We have dependabot running.
