### ISSUE TITLE
[Bug]: Some sections need alignment

### ISSUE THREAD

**Issue by officeneerajsaini** [json-schema-org/website#409]
#### Describe the bug
Some sections have a top margin to align items in the center. However, this might not be the best way to achieve center alignment. I noticed that the items are not yet centered, possibly because they use a top margin for alignment. I am going to fix that section

#### How to Reproduce
go to [This link](https://json-schema.org/)
1 Scroll to "Start learning JSON Schema" Section
2 Scroll to "Start contributing to JSON Schema" Section 

![1](https://github.com/json-schema-org/website/assets/118799941/9bb6314f-6122-410a-a797-1a8b7ff374e8)

![2](https://github.com/json-schema-org/website/assets/118799941/91414a2b-8893-4f42-a844-6bafe706e939)

![3](https://github.com/json-schema-org/website/assets/118799941/033127e5-a695-41b8-846b-650494a417f6)

![4](https://github.com/json-schema-org/website/assets/118799941/81027025-a55a-4778-8bc2-9f0fd6cfdbc7)
 

#### Expected behavior

![1](https://github.com/json-schema-org/website/assets/118799941/a964458f-d7aa-4075-8b29-fcda583da876)

![2](https://github.com/json-schema-org/website/assets/118799941/532900e2-43ba-4aa5-9b75-6da313101bef)

**Comment by benjagm** [comment]
Thanks for catching this! 
Issue accepted.

**Comment by benjagm** [comment]
@officeneerajsaini

**Comment by benjagm** [comment]
Are you working on it officeneerajsaini ? I just assigned it assuming it.

**Comment by officeneerajsaini** [comment]
@benjagm  i already done my work you can seen my open PR

**Comment by officeneerajsaini** [comment]
Sorry i make my pull request before it assign to me @benjagm

**Comment by benjagm** [comment]
All good. Thanks @officeneerajsaini
