### ISSUE TITLE
Feature to greet users when they merge their first PR

### ISSUE THREAD

**Issue by Maykkkk** [json-schema-org/website#411]
**Summary**- I would like to implement a feature that automatically greets new users when they open their first pull request or issue in our repository. This will help us foster a welcoming and supportive community environment.

Expected Behavior -
Upon opening their first pull request or issue, a new user should receive a friendly greeting message automatically.

Additional Information -
Use Case: This feature will enhance the onboarding experience for new contributors and reinforce a positive community atmosphere.
Impact: We anticipate that this feature will help increase user engagement and foster a sense of belonging within our community.

Expected outcomes after the implementation:

Example 1
```
🎉 Welcome, [@username](link_to_user_profile)! 🎉

Thank you for opening your first pull request! We're excited to see your contribution. If you have any questions or need assistance, feel free to ask. Happy coding! 😊
```

Example 2
```
🚀 Hey there, [@username](link_to_user_profile)!

Congratulations on making your first pull request! Your initiative is appreciated. Don't hesitate to explore more areas of the project, and remember, every contribution counts! 💪
```

**Comment by benjagm** [comment]
We already have an issue for thanks users when they open an new PR or create an Issue #353 . In this case the challenge is create a github action to congratulate a user when its first PR is merged. We need to check first if this is possible.

**Comment by princerajpoot20** [comment]
> In this case the challenge is create a github action to congratulate a user when its first PR is merged. We need to check first if this is possible.

@benjagm We can create this action, which will be triggered when a PR is merged. It will then check the contributor's PR count. If the `count==1`, then it will greet the user.

**Comment by benjagm** [comment]
> @benjagm We can create this action, which will be triggered when a PR is merged. It will then check the contributor's PR count. If the `count==1`, then it will greet the user.

Sounds like the right thing to do!! Yes!

**Comment by princerajpoot20** [comment]
@Maykkkk Would you like to work on this, or should I do it?

**Comment by Maykkkk** [comment]
Hey @princerajpoot20, This issue already in WIP.
Thanks for asking.

**Comment by princerajpoot20** [comment]
> Hey @princerajpoot20, This issue already in WIP.

Ok, ping me if you need any help. 🙂
