### ISSUE TITLE
[Bug]: Unnecessary top padding in button  

### ISSUE THREAD

**Issue by officeneerajsaini** [json-schema-org/website#414]
### Describe the bug

Unnecessary top padding in button  , so text not able to align perfectly

### Steps To Reproduce

1.  Go to [home page](https://json-schema.org/)
2.  click to [Community page](https://json-schema.org/#community)
3.you can see [Read more](https://json-schema.org/blog/posts/understanding-lexical-dynamic-scopes) or "[View Calendar](https://calendar.google.com/calendar/u/0/embed?src=c_8r4g9r3etmrmt83fm2gljbatos@group.calendar.google.com)"

### Expected Behavior

remove top margin

### Screenshots

![Screenshot from 2024-03-02 20-57-58](https://github.com/json-schema-org/website/assets/118799941/f9391c3a-1d5b-4308-875d-dc66d5f43d30)

![Screenshot from 2024-03-02 20-57-43](https://github.com/json-schema-org/website/assets/118799941/1ca1a299-c122-44fd-990e-96899c57a773)

### Device Information [optional]

```markdown
- OS:Linux Ubuntu 22.04.4 LTS
- Browser: Google Chrome
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by Ali7040** [comment]
@benjagm Please assign it to me. I want to work on it.

**Comment by Adity20** [comment]
@benjagm Can I work on this one?

**Comment by benjagm** [comment]
@Ali7040 please go ahead with this issue.
