### ISSUE TITLE
[📑 Docs]: Lets create a welcome page for the docs section

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#421]
### What Docs changes are you proposing?

Inspired by the good work of AsyncAPI Team, we think it would be great to create a welcome page to our docs section with a welcome message and a card for each subsection of our docs:

- Overview
- Getting started
- Reference
- Specification

This will also required add a new section on top of the sidebar called Welcome. We'll need to make this totally consisten with the style of our website.

[See images for inspiration](https://www.asyncapi.com/docs):
![Screenshot 2024-03-03 at 15 16 34](https://github.com/json-schema-org/website/assets/40007659/2e264042-ecf0-4655-9bd6-2269d9a30e43)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TamannaVerma99** [comment]
Hey @benjagm !
Is this issue available for taking up?
If yes, I would love to contribute towards it :)

**Comment by benjagm** [comment]
Yes. This is available. Please go ahead.

**Comment by benjagm** [comment]
The screenshot is just for inspiration. Please use styles according to our website and branding.

**Comment by officeneerajsaini** [comment]
I am also excited to work on this issue. Maybe I know you assigned it to someone, but can I work on this too? @benjagm

**Comment by benjagm** [comment]
@officeneerajsaini are you open to work on #280 ? It is similar to this one.

**Comment by TamannaVerma99** [comment]
> The screenshot is just for inspiration. Please use styles according to our website and branding.
Sure! I will take care of that.

**Comment by officeneerajsaini** [comment]
> @officeneerajsaini are you open to work on #280 ? It is similar to this one.

Okay ,

**Comment by benjagm** [comment]
Can you please change the target branch to https://github.com/json-schema-org/website/tree/web-release-3?

Reference docs: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by benjagm** [comment]
@TamannaVerma99 are you still working on this?

**Comment by benjagm** [comment]
@TamannaVerma99 please proceed with the integration if the component Card available in the parent branch. If you need to modify the component let's discuss first because others are integrating it.

**Comment by benjagm** [comment]
This is now in the release 3 branch pending to be merged into main.
