### ISSUE TITLE
✨ Enhancement: Create the use cases page

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#426]
### Is your feature request related to a problem? Please describe

This is a new feature.

### Describe the solution you'd like

As per the documentation strategy #strategy, we'd like to publish a use cases page. This page will be totally data driven, reading the information from a json file in the data folder.

I am thinking in a page similar to this one: https://nuclia.com/ai-search-use-cases/

![Screenshot 2024-03-03 at 16 21 37](https://github.com/json-schema-org/website/assets/40007659/e76cea15-1d79-40da-8143-a23592a33cfa)

There will be a title and welcome message and later cards with the details of the use case.

The json storing the use cases will be based on:
* Short title
* Description supporting markdown

Please build the page with face use cases and as soon as the feature is ready I'll add the use cases.
Please build the page as per the branding and style of our page.

Similar issues: #421 #280 

### Are you working on this?

No

**Comment by DhairyaMajmudar** [comment]
@benjagm I would like to work on this feature.

**Comment by VivekJaiswal18** [comment]
Hey @benjagm  I would want to work on this issue!

**Comment by benjagm** [comment]
@VivekJaiswal18 please go ahead. Dhairya, please join me as reviewer of this PR.

**Comment by DhairyaMajmudar** [comment]
> @VivekJaiswal18 please go ahead. Dhairya, please join me as reviewer of this PR.

Sure would be happy to do so :D

**Comment by VivekJaiswal18** [comment]
@benjagm Thanks. :)

**Comment by benjagm** [comment]
The link to this page will go under the overview section.

**Comment by benjagm** [comment]
Can you please make sure the target branch of this PR is : https://github.com/json-schema-org/website/tree/web-release-3?

Reference docs: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by DhairyaMajmudar** [comment]
@VivekJaiswal18 if you need any help feel free to ask : )

**Comment by benjagm** [comment]
@VivekJaiswal18  please proceed with the integration if the component Card available in the parent branch. If you need to modify the component let's discuss first because others are integrating it.

**Comment by VivekJaiswal18** [comment]
Okay Benja, working on the integration

**Comment by VivekJaiswal18** [comment]
Hey, @benjagm sorry for the delay due to some mid sem internal tests going on last week.
I want to take your suggestion on the design changes for the use cases page. Should I change it/make a new card component
Before:
![image](https://github.com/json-schema-org/website/assets/96608169/57117a44-0236-45ed-8250-ab71f2fd3f81)

After:
![image](https://github.com/json-schema-org/website/assets/96608169/cf8c9197-7817-4a0e-b38c-21136f529cbd)
I have made some changes like -  text size and some alignments.
**Intention for the changes** - For pages like these user should be able to see maximum information at the first glance without scrolling too much. 
Here the heading and body text size was too big and taking extra space.
Please have a look and suggest what should I do.
Thank you for reading.

**Comment by benjagm** [comment]
I like the result . Thanks!

**Comment by VivekJaiswal18** [comment]
So shall I create a separate card component for the use cases page @benjagm

**Comment by benjagm** [comment]
I don't think so. Instead modify the current card to use different sizes for the title depending if there is icon or not. With icon size should be smaller, but without icon the title can be bigger.

Does this makes sense?

**Comment by VivekJaiswal18** [comment]
Okay I will modify the same card component. 
But I think size should be independent of whether icon is present or not as in use cases not many cards can have a icons that fits the use cases then in that case heading must not be bigger. This is just a suggestion I'll accept your final call on this. 
Thank you

**Comment by benjagm** [comment]
Let's add a new optional param called size os something like that. You can use it to overwrite te size. You can use M (your size) or XL (current)

Ore something else, but let's improve this cars instead of duplicate

**Comment by VivekJaiswal18** [comment]
Okay benja thanks for helping I will modify the existing component so that it is flexible with any heading size.

**Comment by benjagm** [comment]
Closed as completed.
