### ISSUE TITLE
🐛 Bug: Too much top padding in Blogs landing page

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#427]
### Describe the bug

When accessing the Blogs landing page, there is too much vertical space between the the details of the last blog  (label, title author) and the top menu:
![Screenshot 2024-03-03 at 17 02 45](https://github.com/json-schema-org/website/assets/40007659/1bb92f41-7256-4a43-9f7e-77fa5ae382a4)

In mobile we are loosing most of the content:
![Screenshot 2024-03-03 at 17 03 43](https://github.com/json-schema-org/website/assets/40007659/66c8e49d-dae4-4949-85ac-25fe0cb2ff51)

### Steps To Reproduce

https://json-schema.org/blog

### Expected Behavior

Less vertical padding in desktop version and a better approach for mobile.

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by TamannaVerma99** [comment]
Hey @benjagm !
Just a small note, this issue might be redundant as Issue #412 . I have raised a PR concerning this issue (PR #420 ) which is yet to be reviewed. If there's any feedback on that issue, would resolve the same to cover this issue as well.
Thanks for your time!

**Comment by benjagm** [comment]
Can I assign both issue to you too? So we fix everything? #412 seems focused only in mobile.

**Comment by TamannaVerma99** [comment]
Sure! I will do it. Thanks :)

**Comment by VivekJaiswal18** [comment]
@benjagm So is this issue open. If yes then I am willing to take this issue! Thanks.

**Comment by satyam-x10** [comment]
@benjagm  I am interested in working on this. I have worked on UI with react and typescript .I  would be grateful if i can work on this. Thank you

**Comment by Ekep-Obasi** [comment]
@benjagm I'd love to work on this issue

**Comment by benjagm** [comment]
@TamannaVerma99 please go ahead considering that you are working in the same component.

**Comment by TamannaVerma99** [comment]
Done with the required changes @benjagm .

**Comment by benjagm** [comment]
Closed as completed.
