### ISSUE TITLE
✨ Enhancement: Create a card component to be able to standarize the usage of list of cards 

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#433]
### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

We are working in different issue that require usage of cards like #426 and #421  and it will be beneficial to have a standard card component to be able to use across. 

Examples for reference:
Use Cases
![Screenshot 2024-03-03 at 16 21 37](https://github.com/json-schema-org/website/assets/40007659/e76cea15-1d79-40da-8143-a23592a33cfa)
Docs Landing
![Screenshot 2024-03-03 at 15 16 34](https://github.com/json-schema-org/website/assets/40007659/2e264042-ecf0-4655-9bd6-2269d9a30e43)

### I think the best approach is follow the design used in these card of the landing page:
<img width="1036" alt="Screenshot 2024-03-03 at 23 20 16" src="https://github.com/json-schema-org/website/assets/40007659/6ca1f399-08c1-42b7-8528-9dd1ba6fa007">

The card should support:
- Mandatory: Title
- Mandatory: Body
- Optional: Icon
- Optional: Link

### Are you working on this?

No

**Comment by benjagm** [comment]
@TamannaVerma99 and @VivekJaiswal18 please use this card component for your development.

**Comment by VivekJaiswal18** [comment]
Okay thats good!

**Comment by VivekJaiswal18** [comment]
@benjagm where should we add the navigation button for routing

**Comment by TamannaVerma99** [comment]
okay great!!

**Comment by divyaxdv** [comment]
@benjagm can you please assign this to me?

**Comment by Michael-Obele** [comment]
Is anyone assigned to this? I'd love to do it or collaborate with them.

**Comment by benjagm** [comment]
@Michael-Obele please go ahead with this one. Thanks.

**Comment by TamannaVerma99** [comment]
Hey! @benjagm 
As I have to use this component to proceed with the welcome page issue so should I wait for this issue to get completed first?

**Comment by VivekJaiswal18** [comment]
@benjagm I am almost ready to raise the PR for this issue. Due to some issues I had to travel to my university today.

**Comment by divyaxdv** [comment]
@Michael-Obele let me know if I could assist you in any way. I would be pleased to help .

**Comment by Michael-Obele** [comment]
> @Michael-Obele let me know if I could assist you in any way. I would be pleased to help .

I will, thanks.

**Comment by Michael-Obele** [comment]
Hey guys, I apologize for taking so long to send this PR. I would appreciate your feedback on the design, particularly how it looks with an icon.

**Comment by ayushtiwari110** [comment]
Hey there @benjagm ,
I just came across this task. The progress done so far is great. I had a suggestion that we can use composition logic for making the Card component. We can refactor the current code for this logic. It'll benefit us in following way: 
- Break Down Functionality: Individual card elements (image, title, description, buttons, etc.) could become smaller components.
- Compose the Card: The main card component could then compose these smaller pieces together, using props for layout and any essential overarching data.
- Here's an article for reference: [Why and how to use component composition in React](https://javascript.plainenglish.io/component-composition-in-react-c66f1fd02b45)
I guess if the card component would be having a consistent UI across different usecases, we can still go with the current design. But if the design would be varying, I believe building it in compositional way would be helpful in increasing reusability of the card component.
I would like to hear your opinion on this.

**Comment by Michael-Obele** [comment]
> Hey there @benjagm , I just came across this task. The progress done so far is great. I had a suggestion that we can use composition logic for making the Card component. We can refactor the current code for this logic. It'll benefit us in following way:
> 
> * Break Down Functionality: Individual card elements (image, title, description, buttons, etc.) could become smaller components.
> * Compose the Card: The main card component could then compose these smaller pieces together, using props for layout and any essential overarching data.
> * Here's an article for reference: [Why and how to use component composition in React](https://javascript.plainenglish.io/component-composition-in-react-c66f1fd02b45)
>   I guess if the card component would be having a consistent UI across different usecases, we can still go with the current design. But if the design would be varying, I believe building it in compositional way would be helpful in increasing reusability of the card component.
>   I would like to hear your opinion on this.

Hey, thanks for taking a look at the PR!  I really appreciate the suggestion about using component composition for the card component.  It's a great idea, and I actually started down that path by creating a `CardBody` component.

Here's why I held off on going too much further with breaking things down:

* **Logic is pretty simple:**  Right now, the only real logic in the card is for the link; if there's a link, we wrap everything in it.  Everything else is pretty straightforward: show it if there's data, hide it if not (except for title and body, which are required).
* **Keeping things uniform:** Breaking it down too much might give us a lot of flexibility, but that could also make it harder to keep the cards looking consistent across the app.  Uniformity is a big goal here.
* **Keeping it simple:**  While there are benefits to breaking things down, it can also add complexity.  More components might mean more verbose code with lots of props to pass around, and potentially more documentation needed to explain how to use it all.

So, like you said, it is a great idea!  I'm definitely open to revisiting this if we start needing more flexibility with card layouts in the future.  But for now, I think this approach keeps things clean and easy to manage.

**Comment by Michael-Obele** [comment]
> @Michael-Obele Yeah I do agree with that. Since our current goal is to keep the cards consistent across the app, we can go ahead with current approach. In future we may revisit to this when we feel there are more requirments with the Card component.

Sounds good, thanks for understanding!
