### ISSUE TITLE
✨ Enhancement: Refine the issue templates

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#434]
### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

Id like to refine the setup of the existing issue templates:
* Docs: Assign issues to Docs Team and add new issues to the Project [JSON Schema Docs](https://github.com/orgs/json-schema-org/projects/16)
* Bugs and Enhancements: Assign issue to Triage Team and add new issues to the Project https://github.com/orgs/json-schema-org/projects/11

### Are you working on this?

No

**Comment by DhairyaMajmudar** [comment]
@benjagm I think I can help in this.

**Comment by benjagm** [comment]
All yours @DhairyaMajmudar. Thanks!!
