### ISSUE TITLE
Code formatting issue🐛 Bug: 

### ISSUE THREAD

**Issue by Adity20** [json-schema-org/website#441]
### Describe the bug
Code formatting issue 

When accessing the docs page 
https://json-schema.org/learn/getting-started-step-by-step

There are few code formatting issues like the issue #371 

### Steps To Reproduce

https://json-schema.org/learn/getting-started-step-by-step
![Screenshot 2024-03-04 232032](https://github.com/json-schema-org/website/assets/119804372/8bceba72-bb7d-4091-884e-bfde1b71c423)

### Expected Behavior

Formatted code like this
![Screenshot 2024-03-04 232744](https://github.com/json-schema-org/website/assets/119804372/8e22dcf4-e21b-4a91-8223-f6dc99bc473e)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by Adity20** [comment]
@benjagm any views on this?

**Comment by benjagm** [comment]
This is because the extra "..." in the examples I think we already fixed this but seems not. Issue accepted and available. 

Thanks for finding it.

**Comment by Adity20** [comment]
Can I work on this one as well as I am half way through the issue #371

**Comment by benjagm** [comment]
Go ahead @Adity20 ! Thanks

**Comment by benjagm** [comment]
Sorry @Adity20 . This is being worked here #349

**Comment by benjagm** [comment]
Sorry @Adity20 my fault. Can you please join me to discuss the fix for this in #349?

Let's close this the avoid duplicates.

**Comment by Adity20** [comment]
Yeah sure @benjagm
