### ISSUE TITLE
✨ Enhancement: Auto-assign 'web-team' to PRs

### ISSUE THREAD

**Issue by gregsdennis** [json-schema-org/website#444]
### Is your feature request related to a problem? Please describe

We have a `json-schema.org/web-team` team that should be assigned to PRs.  This will enable notifications for everyone in the team when a new PR is opened, and anyone in the team can approve/merge the PR.

### Describe the solution you'd like

I remember reading that YAML templates can define assignments, but I can't see to find the docs for it.

A custom action would do fine.  (Ideally we'd want to extend an existing action, if one is available, rather than creating a new one.)

### Describe alternatives you've considered

Manual assignments and tagging are inconsistent.

### Are you working on this?

No

**Comment by aialok** [comment]
@gregsdennis , I would love to work on this issue. Please assign : )

**Comment by gregsdennis** [comment]
Sure thing.  Go for it.

(@benjagm please make sure I'm doing this right! 😆)

**Comment by benjagm** [comment]
@aialok are you finally working on this? 

I think this can be easily achieved with the field assignees of the issue templates:

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by gregsdennis** [comment]
> I think this can be easily achieved with the field assignees of the issue templates: - @benjagm 

This is for PRs, not issues.

**Comment by aialok** [comment]
> @aialok are you finally working on this?
> 
> I think this can be easily achieved with the field assignees of the issue templates:
> 
> https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

Thank you, @benjagm. I am currently working on this issue.

@gregsdennis, I have completed the workflow file, but I have a question. As you mentioned earlier, we need to assign the PR to the web team. However, I couldn't find any API endpoint for directly assigning the PR or any actions in marketplace. Instead, there is an endpoint for requesting a review from the team.
You can check it out here: [GitHub REST API - Request Reviewers for a Pull Request](https://docs.github.com/en/rest/pulls/review-requests?apiVersion=2022-11-28#request-reviewers-for-a-pull-request)

I have created a workflow for requesting a review from the team. If this is acceptable, I am ready to submit the PR.

You can review an example here:
PR: [Link to the PR](https://github.com/Lakhua-dev/website/pull/10)
Workflow: [Link to the Workflow](https://github.com/Lakhua-dev/website/actions/runs/8168696488/job/22331263172)

Thank you @gregsdennis @benjagm  : )

**Comment by gregsdennis** [comment]
> Instead, there is an endpoint for requesting a review from the team.

This is what I meant, yes.

**Comment by aialok** [comment]
@gregsdennis , Can you please confirm team slug is `web-team` or `json-schema.org/web-team`?

**Comment by gregsdennis** [comment]
I'm not sure.

**Comment by benjagm** [comment]
@aialok this is the team: https://github.com/orgs/json-schema-org/teams/web-team

**Comment by aialok** [comment]
> @aialok this is the team: https://github.com/orgs/json-schema-org/teams/web-team

Thank you ! Making the PR : )

**Comment by princerajpoot20** [comment]
@gregsdennis @benjagm  I have a suggestion regarding this.
Our aim is to get the notification for the review from the desired team.

For this, we can use the [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) file by github. This file contains the usernames of the maintainers. When someone creates a PR, GitHub automatically `requests a review` from **all the codeowners** and will send a GH notification asking for review.

We can take this **one step further** by creating **different teams** for various areas within the repository. We can also divide maintainers by section, such as assigning **different people for** `docs` or `.md` files and others for any other specific folder (`eg. pages/blog folder section in repo`) **or** the overall project. Any combination that we want is poosible. 
To merge the PR, We need at least one approval from the codeowner of the area of files affected.

Here is an example of the CODEOWNERS file from AsyncAPI's website:
<img width="1312" alt="Screenshot 2024-03-11 at 2 46 09 AM" src="https://github.com/json-schema-org/website/assets/44585452/c71e2b19-eb7c-4bd9-9bfa-2d2b1fc470c2">

This is how it will work in the PR:
<img width="1312" alt="ss1" src="https://github.com/json-schema-org/website/assets/44585452/7561a032-81ba-451a-adbf-baacc5ddff23">

**Comment by aialok** [comment]
Thanks @princerajpoot20, this looks cool can be implemented : )

**Comment by gregsdennis** [comment]
I like this solution. Nice find!

**Comment by benjagm** [comment]
Closed as completed with #505 . Thanks everyone!!
