### ISSUE TITLE
🐛 Bug: "Enhancement" Issue Template field needs adjusting

### ISSUE THREAD

**Issue by gregsdennis** [json-schema-org/website#445]
### Describe the bug

The "additional context" field should be a multiline text field like the others.

### Steps To Reproduce

Start the process to create a new "enhancement" issue.

### Expected Behavior

The "additional context" field should be a multiline text field like the others.

### Screenshots

![image](https://github.com/json-schema-org/website/assets/2676804/0492a7c5-cc49-4c6b-a185-cf90d7261206)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by DhairyaMajmudar** [comment]
Will look into this one

**Comment by DhairyaMajmudar** [comment]
Greg can you pls. assign : D

**Comment by benjagm** [comment]
Reopen it because there was a pending change before I merged:

https://github.com/json-schema-org/website/pull/446#issuecomment-1977970031
