### ISSUE TITLE
🐛 Bug: Warning in the terminal 

### ISSUE THREAD

**Issue by JeelRajodiya** [json-schema-org/website#448]
### Describe the bug

A warning related to JsonEditor component appears in the terminal 

### Steps To Reproduce

**How to reproduce?** run the project locally and go to [this url](http://localhost:3000/learn/getting-started-step-by-step#overview) ( directly by entering this in addresser bar to ensure the page is rendered on the server). 

You will see this **warning** in your terminal along with other hydration errors ( this error does not appear in the browser console it only appears in the terminal ). 

![image](https://github.com/json-schema-org/website/assets/63534268/9fcf9b3d-5385-4033-8177-47f3dede8dc8)

**Solution**: You can find it [here](https://github.com/ianstormtaylor/slate/issues/3163)

### Expected Behavior

There should be no warnings 

### Device Information [optional]

```markdown
- OS: Win 11
- Browser: Chrome 
- version: 122.0.6261.95 (Official Build) (64-bit)
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by Adity20** [comment]
Can I work on this @benjagm

**Comment by benjagm** [comment]
@JeelRajodiya I'll assign this to you considering you are already working on it.
