### ISSUE TITLE
🐛 Bug: Section Hidden in Docs 

### ISSUE THREAD

**Issue by officeneerajsaini** [json-schema-org/website#449]
### Describe the bug

A section property is hidden in the documentation route. Mobile users are unable to access the overview, Getting Started, Reference, and Specification sections. We need to remove the hidden property so that the section appears and all resources from that section can be accessed on mobile.

### Steps To Reproduce

1. Go to [Docs](https://json-schema.org/learn/getting-started-step-by-step)
2. and see you are unable to see those resources

![Screenshot from 2024-03-05 15-01-09](https://github.com/json-schema-org/website/assets/118799941/bc3de679-bccf-4157-a094-ea883b09c044)

### Expected Behavior

![Screenshot from 2024-03-05 15-00-46](https://github.com/json-schema-org/website/assets/118799941/57814315-c6d2-4496-8bba-4f94458e1697)

### Device Information [optional]

```markdown
- OS: Linux Ubuntu 20.04.6 LTS
- Browser:Google Chrome
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by Codesmith28** [comment]
@officeneerajsaini  I think we can access this menu on the phone by clicking the chevron icon.

**Comment by officeneerajsaini** [comment]
@Codesmith28 yeah you are right .
