### ISSUE TITLE
🐛 Bug: The Footer Element 'OpenJS' is not used in the Footer Section

### ISSUE THREAD

**Issue by officeneerajsaini** [json-schema-org/website#452]
### Describe the bug

The Footer Element 'OpenJS' is not used in the Footer Section. It has already been declared, but we need to add it to the footer section.

### Steps To Reproduce

1. Go to Footer Section
2. There No "OpenJS Foundation" Section

![Screenshot from 2024-03-05 20-34-12](https://github.com/json-schema-org/website/assets/118799941/24193225-b6a5-44c4-ada2-a12443ac82d1)

### Expected Behavior

There Should be Open Foundation Section Visible 

![Screenshot from 2024-03-05 20-33-43](https://github.com/json-schema-org/website/assets/118799941/3bd795d4-449a-4990-a727-1a5f1064b528)

### Device Information [optional]

```markdown
- OS:Linux Ubuntu @20.04.06 LTS
- Browser: Google Chrome
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by officeneerajsaini** [comment]
@benjagm Assign this issue to  me i alredy fixed that issue , i need to only make a PR

**Comment by benjagm** [comment]
That section has been deliberately removed by us as we are not part of OpenJS as of now. During this situation we dont want that section the be shown.

**Comment by officeneerajsaini** [comment]
okay

**Comment by officeneerajsaini** [comment]
@benjagm There is one more issue in the footer section. On the /docs or /specification pages, there is some extra space below the footer. However, I am unable to access that area in Chrome Developer Mode. Can someone please fix that issue?

![Screenshot from 2024-03-05 21-19-46](https://github.com/json-schema-org/website/assets/118799941/c113ee93-3e1c-4be8-87eb-7457f79b8352)

**Comment by benjagm** [comment]
> @benjagm There is one more issue in the footer section. On the /docs or /specification pages, there is some extra space below the footer. However, I am unable to access that area in Chrome Developer Mode. Can someone please fix that issue?
> 
> ![Screenshot from 2024-03-05 21-19-46](https://private-user-images.githubusercontent.com/118799941/310188244-c113ee93-3e1c-4be8-87eb-7457f79b8352.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NTc2OTgsIm5iZiI6MTcwOTY1NzM5OCwicGF0aCI6Ii8xMTg3OTk5NDEvMzEwMTg4MjQ0LWMxMTNlZTkzLTNlMWMtNGJlOC04N2ViLTc0NTdmNzliODM1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxNjQ5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTZjODBlZGUyZTgyNmVmZDU1OTRjOTQ5YWM0YWM1NzViNzBmYzQ2M2I0Mzc1ODJkZTc4MDY2MTk2NTRhMTY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xUPWWjetzMxn9CdjcAUZfZQKSjjjCjCXBCuEB1RBIys)

Let's create a new issue. Do you mind open it?

**Comment by officeneerajsaini** [comment]
Okay i will create new issue

**Comment by officeneerajsaini** [comment]
@benjagm  you can close this issue .
