### ISSUE TITLE
[📝 Docs]: Remove references to OpenJS Foundation in the website.

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#453]
### What Docs changes are you proposing?

We'd like to remove all the references to OpenJS foundation in the website repository.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DhairyaMajmudar** [comment]
Shall I take this up : )

**Comment by divyaxdv** [comment]
I would like to take this up @benjagm

**Comment by benjagm** [comment]
Thanks everyone. In order of request. Please @DhairyaMajmudar go ahead.
