### ISSUE TITLE
🐛 Bug: extra space below the footer

### ISSUE THREAD

**Issue by officeneerajsaini** [json-schema-org/website#455]
### Describe the bug

On the /docs or /specification pages, there is some extra space below the footer. However, I am unable to access that area in Chrome Developer Mode. Can someone please fix that issue?

### Steps To Reproduce

1. Go to /docs page 
2.  Go to Footer Section
3. Below Footer you can see some extra space
4. You need to remove that white space 

![310188244-c113ee93-3e1c-4be8-87eb-7457f79b8352](https://github.com/json-schema-org/website/assets/118799941/4d6c5d14-02ff-4583-ae8a-05c431dad6f2)

### Expected Behavior

Remove extra space 

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by VivekJaiswal18** [comment]
Can I take this Issue

**Comment by officeneerajsaini** [comment]
@VivekJaiswal18  sure

**Comment by Ali7040** [comment]
@officeneerajsaini Assign it to me if it's available.

**Comment by officeneerajsaini** [comment]
> @officeneerajsaini Assign it to me if it's available.

@Ali7040  im not maintainer or member of JSON Schema .  i am a contributer like you , you should ask to a maintainer about assign to you .

**Comment by benjagm** [comment]
@Ali7040 thanks for your interest. Please go ahead.

**Comment by benjagm** [comment]
Closed as completed.
