### ISSUE TITLE
🐛 Bug: Indentation problems with JsonEditor component

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#456]
### Describe the bug

We had  issues in the past with the JsonEditor component in small devices because it produced horizontal overflow. For this reason we needed to disable the wrapLines and wrapLongLines attributes  in this commit [cd30786](https://github.com/json-schema-org/website/commit/cd3078604f28ecc1e9c3ad292e399b06cc97c17c) but this is producing unexpected indentation issues like the one discussed [here](https://github.com/json-schema-org/website/pull/385).

The component is this one:
https://github.com/json-schema-org/website/blob/main/components/JsonEditor.tsx

The solution we expect is enable wrapLines and wrapLongLines and add a horizontal scroll bar in component so we producer the best developer experience in all code snippets.

![Screenshot 2024-03-05 at 18 32 09](https://github.com/json-schema-org/website/assets/40007659/399d7cba-bda1-4bde-807a-a0cb0f8483d6)

![Screenshot 2024-03-05 at 18 32 52](https://github.com/json-schema-org/website/assets/40007659/e8d62a0d-68a2-438c-974e-43952e23b8c2)

### Steps To Reproduce

Any page with code snippets in mobile devices.

### Expected Behavior

Horizontal scroll bar at the bottom of the component.

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by Adity20** [comment]
@benjagm I'll start working on this right away.

**Comment by benjagm** [comment]
Thanks @Adity20 !!

**Comment by Adity20** [comment]
@benjagm jsonc format is causing some formatting issue with this component. I am done with all changes for other components and the overflow issue also but there is some issue with this code component.
![Screenshot 2024-03-08 150504](https://github.com/json-schema-org/website/assets/119804372/669e7d7e-f875-4d4d-b7ad-6d184b4536ae)

**Comment by Adity20** [comment]
Okay @benjagm

**Comment by Adity20** [comment]
showing this error while i try to commit the changes 
Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

I tried everything the only solution is to change the linebreak-style to windows but I guess i am not supposed to do that
