### ISSUE TITLE
🐛 Bug: disable carbon adds in small devices because

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#457]
### Describe the bug

We need to disable carbon adds in small devices because we prefer to use the screen just for content. In addition the last ads feature is not working well for mobiles.

https://json-schema.org/blog/posts/dynamicref-and-generics

### Steps To Reproduce

This can be reproduced [any of the blog posts](https://json-schema.org/blog/posts/understanding-lexical-dynamic-scopes) and gradually reducing the size of the screen. As soon as the sidebar disappears adds goes on top producing an undesirable result. As soon as the sidebar disappears the add should be removed/hidden as well.

### Expected Behavior

As soon as the sidebar disappears adds goes on top producing an undesirable result. As soon as the sidebar disappears the add should be removed/hidden as well.

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by TamannaVerma99** [comment]
May I take it up @benjagm ?

**Comment by TamannaVerma99** [comment]
Do we need to remove adds from tablet size too?

**Comment by divyaxdv** [comment]
@benjagm I am intrested in this issue,  It will be helpful if you can clearify that small devices only includes mobile or tablets also?

**Comment by benjagm** [comment]
We'll remove ads in the breaking point when the sidebar dissapear.

**Comment by benjagm** [comment]
@divyaxdv please go ahead with the issue as @TamannaVerma99 have some currently assigned.

**Comment by DarhkVoyd** [comment]
@benjagm The Carbon ads component is designed to be responsive, as it already has a media query in place to fetch and display ads only after the sidebar breaking point. I'm curious if, when encountering the issue, you might have initially visited the page with a viewport that triggered the ads to load and then later resized the viewport manually using dev tools. This scenario might not accurately represent the experience for regular users. Could you please provide more details or steps to reproduce the problem? Thanks!

**Comment by benjagm** [comment]
> The Carbon ads component is designed to be responsive

This can be reproduced [any of the blog posts](https://json-schema.org/blog/posts/understanding-lexical-dynamic-scopes) and gradually reducing the size of the screen. As soon as the sidebar disappears adds goes on top producing an undesirable result. As soon as the sidebar disappears the add should be removed/hidden as well.

**Comment by DarhkVoyd** [comment]
>  I'm curious if, when encountering the issue, you might have initially visited the page with a viewport that triggered the ads to load and then later resized the viewport manually using dev tools.

The component checks for the media width on the initial request and only then sends request and loads the ad. The resizing width using dev tools scenario might not accurately represent the experience for regular users, how about we instead adjust the location of the loaded ad when media query changes. This is based on the carbon ads resource that you shared on the initial implementation that suggested along the lines of `If you send a loadAd request to carbonAds please ensure the ad is properly visible to avoid decreasing the CPM rate.`. So, if the ad is already loaded it might not be the best idea to hide or remove it.

**Comment by benjagm** [comment]
I trust in your criteria @DarhkVoyd . So nothing to do with this issue. Right?

**Comment by DarhkVoyd** [comment]
> I trust in your criteria @DarhkVoyd . So nothing to do with this issue. Right?

After thinking for a while, there exists one scenario where this could happen to a regular user i.e. if you visit our website on a longer tablet device in the landscape mode then the media query would satisfy rendering the ad and later if they switch back from landscape to portrait mode the ad would produce this undesired placement. While I am unsure if the current placement would look bad in the tablet sized device, we could possibly better style the ad & placement for this niche case. Apologies for missing this in the initial implementation.

**Comment by benjagm** [comment]
All good DV. :-). Let's find a solution then.

**Comment by DarhkVoyd** [comment]
> All good DV. :-). Let's find a solution then.

In this case, I believe you were right, adding a media query switch for `display: none` would be a clean and simple solution for this issue. Since, we would still be showing the ad while they are in the landscape mode, so it might not hurt the CPM.

**Comment by DarhkVoyd** [comment]
divyaxdv,
Apologies for the delay, please feel free to work on the issue.

**Comment by divyaxdv** [comment]
sure, DarhkVoyd
