### ISSUE TITLE
🐛 Bug: Lesser top margin on fixed sidebar on blog post page on scrolling.

### ISSUE THREAD

**Issue by TamannaVerma99** [json-schema-org/website#458]
### Describe the bug

On the blog post page left side container (containing information about 'on this page' and author) is  given fixed property on scrolling  but it requires more margin from the top .

![present blog fixed bar](https://github.com/json-schema-org/website/assets/96949249/c1858631-85b3-4a89-921f-ba62ae271cf4)

 

### Steps To Reproduce

1. Click on [LINK](https://json-schema.org/blog/posts/understanding-lexical-dynamic-scopes)
2. Scroll it down until the left container get fixed.

### Expected Behavior

Required top margin for left container on scrolling:

![required blog fixed bar](https://github.com/json-schema-org/website/assets/96949249/3fd58947-45f3-4e36-ac1b-73640700a1e5)

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by TamannaVerma99** [comment]
@benjagm while working on blog page I got to now about this bug, may I correct it ?

**Comment by benjagm** [comment]
I am not able ro reproduce this. It seems that you are doing just vertical scrolling in the page.

![Screenshot 2024-03-05 at 18 58 12](https://github.com/json-schema-org/website/assets/40007659/84259603-32fb-4725-a31a-da4bccdf2c25)

**Comment by TamannaVerma99** [comment]
On scrolling the blog vertically on desktop view I am getting this.You may too get it on scrolling as I have shown in screenshot.

**Comment by benjagm** [comment]
> On scrolling the blog vertically on desktop view I am getting this.You may too get it on scrolling as I have shown in screenshot.

Can you record a short video? I think I am not getting what is the problem. I am sure it is just me.

**Comment by kx412764776** [comment]
I think what he means is that there needs to be more top margin here. Main navbar will obscure part of the author avatar after scrolling vertically

**Comment by TamannaVerma99** [comment]
The 'Go Back to Blog' option gets hidden when scrolled and the visibility of author image too is disturbed.

https://github.com/json-schema-org/website/assets/96949249/ed87a231-7c2e-4e0c-96a7-c6fbbf1c9959

**Comment by TamannaVerma99** [comment]
@benjagm  I have added a video for reference.Thanks!

**Comment by benjagm** [comment]
Thanks @TamannaVerma99 Now I understand thanks. Issue accepted and available for contributors

**Comment by TamannaVerma99** [comment]
Thanks @benjagm 
May I proceed with this issue?

**Comment by benjagm** [comment]
Thanks @TamannaVerma99 . Please go ahead.
