### ISSUE TITLE
🐛 Bug: Broken alignment of fragment in Specification section

### ISSUE THREAD

**Issue by VivekJaiswal18** [json-schema-org/website#462]
### Describe the bug

When clicking on the Specification heading it is not aligning to the header but getting scrolled too much.

### Steps To Reproduce

1. Go to https://json-schema.org/specification 
2. Click on the Specification Heading 

### Expected Behavior

It must be aligning to the header 

### Screenshots

https://github.com/json-schema-org/website/assets/96608169/75f7a105-fd72-451e-aeca-a11d88611246

### Device Information [optional]

```markdown
- OS: Windows
- Browser: Chrome
- version: 122.0.6261.94
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by VivekJaiswal18** [comment]
I am working on this Issue

**Comment by benjagm** [comment]
Thanks @VivekJaiswal18 . I think you can fix this and #463 in the same PR. We did some changes to improve the heading location after click and I think we still have some work to do. Thanks.

I assigned the issue to you.

**Comment by VivekJaiswal18** [comment]
Okay Thanks!!

**Comment by AdityaSingh-02** [comment]
Heyy @VivekJaiswal18 are you still working on this?? Can I help?

**Comment by lalitkumawat1m** [comment]
Hey @VivekJaiswal18 are you working on it?

**Comment by VivekJaiswal18** [comment]
Yes

**Comment by AdityaSingh-02** [comment]
@VivekJaiswal18 Are you still working??

**Comment by VivekJaiswal18** [comment]
hey @AdityaSingh-02 this issue does not have much to do but to solve this I have to change somethings in the deployed website and for that I need @benjagm to give me a conformation as I don't want to proceed without the permission. you can look the comment i left in #463 its the same issue. So waiting for the conformation.
