### ISSUE TITLE
🐛 Bug: Scrolling Becomes Unresponsive When Opening Search Bar on Docs Page; Auto-Scroll to Top Needed to reach Search bar

### ISSUE THREAD

**Issue by MeastroZI** [json-schema-org/website#478]
### Describe the bug

When clicking on the search bar in the documentation section with a screen width of less than 769 pixels, the scroll functionality becomes unresponsive. Users are unable to access the scroll and it remains unresponsive until the search bar is open. Consequently, users have no option but to reload the page.

### Steps To Reproduce

1) Navigate to the docs page of the website and adjust the screen width less than 769 pixels.
2) Click on the search icon to open the search bar.
3) Attempt to scroll down/up the page while the search bar is open.

### Expected Behavior

The page should scroll smoothly to the top ( to the search bar ) when click on the search button

### Screenshots

[Screencast from 07-03-24 11:17:12 AM IST.webm](https://github.com/json-schema-org/website/assets/106718914/077d2854-9a99-4b6c-81ce-f6a950a06296)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by AdityaSingh-02** [comment]
@benjagm Can I work on this issue?

**Comment by benjagm** [comment]
Thanks @MeastroZI! Are you already working on this?

**Comment by MeastroZI** [comment]
> Thanks @MeastroZI! Are you already working on this?

Thanks for your message, sir. Yes, I am working on this issue

**Comment by benjagm** [comment]
Closed as completed. Thanks a lot for your contributions!
