### ISSUE TITLE
🐛 Bug: Overflow of text in validators on tools page.

### ISSUE THREAD

**Issue by TamannaVerma99** [json-schema-org/website#485]
### Describe the bug

There is an overflow of text in validators on tools page on reducing screen dimensions less than desktop view.

![buttons bug](https://github.com/json-schema-org/website/assets/96949249/1b3efc73-9a79-4a5e-98ac-66aadf69a3bb)

### Steps To Reproduce

1. Go to [LINK](https://json-schema.org/)
2. Click on tools page from main navigation bar.

### Expected Behavior

![buttons expected](https://github.com/json-schema-org/website/assets/96949249/27cae88d-48b2-4a22-a2f1-3b900ffd3f39)

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by TamannaVerma99** [comment]
Hey! @benjagm
Should I work on  this?

**Comment by benjagm** [comment]
Thanks Tammana! Please go ahead.
