### ISSUE TITLE
🐛 Bug: Broken alignment in options menu when in mobile view

### ISSUE THREAD

**Issue by VivekJaiswal18** [json-schema-org/website#486]
### Describe the bug

When clicking on the options menu in mobile view the menu is not aligned properly.

### Steps To Reproduce

1. Set Dimensions to Mobile view
2. Go to page: Tools and Blogs
3. Click on the hamburger menu

### Expected Behavior

It should not have visible gap in between the header and the menu options

### Screenshots

https://github.com/json-schema-org/website/assets/96608169/922378c3-b99a-4207-803a-b54b32369cb7

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by VivekJaiswal18** [comment]
@benjagm please have a look

**Comment by maverox** [comment]
@benjagm Please assign this to me if it hasn't been assigned to anyone else.
I am looking into the solution currently

**Comment by benjagm** [comment]
Thanks for filing this issue. I am concerned this is duplicated with #485

**Comment by benjagm** [comment]
Issue reopened.

**Comment by satyam-x10** [comment]
@benjagm i will  like to work on this. with my expertise i i can achieve this.

**Comment by VivekJaiswal18** [comment]
Yes @benjagm no worries.

**Comment by satyam-x10** [comment]
@benjagm i have raised a PR and the bug was solved. Have a look and let me have your  feedback. Thanks . https://github.com/json-schema-org/website/pull/511

**Comment by benjagm** [comment]
Closed as completed. Thanks for your contributions.
