### ISSUE TITLE
🐛 Bug: Justify Content is not applied

### ISSUE THREAD

**Issue by Sahil-Shadwal** [json-schema-org/website#488]
### Describe the bug

The contents in https://json-schema.org/draft/2020-12/release-notes are not justified. Which is making it look messy, so i would suggest Justify alignment to be applied to get more authentic visual presentation.

### Steps To Reproduce

1. Go to https://json-schema.org/draft/2020-12/release-notes

### Expected Behavior

The content should be justified 

### Screenshots

![Screenshot from 2024-03-09 15-54-16](https://github.com/json-schema-org/website/assets/119167601/c1207dd9-4ef8-4921-a792-81a7233596a9)

### Device Information [optional]

```markdown
- OS:Windows
- Browser:Chrome
- version:
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by benjagm** [comment]
I think Justified can bring unexpected experience when dealing with code lists and so on like we are. 

Can you provide some examples of developer docs using justified format?

**Comment by Sahil-Shadwal** [comment]
Yeah you are right, i looked into other docs they don't use justify alignment. But i did saw most of them use dark mode, what are your thoughts on that ?

**Comment by Sahil-Shadwal** [comment]
Hey @benjagm  can you hook me up with some issues, and whats the qualification criteria of the tooling page project?
