### ISSUE TITLE
🐛 Bug: All pages inside Specification page must be aligned

### ISSUE THREAD

**Issue by VivekJaiswal18** [json-schema-org/website#490]
### Describe the bug

Inside specification, every page is showing overflow and as a result zooming out is also an option which must be fixed.

### Steps To Reproduce

1. Go to any page inside the specification page 

### Expected Behavior

It must be behaving like other pages 

### Screenshots

![Screenshot (8)](https://github.com/json-schema-org/website/assets/96608169/8bdb7282-8c19-4433-98f0-8ced388910a5)

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by VivekJaiswal18** [comment]
Hello @benjagm please have a look into this issue and also issue #491

**Comment by benjagm** [comment]
Accepted and assigned to you. Thanks.

**Comment by lalitkumawat1m** [comment]
Hey @VivekJaiswal18 !
Are you working on this issue or can I take this?

**Comment by AdityaSingh-02** [comment]
Heyy @VivekJaiswal18 This issue was fixed in #483 #498

**Comment by benjagm** [comment]
Vivek. Are you still working on this issue?

**Comment by VivekJaiswal18** [comment]
@benjagm After solving this issue I saw it is being solved in PR #483 so I dropped it. But still I see the same issue in other pages of the deployed branch and solved that shall I raise another issue for those separately or I solve in this issue only and raise a PR

**Comment by benjagm** [comment]
Use this one making sure the issue and the PR have the scope updated

**Comment by benjagm** [comment]
Making this issue available for others as there as been no progress in the last 3 weeks

**Comment by DhairyaMajmudar** [comment]
Seems like this issue is now resolved

![image](https://github.com/json-schema-org/website/assets/124715224/ca6b77fe-a2c2-4893-aefd-026a29375dd0)

**Comment by Michael-Obele** [comment]
Hi @benjagm, Great news! It looks like the issue might be resolved. I just checked it on my end, and everything seems to be working well.

**Comment by benjagm** [comment]
Thanks everyone! Closed as this has been fixed.
