### ISSUE TITLE
✨ Enhancement: Sidebar must be removed automatically when an option is chosen/clicked in mobile view

### ISSUE THREAD

**Issue by VivekJaiswal18** [json-schema-org/website#491]
### Is your feature request related to a problem? Please describe

https://github.com/json-schema-org/website/assets/96608169/248aafe3-ae11-4e18-97de-83b1ee08d8f6

### Describe the solution you'd like

It must remove the sidebar when user clicks on an option. It can be solved in many ways like using state management, etc. 

### Are you working on this?

Yes

**Comment by benjagm** [comment]
This makes total sense. Thanks Vivek!

**Comment by AdityaSingh-02** [comment]
Heyy @VivekJaiswal18 Are you still working on it?? I was wondering Can I work alongside you maybe I could help 🚀
Hey @benjagm Can I also work alongside @VivekJaiswal18 ??

**Comment by VivekJaiswal18** [comment]
Thank you. But I am almost done with this issue.

**Comment by VivekJaiswal18** [comment]
Hey @benjagm is it right time to raise a PR. I know there was some trouble rolling out the last version with dark theme merger
