### ISSUE TITLE
🐛 Bug:  tool page is not responsive on small devices

### ISSUE THREAD

**Issue by Ali7040** [json-schema-org/website#495]
### Describe the bug

When accessing the tool page on devices with a width below 850 pixels, its behavior changes, and it becomes non-responsive.

### Steps To Reproduce

Go to the tool page, scroll a bit, and check its responsiveness for small devices.

### Expected Behavior

It should be responsive for small devices.

### Screenshots

<img width="775" alt="Screenshot 2024-03-09 at 6 19 51 PM" src="https://github.com/json-schema-org/website/assets/81979505/67bdbf7c-1947-4e06-9825-fe5f9418defd">

### Device Information [optional]

```markdown
- OS: macOS
- Browser: Chrome
- version:
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by AdityaSingh-02** [comment]
@benjagm Can I work on this issue?

**Comment by benjagm** [comment]
Hi @Ali7040. I think we'll work this as part as #485
