### ISSUE TITLE
🐛 Bug: Issue with workflow to Greeting the new contributor 

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#500]
### Describe the bug

We are getting too much executions of the workflow for greeting new contributors:

I am thinking that maybe we need to add some additional criteria in the trigger. As of now the trigger is:

````
on: [pull_request, issues]
````

but I think we need to add the  activity types as well.

````
on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]
````

### Steps To Reproduce

The workflow triggers in these scenarios:

on: [pull_request, issues]

### Expected Behavior

not error.

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by aialok** [comment]
Thank you, @benjagm. This workflow runs for every commit on a pull request. I can work on this issue to fix this, or if any new contributor is looking for their first issue, they are good to go. Otherwise, please assign this to me.

**Comment by Adity20** [comment]
Can I work on this @benjagm?

**Comment by ayushtiwari110** [comment]
Hey @benjagm , I'm open to working on this. I've also implemented our CI workflow pipeline, and these days I'm learning in more detail about pipelines and Github Actions, so I'll try to figure out what's happening in this workflow.

**Comment by Sahil-Shadwal** [comment]
Can I work on this issue .

**Comment by benjagm** [comment]
All yours Sahil!
