### ISSUE TITLE
✨ Enhancement: Dark Mode

### ISSUE THREAD

**Issue by Sahil-Shadwal** [json-schema-org/website#501]
### Is your feature request related to a problem? Please describe

Light Mode put stress on the eyes, it would be great to have dark mode

### Describe the solution you'd like

I would like to add a feature of light/dark mode. Like here :
![image](https://github.com/json-schema-org/website/assets/119167601/345635d0-5cf2-4218-ad2d-4832ac62e6ca)

### Additional context

Here are some common features and benefits of dark mode:

1. Reduced Eye Strain
2. Improved Visibility in Low Light
3. Aesthetic Appeal
4. Focus and Attention
5. Consistency Across Devices

### Are you working on this?

Yes

**Comment by JeelRajodiya** [comment]
Hello @Sahil-Shadwal, There is already a PR for dark mode. please check #365
Thanks showing interest !
