### ISSUE TITLE
🐛 Bug: UI Bug - In the Tools page, table and tags are hidden on Smaller Viewports

### ISSUE THREAD

**Issue by ayushtiwari110** [json-schema-org/website#502]
### Describe the bug

In the Tools page, on medium and small-sized viewports (<600), the tags and table in the validator section are not visible properly. The name of validator tags seems to be cut-off by small amout for medium devices, and more for smaller devices.

### Steps To Reproduce

- Go to https://json-schema.org/implementations , and try decreasing the viewport width below ~600. The cutoffs will start to become visible

### Expected Behavior

The table and its associated tags should remain completely visible and correctly formatted on medium and small-sized viewports. They should adapt to the available screen space.

### Screenshots

![json-schema org_implementations (1)](https://github.com/json-schema-org/website/assets/84335414/e10f4ecc-e972-43df-9716-2d2b61e7c6fe)
![json-schema org_implementations](https://github.com/json-schema-org/website/assets/84335414/73a41736-94c1-4e56-b5f5-1b9d8de3727a)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

Yes

**Comment by ayushtiwari110** [comment]
@benjagm , I noticed this small issue in the UI responsiveness of Tools page. Would like to hear your feedback on this, and if it seems a bug to solve, I would like to take this.

**Comment by benjagm** [comment]
Hi @ayushtiwari110. We'll work this as part of #485

**Comment by benjagm** [comment]
Issue reopened.

**Comment by ayushtiwari110** [comment]
Can I work on this?

**Comment by benjagm** [comment]
Yes please. Thanks a lot.

**Comment by benjagm** [comment]
To fix it maybe we'll need to hide some columns for small devices.

**Comment by benjagm** [comment]
> Yeah , or I was thinking maybe we can reduce the relative font size in small devices... I'll try the available options and see which works better

Sounds good! Thanks.
