### ISSUE TITLE
✨ Enhancement: To create a scroll to top button 

### ISSUE THREAD

**Issue by DhairyaMajmudar** [json-schema-org/website#503]
### Is your feature request related to a problem? Please describe

To create a scroll to top button so that users can easily navigate to top.

### Describe the solution you'd like

To create a top scroll to top button by taking reference from the [AsyncAPI Website](https://www.asyncapi.com/en) 

![Screenshot from 2024-03-11 17-55-19](https://github.com/json-schema-org/website/assets/124715224/47436d0b-590d-4372-9663-caab78f0cfeb)

### Describe alternatives you've considered

N/A

### Additional context

N/A

### Are you working on this?

Yes

**Comment by DhairyaMajmudar** [comment]
I would love to have create a scroll to top button for the website : D

**Comment by satyam-x10** [comment]
@benjagm this looks like a nice feature to add. I would like to implement this . Thanks

**Comment by DhairyaMajmudar** [comment]
> This is cool! Accepted. Are you working on this?

Yes I am working on this.
