### ISSUE TITLE
Shrink version of the header menu when outside the landing page

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#52]
Can we shrink the header  it as much as possible when viewing pages that are not the landing page?

**Comment by benjagm** [comment]
Thanks @deveshidwivedi! Issue is yours.

**Comment by Maykkkk** [comment]
Hey @benjagm I would like to contribute in this issue is it still open?

**Comment by nikhilyadav24** [comment]
Hey @benjagm , Please assign this to me.

**Comment by benjagm** [comment]
After long consideration we have decided to not implement this feature. Thanks.
