### ISSUE TITLE
🐛 Bug: Unexpected behavior of dark mode feature

### ISSUE THREAD

**Issue by AgniveshChaubey** [json-schema-org/website#523]
### Describe the bug

The [following section](https://json-schema.org/understanding-json-schema/reference/object) doesn't look good in the dark mode
![image](https://github.com/json-schema-org/website/assets/113545196/4c127bf3-097e-4eae-be34-627ce7b50fb7)

### Unexpected behavior
My machine is defaulted to dark mode.
when I open the [website](https://json-schema.org/understanding-json-schema/reference/object), initially, I can't see the logo and some of the icons (including search and sidebar icons) in the correct mode.
![image](https://github.com/json-schema-org/website/assets/113545196/ba160474-5966-4046-b6ec-c558d161100e)
![image](https://github.com/json-schema-org/website/assets/113545196/bd0ef629-07c4-43fb-aee4-fa2e702ce803)
![image](https://github.com/json-schema-org/website/assets/113545196/5a2f9510-cca9-4198-bbb7-0d409928cca6)

Additionally, when I change the mode for first time, the dark mode button changes to `sun icon`, but the theme doesn't't change to light mode. However, the logo and other icons mentioned previously work as intended (after the first click). Afterwards, the button works properly, but the only catch remain is the mismatch of the icons with the theme.

Demo:

https://github.com/json-schema-org/website/assets/113545196/5a63af12-6fa0-42ba-a66f-6e4c22c298ea

**Comment by benjagm** [comment]
Thanks for finding this! Issue accepted and available for contributors to pick it up.

**Comment by benjagm** [comment]
Thanks for finding this! Issue accepted and available for contributors to pick it up.

**Comment by officeneerajsaini** [comment]
footer section totaly changed  

![Screenshot from 2024-03-13 18-51-57](https://github.com/json-schema-org/website/assets/118799941/518f0156-892c-4920-9ceb-7fcbe2f3dc4e)

**Comment by benjagm** [comment]
> footer section totaly changed
> 

Thanks @officeneerajsaini Can you please open an issue. We have lost the change we made in the footer.

**Comment by benjagm** [comment]
> > footer section totaly changed
> 
> Thanks @officeneerajsaini Can you please open an issue. We have lost the change we made in the footer.

I just created a new issue for this. #526

**Comment by DhairyaMajmudar** [comment]
> Along with that many old bugs which was resolved by several PRs are now visible again
> 
> * Unexpected gap below the Footer section
> 
> ![image](https://private-user-images.githubusercontent.com/124715224/312467565-398c6caa-a14e-4437-b5d7-3a12e05bf009.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMzgyMzgsIm5iZiI6MTcxMDMzNzkzOCwicGF0aCI6Ii8xMjQ3MTUyMjQvMzEyNDY3NTY1LTM5OGM2Y2FhLWExNGUtNDQzNy1iNWQ3LTNhMTJlMDViZjAwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QxMzUyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTQzYjRhMmE3NTE0MDgzNmIzOWE3NDBmMGE0NGM2ZWYxOTRiNGJmMTQwMzRjNGVhMTM5YTI2NTFmYzQxYjNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aheXJFnwOanAqD3uZasgp_WCdRVbxQIXrDt1zhfudNg)
> 
> * Search box not aligned properly
> 
> ![image](https://private-user-images.githubusercontent.com/124715224/312467886-006921e6-6aab-4217-b140-7a5c41e66d02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMzgyMzgsIm5iZiI6MTcxMDMzNzkzOCwicGF0aCI6Ii8xMjQ3MTUyMjQvMzEyNDY3ODg2LTAwNjkyMWU2LTZhYWItNDIxNy1iMTQwLTdhNWM0MWU2NmQwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QxMzUyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOGY3ZGY5MGZkZDAzYjEwOTYwODUzODA3ZmQwYTFmYmNjMGUyYTJkMjZkZTdlOTY1MDE0NjdhNjk4MWI0N2UyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ilsnNIDT17QM5peYIZagc021q3738AljD_Xhk5r-pGQ)
> 
> * Shadow when modal is open in mobile view
> 
> ![image](https://private-user-images.githubusercontent.com/124715224/312470145-d954807d-ef47-468c-b4f1-61833b78daee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMzgyMzgsIm5iZiI6MTcxMDMzNzkzOCwicGF0aCI6Ii8xMjQ3MTUyMjQvMzEyNDcwMTQ1LWQ5NTQ4MDdkLWVmNDctNDY4Yy1iNGYxLTYxODMzYjc4ZGFlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QxMzUyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDA1NzU2MTg1YmIwOGU5NzZjNjIyYzE0MTNmNmUyNGRlNTE3NmU2YzAxM2Q1MDNmOGY3YTYyODJjNTg1ODdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vroXFg9PGo7wVScCovgSUltPor0skvATf6OE3joHv74)
> 
> * Overflow in the blogs page.

Pls. create issue for this one also : )

**Comment by benjagm** [comment]
> Pls. create issue for this one also : )

Can you please create it?

**Comment by satyam-x10** [comment]
@benjagm  This looks interseting. I would love to work on this . Can u assign me with this too. Thanks

**Comment by officeneerajsaini** [comment]
@DhairyaMajmudar @AgniveshChaubey , are these issues arising because the dark theme pull request was merged? If so, can we revert that pull request and then update that branch with the upstream? Afterward, we can merge that branch, which may solve all the problems.

**Comment by DhairyaMajmudar** [comment]
> > Pls. create issue for this one also : )
> 
> Can you please create it? It will require review the whole landing page.

sure thing, I have one firefox extension for taking whole screenshot of landing page to point out bugs.

**Comment by DhairyaMajmudar** [comment]
Yes Neeraj these after these problems are arising after the merger of dark theme PR.

**Comment by benjagm** [comment]
> @DhairyaMajmudar @AgniveshChaubey , are these issues arising because the dark theme pull request was merged? If so, can we revert that pull request and then update that branch with the upstream? Afterward, we can merge that branch, which may solve all the problems.

I have roll backed the deployment but the changes are in the master branch. We need someone to take a look to see what else we have lost comparing master branch with https://github.com/json-schema-org/website/commit/ca8cd66b43121ec20d8f393eb78570ae23dfe9ff

**Comment by officeneerajsaini** [comment]
So what we do now ?  Are we need to open new issues for previous issues ?

**Comment by benjagm** [comment]
@satyam-x10 Please use this branch as master branch: https://github.com/json-schema-org/website/tree/web-dark-theme

**Comment by DhairyaMajmudar** [comment]
One solution can be to create a new branch for dark theme and compare it with the main branch such that old changes are not lost

**Comment by benjagm** [comment]
> So what we do now ? Are we need to open new issues for previous issues ?

We need someone to do this:

I have roll backed the deployment but the changes are in the master branch. We need someone to take a look to see what else we have lost comparing master branch with the previous commit to the dark theme https://github.com/json-schema-org/website/commit/ca8cd66b43121ec20d8f393eb78570ae23dfe9ff

**Comment by DhairyaMajmudar** [comment]
> > So what we do now ? Are we need to open new issues for previous issues ?
> 
> We need someone to do this:
> 
> I have roll backed the deployment but the changes are in the master branch. We need someone to take a look to see what else we have lost comparing master branch with the previous commit to the dark theme [ca8cd66](https://github.com/json-schema-org/website/commit/ca8cd66b43121ec20d8f393eb78570ae23dfe9ff)

I can help in this.

**Comment by benjagm** [comment]
@DhairyaMajmudar thanks! This is the branch I asked everyone involved to work in:

https://github.com/json-schema-org/website/tree/web-dark-theme

**Comment by benjagm** [comment]
Hi @satyam-x10. We have almost all the changes in the branch [web-dark-theme](https://github.com/json-schema-org/website/tree/web-dark-theme). Are you working in the elements highlighted by Agnivesh?

**Comment by satyam-x10** [comment]
> Hi @satyam-x10. We have almost all the changes in the branch [web-dark-theme](https://github.com/json-schema-org/website/tree/web-dark-theme). Are you working in the elements highlighted by Agnivesh?

Yes.. I am

**Comment by satyam-x10** [comment]
> Hi [@satyam-x10](https://github.com/satyam-x10). We have almost all the changes in the branch [web-dark-theme](https://github.com/json-schema-org/website/tree/web-dark-theme). Are you working in the elements highlighted by Agnivesh?

Yes , I am working on it. Will push it asap

**Comment by satyam-x10** [comment]
@benjagm  i am working on  this issue from branch web-dark-theme . but things are little broken and not as shown in in the Screenshot by @AgniveshChaubey  . I cant see any tabs

![Image](https://github.com/json-schema-org/website/assets/106728045/e504ffa8-147b-4009-8134-c713183d531e)

**Comment by benjagm** [comment]
The only pending fix to be done is the behavior of the sidebar icons.
![312463208-bd0ef629-07c4-43fb-aee4-fa2e702ce803](https://github.com/json-schema-org/website/assets/40007659/d98d907d-9471-49c3-9198-3bbde21f9980)

This is apparently because for any reason the variable `theme` is undefined in Sidebar.tsx when is evaluated to switch the icons. 

The tabs are fixed.
<img width="905" alt="Screenshot 2024-03-16 at 00 51 25" src="https://github.com/json-schema-org/website/assets/40007659/c4d74c3f-fa3f-497d-94e0-7abeed845719">

**Comment by satyam-x10** [comment]
> The only pending fix to be done is the behavior of the sidebar icons.
> ![312463208-bd0ef629-07c4-43fb-aee4-fa2e702ce803](https://github.com/json-schema-org/website/assets/40007659/d98d907d-9471-49c3-9198-3bbde21f9980)
> 
> This is apparently because for any reason the variable `theme` is undefined in Sidebar.tsx when is evaluated to switch the icons. 
> 
> The tabs are fixed.
> <img width="905" alt="Screenshot 2024-03-16 at 00 51 25" src="https://github.com/json-schema-org/website/assets/40007659/c4d74c3f-fa3f-497d-94e0-7abeed845719">
> 

Got it . Thanks

**Comment by benjagm** [comment]
@satyam-x10 My gut tells me that this is probably because we are not making proper use of the `setTheme` feature so the library is unclear depending on the context. Can you please take a look to this example:
https://github.com/broomva/arcan/blob/a2019f23f9efbc112cf994395d27eff2aaf811a3/src/components/theme-toggle.tsx#L10

I think we'll benefit of a dedicated toggle component like them.

**Comment by satyam-x10** [comment]
the systemTheme variable is not working as  expected. when page loads at first systemTheme  is undefined. and then its sticking to the first value of theme . 

![Image](https://github.com/json-schema-org/website/assets/106728045/40f06c62-fad0-46b6-a05c-5338e255bbe4)

**Comment by benjagm** [comment]
Closed as completed.

**Comment by officeneerajsaini** [comment]
Close icon  not visible in dark mode it should be visible.
![Screenshot_2024-03-18-09-54-18-242_com android chrome](https://github.com/json-schema-org/website/assets/118799941/904ae591-b957-40a9-99bf-0e7e7c950c69)
![Screenshot_2024-03-18-09-54-35-943_com android chrome](https://github.com/json-schema-org/website/assets/118799941/9ae12f1a-c5d7-4751-96a9-340f83d4af61)

**Comment by Adity20** [comment]
Hello @benjagm I can help with this one 

> Close icon not visible in dark mode it should be visible. ![Screenshot_2024-03-18-09-54-18-242_com android chrome](https://private-user-images.githubusercontent.com/118799941/313549773-904ae591-b957-40a9-99bf-0e7e7c950c69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MzY0NjQsIm5iZiI6MTcxMDczNjE2NCwicGF0aCI6Ii8xMTg3OTk5NDEvMzEzNTQ5NzczLTkwNGFlNTkxLWI5NTctNDBhOS05OWJmLTBlN2U3Yzk1MGM2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQwNDI5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYTA1ZjkzNTE2NWI5NzY5NDA0ZGE2ZGQxMThmYzIwMDZkMjQ3MTUyMjhkYTQ4MDZiZWU1MTlmNGVhMGQ4YmJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HIYdWJKtkwCXYSGBJADCD9aUDXF8UIevOo2_R6rdoEY) ![Screenshot_2024-03-18-09-54-35-943_com android chrome](https://private-user-images.githubusercontent.com/118799941/313549784-9ae12f1a-c5d7-4751-96a9-340f83d4af61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MzY0NjQsIm5iZiI6MTcxMDczNjE2NCwicGF0aCI6Ii8xMTg3OTk5NDEvMzEzNTQ5Nzg0LTlhZTEyZjFhLWM1ZDctNDc1MS05NmE5LTM0MGY4M2Q0YWY2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQwNDI5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2ZmMTM2NDUwYTYzYjU1NDRiMGE1YjQ4N2UxN2U2MzkzYjk4MDIxMGRiODNlOGUzZGQ5NmYxMTIzMTc1YWY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xIMhRFKYDliVUgI-pJ2fa8NWAvf4QqKF7i22gaEu_To)

**Comment by officeneerajsaini** [comment]
This issue already open #553

**Comment by benjagm** [comment]
@officeneerajsaini please open a new issue for this. Thanks

**Comment by VivekJaiswal18** [comment]
@benjagm a new issue is already opened #553 please have a look thank you
