### ISSUE TITLE
🐛 Bug: Sponsor logos are not optimized for dark mode

### ISSUE THREAD

**Issue by mwadams** [json-schema-org/website#524]
### Describe the bug

Sponsor logos are (mostly) optimized for a light background [and likely have brand use guidelines prohibiting their use against low-contrast backgrounds].

They therefore (mainly) appear indistinct in dark mode.

### Steps To Reproduce

Navigate to homepage.
Scroll to sponsors.

### Expected Behavior

The background against which sponsor logos are overlaid is suitable for the readability of the logos and conforms to their brand usage guidelines.

### Screenshots

![image](https://github.com/json-schema-org/website/assets/347194/aef5a30c-1927-45bd-9634-4657517243d4)

### Device Information [optional]

```markdown
- OS: Windows 11
- Browser:Edge / Chrome
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by benjagm** [comment]
Thanks Matthew! We'll work in it.

**Comment by satyam-x10** [comment]
@benjagm  If this issue is still idle , i would be happy to work on it.  Thanks

**Comment by satyam-x10** [comment]
> Please use this branch as master branch: https://github.com/json-schema-org/website/tree/web-dark-theme

Sure.. Thanks

**Comment by satyam-x10** [comment]
@benjagm i have implemented gradient to fix this issue. Kindly review it when possible and let me have your feedback. Thanks

**Comment by benjagm** [comment]
Closed as completed.
