### ISSUE TITLE
🐛 Bug: Unexpected behaviour when clicking in the search button

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#525]
### Describe the bug

When clicking in the search button we found that the header content is slightly moving to the right when the search box is shown.  See video

https://github.com/json-schema-org/website/assets/40007659/d3dfef40-d3bd-4637-99c7-63b49e140a69

### Steps To Reproduce

When clicking in the search button we found that the header content is slightly moving to the right when the search box is shown. 

### Expected Behavior

No movement of the search button.

### Screenshots

See video un the opening comment.

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by satyam-x10** [comment]
@benjagm This looks odd. I would be happy to work on this . Thanks

**Comment by Adity20** [comment]
Can I work on this one @benjagm

**Comment by benjagm** [comment]
Thanks everyone! @Adity20 please go ahead.

**Comment by benjagm** [comment]
Please use this branch as master branch: https://github.com/json-schema-org/website/tree/web-dark-theme

**Comment by Adity20** [comment]
Done @benjagm  kindly review PR #544
