### ISSUE TITLE
🐛 Bug: After deploying the dark theme we have lost changes done in #375

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#526]
### Describe the bug

We have lost changes done in https://github.com/json-schema-org/website/issues/375

### Steps To Reproduce

Check the footer.

### Expected Behavior

We need to bring back the footer merged in https://github.com/json-schema-org/website/issues/375

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by benjagm** [comment]
Thanks @Sahil-Shadwal. Please go ahead.

**Comment by benjagm** [comment]
Please use this branch as master branch: https://github.com/json-schema-org/website/tree/web-dark-theme

**Comment by Sahil-Shadwal** [comment]
yeah sure

**Comment by officeneerajsaini** [comment]
@benjagm i think you assigned this issue to @DhairyaMajmudar .

**Comment by benjagm** [comment]
> @benjagm i think you assigned this issue to @DhairyaMajmudar .

Not exactly but thanks for the heads up. @Sahil-Shadwal please hold on. @DhairyaMajmudar will look for this and any other change we have lost. Do you mind if I assign this to him too?

**Comment by Sahil-Shadwal** [comment]
i kinda solved it

**Comment by benjagm** [comment]
Please open the PR! Thanks!

That was kick!

**Comment by benjagm** [comment]
Closed as completed.
