### ISSUE TITLE
🐛 Bug: Getting the lost changes from the merger of dark theme pr.

### ISSUE THREAD

**Issue by DhairyaMajmudar** [json-schema-org/website#528]
### Describe the bug

After merging the dark theme PR #365 several changes previous done are now lost which should be recovered.

As of now the dark them is rolled back from the production in is placed in the new branch `web-dark-theme` , this branch needs to be compared with the `main` ( production branch ) to revoer the changes back.

### Steps To Reproduce

N/A

### Expected Behavior

The previous changes should be recovered while also implementing back the dark theme.

### Screenshots

N/A

### Device Information [optional]

```markdown
- OS: Linux (Debian)
- Browser: Firefox
- version: latest
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by DhairyaMajmudar** [comment]
Referencing the [comment](https://github.com/json-schema-org/website/issues/523#issuecomment-1994460401) from the issue.

**Comment by VivekJaiswal18** [comment]
Hey @DhairyaMajmudar I also want to help recover the lost changes back. How about working on this together

**Comment by DhairyaMajmudar** [comment]
> Hey @DhairyaMajmudar I also want to help recover the lost changes back. How about working on this together?

Thanka Vivek for the help but I am about to complete this : )

**Comment by benjagm** [comment]
Closed as completed. Thanks Dhairya!
