### ISSUE TITLE
🐛 Bug: Sponsor Logos Not Updating in DARK MODE

### ISSUE THREAD

**Issue by Sahil-Shadwal** [json-schema-org/website#531]
### Describe the bug

I've noticed an inconsistency with the recently introduced dark mode on the website. Specifically, in the Sponsors section, the sponsor logos are not changing their appearance to match the dark theme.

### Steps To Reproduce

Switch from light mode to dark mode

### Expected Behavior

When a user switches to dark mode, all website elements, including sponsor logos, should adjust their colors or styles to be displayed appropriately within the dark theme. This would likely involve logos switching to a lighter version or one with an inverted color scheme to maintain visibility and contrast within the dark background.

### Screenshots

![image](https://github.com/json-schema-org/website/assets/119167601/4be084ec-22d4-4dd7-aa03-21c57c906663)

[Screencast from 2024-03-13 21-12-53.webm](https://github.com/json-schema-org/website/assets/119167601/a430ff63-c34c-42d9-8013-6354fc62700c)

### Device Information [optional]

```markdown
- OS: Fedora-Linux
- Browser: Chrome
- version: Version 122.0.6261.111 (Official Build) (64-bit)
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by benjagm** [comment]
Duplicated with #532
