### ISSUE TITLE
🐛 Bug: Fix spacing in icon buttons of the header

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#535]
### Describe the bug

The new header in the dark theme includes an button for search and another for switch dark theme but the spacing needs extra work for both desktop and mobile.

**Desktop:**
<img width="967" alt="Screenshot 2024-03-13 at 17 45 42" src="https://github.com/json-schema-org/website/assets/40007659/79db46d6-c630-4608-a077-7cb81da7f6e3">

**Mobile:**
<img width="356" alt="Screenshot 2024-03-13 at 17 45 48" src="https://github.com/json-schema-org/website/assets/40007659/843b8882-66f6-4dd2-b0e0-5e1e0c2cd356">

### Steps To Reproduce

Just open the json schema website.

### Expected Behavior

optimal spacing.

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by Akshaybagai52** [comment]
Hello @benjagm 
can I work on this issue

**Comment by VivekJaiswal18** [comment]
@benjagm  Can you eleborate what needs to be done here. As when I checked it was looking ok

**Comment by benjagm** [comment]
This issue is on hold to be fixed when we have back the dark theme feature

**Comment by satyam-x10** [comment]
@benjagm can i work on this one. Thanks

**Comment by AjayAsnani** [comment]
Hey @benjagm Can you assign this issue to me

**Comment by benjagm** [comment]
@Akshaybagai52 please go ahead with this issue.

**Comment by Akshaybagai52** [comment]
> @Akshaybagai52 please go ahead with this issue.

This is the PR https://github.com/json-schema-org/website/pull/575

**Comment by benjagm** [comment]
Closed as completed.
