### ISSUE TITLE
✨ Enhancement: Top Navbar should close when user clicks anywhere on the screen 

### ISSUE THREAD

**Issue by VivekJaiswal18** [json-schema-org/website#536]
### Is your feature request related to a problem? Please describe

User should be able to close the top navbar by not only clicking on the cross button but also by tapping anywhere outside the top navbar.
This will make it more ergonomic for the mobile users.

https://github.com/json-schema-org/website/assets/96608169/9126bd13-be5f-43ff-80aa-42d3c5c3f035

### Describe the solution you'd like

This can be solved in various ways like using hooks, etc

### Are you working on this?

Yes

**Comment by VivekJaiswal18** [comment]
@benjagm please have a look. I want to work on this.
Thank you

**Comment by AdityaSingh-02** [comment]
Heyy @benjagm Can you please assign me this issue?

**Comment by lalitkumawat1m** [comment]
Hey @benjagm, I want to work on this issue?

**Comment by benjagm** [comment]
@lalitkumawat1m please go ahead with this issue. Thanks @VivekJaiswal18 !!
