### ISSUE TITLE
✨ Enhancement: Specification links in sidebar should move upper

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#541]
### Is your feature request related to a problem? Please describe

The current position of the Specification Links menu item at the bottom of the sidebar is not ideal.
![Screenshot 2024-03-14 at 18 37 24](https://github.com/json-schema-org/website/assets/40007659/12ff9818-cc5c-4001-8a19-1d949f11217b)

The ideal position is below overview.

### Describe the solution you'd like

The ideal position is below overview.

### Are you working on this?

No

**Comment by ayushtiwari110** [comment]
Hey there! Can I take this issue?

**Comment by Adity20** [comment]
Shall I take this up @benjagm ?

**Comment by Sahil-Shadwal** [comment]
assign me if its available , thank you :)

**Comment by AdityaSingh-02** [comment]
Heyy @benjagm Please assign me this issue 🚀

**Comment by crampussm** [comment]
Heyy @benjagm please assign me this issue

**Comment by lalitkumawat1m** [comment]
Hey @benjagm, can I take this?
