### ISSUE TITLE
✨ Enhancement: Online Playground/Evaluator for testing scenarios and increasing learning of JSON Schema

### ISSUE THREAD

**Issue by nkcmr** [json-schema-org/website#546]
### Is your feature request related to a problem? Please describe

No. This is a pure enhancement idea.

### Describe the solution you'd like

In order to increase usage of JSON Schema and understanding, the main website should have some area where visitors can make schemas and test out certain scenarios in order to increase understanding. I am a hands-on learner, so I enjoy getting to start messing with something to learn it.

Another use-case is sharing snippets: If you do know JSON schema quite will and are trying to convey some scenario, being able to whip up an example and send it to some one else so they can see would increase understanding. Much like Golang's playground where you can share snippets.

### Describe alternatives you've considered

I have done web searches for something like this and there were none that were good enough. Since the main website is there to help folks learn, this seems like a valuable addition to the website to help people learn and then _test_ their understanding with a small editor.

### Are you working on this?

No

**Comment by lalitkumawat1m** [comment]
I would like to work on this issue?

**Comment by benjagm** [comment]
Thanks @nkcmr !! All of that sounds great. Scenario 1, yes. We are planing to rebuild the getting started journey and my plan is to do exactly that. Provide an editor. In addition, as plan as Google Summer of code we have this project idea https://github.com/json-schema-org/community/issues/645 that will provide a learning experience similar than 
 A tour of Go: https://go.dev/tour/welcome/1. 
 
 Regarding scenario 2: Can you please share the link to the golang playground?

**Comment by radhesh1** [comment]
> Regarding scenario 2: Can you please share the link to the golang playground?
https://go.dev/play/
