### ISSUE TITLE
✨ Enhancement: Rebuild the getting started guide

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#549]
### Is your feature request related to a problem? Please describe

We are aware that learning JSON Schema is not easy and we also know that our docs needs a lot of improvement. But now, with the new feedback component we are even more clear about the areas that needs improvement and the getting started guide is clearly one of them.

After long consideration, I think the best approach is proceeding with a first iteration consisting on changing the section [Validating JSON data against the schema](https://json-schema.org/learn/getting-started-step-by-step#validate).

We don't maintain or promote any validator over others and in addition we are not integrating any validator. This is great to keep our neutrality but it adds friction into new users journey. We are going to keep that neutrality but it will be great to allow the users feel the HAHA moment of getting a json message validated against a schema.

My proposal is to create a component that provides different valid and invalid examples for different uses cases following this prototype:

<img width="380" alt="Screenshot 2024-04-18 at 15 51 05" src="https://github.com/json-schema-org/website/assets/40007659/a8fa4a73-5900-4fe0-9c76-d996da1bf8a7">

The default example shown by the component is the one used for getting started. Considering that the examples are pre-recorded and we know the validation result. 

1. Initially the component shows the default schema instance.  (this will be paremetrized in a yaml file)
2. The user can select 2 or 3 different instances, valid and invalid and we show the result and the explanation why showing a green check when is valid and red cross when is invalid.
3. We'll provide some other schema examples with instances so the users can see it working in different scenarios. We add simple and other more complex examples.
4. We provide a download button to allow to download the schema and the selected instance so the user can try it with the validator of their choice.

The idea is let the users see the power of the json schema validation and show other real life examples to inspire them.

**Comment by benjagm** [comment]
Some examples: 
 * https://docs.astro.build/en/getting-started/
 * https://docs.github.com/en/get-started
 * https://gohugo.io/getting-started/quick-start/

**Comment by VivekJaiswal18** [comment]
Hello @benjagm, can I help you with this in any way.

**Comment by benjagm** [comment]
Thanks Vivek. I still need to find some time to create a prototype with what I have in mind.

**Comment by crampussm** [comment]
Hey @benjagm can I work on this?

**Comment by benjagm** [comment]
> Hey @benjagm can I work on this?

My apologies for the late response. I think @DhairyaMajmudar is working on this. Isn't it?

**Comment by DhairyaMajmudar** [comment]
Yes I am currently working on this.
