### ISSUE TITLE
🐛 Bug: Navbar in shifts while toggling theme.

### ISSUE THREAD

**Issue by DhairyaMajmudar** [json-schema-org/website#552]
### Describe the bug

Navbar UI shifts when the button for toggling is pressed.

### Steps To Reproduce

1. Checkout to `web-dark-theme` branch  
2. Click on the theme toggle button. 

### Expected Behavior

Navbar ui should not shift while changing the theme.

### Screenshots

[Screencast from 2024-03-17 23-31-27.webm](https://github.com/json-schema-org/website/assets/124715224/99d2954e-5944-4d5c-88c0-bae43cfa18b2)

### Device Information [optional]

```markdown
- OS: Linux (Debian)
- Browser: Firefox 
- version: Latest
```

**Comment by Adity20** [comment]
If this looks valid to you @benjagm I would love to work on this one :)

**Comment by benjagm** [comment]
Thanks. All yours @Adity20
