### ISSUE TITLE
🐛 Bug: In dark theme Menu button gets invisible when clicked

### ISSUE THREAD

**Issue by VivekJaiswal18** [json-schema-org/website#553]
### Describe the bug

In mobile view the menu close button gets invisible but working.

### Steps To Reproduce

1. Checkout mobile view
2. Tap on menu option

### Expected Behavior

It should be visible

### Screenshots

https://github.com/json-schema-org/website/assets/96608169/0f065db7-722e-4d59-bb49-ae214508a0d1

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

Yes

**Comment by VivekJaiswal18** [comment]
Hey @benjagm if you approve this issue I want to work on this issue.
Thank you

**Comment by Adity20** [comment]
Can I work on this one @benjagm

**Comment by benjagm** [comment]
Fixed. Thanks everyone
