### ISSUE TITLE
🐛 Bug: Search button in hero page should be fully clickable

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#556]
### Describe the bug

In the search button of the hero page only the lens icon is clickable. 

<img width="187" alt="Screenshot 2024-03-18 at 08 16 18" src="https://github.com/json-schema-org/website/assets/40007659/9be0f84a-fd8e-44de-93e9-87012b1c2be1">

### Steps To Reproduce

Access the landing page and move hover the button outside the icon area.

### Expected Behavior

Expected behaviour is the full button being clickable.

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by benjagm** [comment]
Go ahead @VivekJaiswal18 thanks!

**Comment by benjagm** [comment]
Hi @VivekJaiswal18. Still working on this issue?

**Comment by Adity20** [comment]
I can help on this one @benjagm

**Comment by benjagm** [comment]
@Adity20 please go ahead
