### ISSUE TITLE
✨ Enhancement: Modify the response of the feedback form

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#561]
### Is your feature request related to a problem? Please describe

As of now we are sharing a generic response with the people that send us feedback in the DocsHelp component. However we'd like to improve it.

<img width="568" alt="Screenshot 2024-03-18 at 19 10 33" src="https://github.com/json-schema-org/website/assets/40007659/3011fc86-b41d-458c-972d-bda77b3405e7">

### Describe the solution you'd like

A better response will be:

Thanks for your feedback! It will be published in the `#website` channel of our [Slack](https://json-schema.org/slack) workspace. Please join us there to continue the discussion!

If it is too long let's improve it!

### Are you working on this?

No

**Comment by Sahil-Shadwal** [comment]
I would like to work on this . Thanks:)

**Comment by Sahil-Shadwal** [comment]
hey @benjagm take a look at this
![image](https://github.com/json-schema-org/website/assets/119167601/541466a2-7616-49b0-8664-d97dfe87502b)

Alternatives:-
1. Thanks for your feedback! It will be shared on #website in Slack.
2. Thanks for your feedback! Share your thoughts on #website in Slack.

Which one should i go with, i would prefer 
![Screenshot from 2024-03-20 23-48-26](https://github.com/json-schema-org/website/assets/119167601/6036fdb2-9549-4290-a0f5-7b8b72e6ed73)
cause this focuses on both sharing and discussion.

**Comment by Sahil-Shadwal** [comment]
Made a PR with 
`Thanks for the feedback! See it on [#website](https://json-schema.slack.com/archives/C8C4UBXDF) in [Slack ](https://json-schema.org/slack)for further discussion.`
What you suggested was too long , will immediately change it if you don't like my suggestion. Sorry for going out of the way.
