### ISSUE TITLE
🐛 Bug: [Edge Case] The mobile nav bar does not disappear when we change the browser width 

### ISSUE THREAD

**Issue by JeelRajodiya** [json-schema-org/website#562]
### Describe the bug
The mobile nav bar does not disappear when we change the browser width

### Steps To Reproduce

1. open the website 
2. set the width of your browser similar to a mobile device 
3. open nav bar 
4. now while keeping it open, increase the width of the browser 
5. Now you will have two navbars 

![image](https://github.com/json-schema-org/website/assets/63534268/366c8a90-1edb-47d8-8622-34b928c1c930)

### Expected Behavior

The mobile navbar should disappear when we switch back to desktop 

### Screenshots

https://github.com/json-schema-org/website/assets/63534268/8ce5058e-437e-48f1-a8d4-5e866263a0d6

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?
Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by JeelRajodiya** [comment]
**Benjamin**, I like to work on the issue

**Comment by AdityaSingh-02** [comment]
@benjagm Can I please take this??

**Comment by maverox** [comment]
@benjagm I would like to work on this

**Comment by benjagm** [comment]
Go ahead @JeelRajodiya. Thanks
