### ISSUE TITLE
Minor bug on Docs page

### ISSUE THREAD

**Issue by handealptekin** [json-schema-org/website#564]
https://json-schema.org/understanding-json-schema/reference/combining page has "A snippet of the British royal family tree" written 2 times by mistake while giving examples to subschemas.

**Comment by DarhkVoyd** [comment]
The two instances in `pages/understanding-json-schema/reference/combining.md`, seems to originate from the example about the same in `pages/understanding-json-schema/structuring.md`. It dates back to [this](https://github.com/json-schema-org/website/commit/fdb0b2b5de7d66898c20d0503642c63ba56ee0b1) commit. Probably, it was mistakenly copied when parts of structuring were migrated to combining.

**Comment by maverox** [comment]
I can resolve this.

**Comment by benjagm** [comment]
Thanks everyone. @maverox go ahead.
