### ISSUE TITLE
✨ Enhancement: Dark mode for the search popup 

### ISSUE THREAD

**Issue by JeelRajodiya** [json-schema-org/website#569]
### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

Add dark mode for search popup 

![output](https://github.com/json-schema-org/website/assets/63534268/607bac65-7984-47f7-87c0-f9804adc0c20)

### Are you working on this?

No

**Comment by JeelRajodiya** [comment]
**Benjamin** I like to work on this issue.

**Comment by VivekJaiswal18** [comment]
I was going to raise this same issue now. :)
@benjagm Can i take this up issue

**Comment by AdityaSingh-02** [comment]
Heyy @benjagm Can I work on this?

**Comment by crampussm** [comment]
Hey @benjagm can I take this one?

**Comment by lalitkumawat1m** [comment]
Hey @benjagm can I take this issue?
