### ISSUE TITLE
✨ Enhancement: Improve the design of TableOfContent custom tag.

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#571]
### Is your feature request related to a problem? Please describe

We have a certain number of custom tags that can be used in markdown to enhance the resulting webpage. Most of them are actually documented here: https://json-schema.org/md-style-guide

One of the tags is TableOfContent. This tag generates a table of contents, however the resulting design needs improvement. See: https://json-schema.org/specification-links

<img width="709" alt="Screenshot 2024-03-21 at 09 51 15" src="https://github.com/json-schema-org/website/assets/40007659/931fadd8-741b-4252-8db1-e47b8f5f4d6a">

### Describe the solution you'd like

The resolution of this issue implies:

- Add the documentation of how to use the TableOfContent tag into the guide: https://json-schema.org/md-style-guide
- Enhance the resulting html code to make the resulting table of contents look great in light and dark theme.

### Are you working on this?

No

**Comment by its-VinayKumar** [comment]
@benjagm Plz assign me this issue.

**Comment by benjagm** [comment]
@its-VinayKumar please go ahead.

**Comment by vinfinity7** [comment]
@its-VinayKumar must be busy with a lot of issues , mind if i take over on thisone @benjagm ?

**Comment by its-VinayKumar** [comment]
@vinfinity7 if member assign the issue. Please don't ask again. :)

**Comment by vinfinity7** [comment]
Yes @its-VinayKumar  , no offence , I was just concerned about the completion of the issue s , nothing else ! Go on and ping me if you need any help ;)

**Comment by benjagm** [comment]
@vinfinity7 still interested on this issue?

**Comment by Adity20** [comment]
I am interested @benjagm

**Comment by vinfinity7** [comment]
@benjagm I am ready to pick this up

**Comment by benjagm** [comment]
Go ahead @vinfinity7 !

**Comment by vinfinity7** [comment]
@benjagm how do you wish the new design to be like ?

**Comment by vinfinity7** [comment]
@benjagm I am thinking maybe we can add borders to each peice and display hierarchy in a more clear way ?

**Comment by benjagm** [comment]
Feel free to be creative.

**Comment by vinfinity7** [comment]
@benjagm So i  will proceed with underlines and bulleting

**Comment by benjagm** [comment]
> i will proceed with bulleting because boxes

What about this symbol ▷

**Comment by vinfinity7** [comment]
ohk Ill get that done

**Comment by vinfinity7** [comment]
![image](https://github.com/json-schema-org/website/assets/122719607/f8b160bf-51e5-4b38-908a-7bb08989cca7)
@benjagm  This is how it looks like

**Comment by benjagm** [comment]
That does not like great too. We are not improving.

What about this something inspired in this example: https://www.youtube.com/watch?app=desktop&v=VnGOsLoI5MY

**Comment by radhesh1** [comment]
that looks better

**Comment by radhesh1** [comment]
Could we Maybe have the Size of the titles to be Different?

**Comment by vinfinity7** [comment]
yes @benjagm, the arrow signs weren't adding what was needed, I'll head to the YouTube video idea and finish the work by the night 👍

**Comment by radhesh1** [comment]
@vinfinity7 could we collaborate on this?

**Comment by vinfinity7** [comment]
@radhesh1 we can collaborate surely but this issue doesn't need 2 people spending their time on this tbh , since We have the design to be implemented , Yes if we had to brainstorm the design ideas , you were more than welcome to collab .

**Comment by vinfinity7** [comment]
![image](https://github.com/json-schema-org/website/assets/122719607/3bca98f0-e0e8-4b2c-b744-6b52d26d7a69)
@benjagm Hows this ?

**Comment by vinfinity7** [comment]
So @benjagm  , I have made a PR and we can amend any changes on to that to streamline the process

**Comment by benjagm** [comment]
This issue is now available for other contributors.
