### ISSUE TITLE
✨ Enhancement: Invert the order of the links table

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#572]
### Is your feature request related to a problem? Please describe

The [Specification links page](https://json-schema.org/specification-links) is important because it shows the current JSON Schema drafts. As of now we are showing the table with each release sorted from oldest to newest and we'd like to invert that order so we start with the newest.

See:
<img width="680" alt="Screenshot 2024-03-21 at 09 54 24" src="https://github.com/json-schema-org/website/assets/40007659/419e5f7a-460b-466d-9244-692d46cd2bdb">

### Describe the solution you'd like

The solution to this issue will imply:

- Invert the order of the table.
- Add a new column called "Published" with release date (available in this same page) 
- Change the columns order to go this way: Common Name, Published, meta-schema identifiers, Metaschemas and notes

### Are you working on this?

No

**Comment by its-VinayKumar** [comment]
@benjagm Plz assign me this issue. I want to work on this. :)

**Comment by benjagm** [comment]
Go ahead @its-VinayKumar

**Comment by vinfinity7** [comment]
@benjagm Hi , can i get this assigned  to me ?

**Comment by vinfinity7** [comment]
@its-VinayKumar , feeling any issues ? I am up for the help and maybe we can collab for this one ?

**Comment by its-VinayKumar** [comment]
@benjagm Please have a look on this, I will make PR ASAP :)
![Screenshot (215)](https://github.com/json-schema-org/website/assets/129538020/333fd910-a4f5-49d8-bb11-e51fa241ee10)
![Screenshot (217)](https://github.com/json-schema-org/website/assets/129538020/aeca58c9-a6a0-4d06-ae61-db9f4a636aef)

**Comment by benjagm** [comment]
Are you still working on this @its-VinayKumar ?

**Comment by JeelRajodiya** [comment]
Can I please work on this?

**Comment by benjagm** [comment]
Thanks Jeel. Please go ahead!

**Comment by JeelRajodiya** [comment]
> The solution to this issue will imply:
> - Invert the order of the table.
> - Add a new column called "Published" with release date (available in this same page)
> - Change the columns order to go this way: Common Name, Published, meta-schema identifiers, Metaschemas and notes

@benjagm, Regarding the third point in the [issue description](https://github.com/json-schema-org/website/issues/572#issue-2199570772), it appears that there's no mention of the IETF identifiers column. Would it be appropriate to consider removing the IETF identifiers column?
