### ISSUE TITLE
🐛 Bug: Website's Copyright is not mentioned within the Footer Section.

### ISSUE THREAD

**Issue by its-VinayKumar** [json-schema-org/website#573]
### Describe the bug

* In the Footer section Copyright is missing.
* Copyright should be included in a website.

### Steps To Reproduce

1. Go to 'Website'.
2. Scroll down 'Footer Section'.
3. See error.

### Expected Behavior

![json schema](https://github.com/json-schema-org/website/assets/129538020/c20e0a9c-fe69-488e-b6db-398f03b263b8)

### Screenshots

Screenshot displays how copyright may be included to a website's footer section.

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

Yes

**Comment by benjagm** [comment]
Good proposal. Let use white fonts like the rest of the texts in the footer.

**Comment by its-VinayKumar** [comment]
@benjagm Thanks. :)

**Comment by its-VinayKumar** [comment]
![json copyright](https://github.com/json-schema-org/website/assets/129538020/2e6e84f6-9b36-4a0d-a7f8-083bab8c2546)
@benjagm Please have look on this.

**Comment by benjagm** [comment]
Please use "All right reserved." Instead of "All Right Reserved". Using lowercase and final point.

**Comment by its-VinayKumar** [comment]
![copyright](https://github.com/json-schema-org/website/assets/129538020/a0c4f08c-99e2-436c-89ff-6fd1db60448f)
@benjagm Please look on this, So I will make PR soon. :)

**Comment by its-VinayKumar** [comment]
@benjagm I have made the changes. Please review and merge my PR of this issue.

**Comment by its-VinayKumar** [comment]
@benjagm I made the updated PR of this issue. Please review on it. :)
