### ISSUE TITLE
✨ Enhancement: Add Dark mode in mobile docs sidebar 

### ISSUE THREAD

**Issue by JeelRajodiya** [json-schema-org/website#583]
### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

Add dark mode for the docs mobile sidebar 

![image](https://github.com/json-schema-org/website/assets/63534268/04e33926-209c-408f-b804-9b077a2bbf5c)

### Are you working on this?

Yes

**Comment by JeelRajodiya** [comment]
**Benjamin**, I would like to work on this issue.

**Comment by VivekJaiswal18** [comment]
Just realized I also created the same issue

**Comment by rajanraj2** [comment]
Can I work on this one @benjagm ?

**Comment by crampussm** [comment]
@benjagm can I take this one?

**Comment by JeelRajodiya** [comment]
Closing this, as issue #584 is similar to current issue
