### ISSUE TITLE
🐛 Bug:  Dark mode not consistent

### ISSUE THREAD

**Issue by VivekJaiswal18** [json-schema-org/website#584]
### Describe the bug

![image](https://github.com/json-schema-org/website/assets/96608169/579903cb-7e34-4641-ab60-abfc33ed21f1)

### Steps To Reproduce

In mobile view sidebar navigation is not getting the dark mode

### Expected Behavior

It should get the dark mode
When working on the use cases page I noticed that when in mobile view it is showing background white

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

Yes

**Comment by Adity20** [comment]
@JeelRajodiya has already opened an issue for the same.

**Comment by VivekJaiswal18** [comment]
yes just saw that, I am okay with him taking it or me

**Comment by VivekJaiswal18** [comment]
maybe I should close this

**Comment by JeelRajodiya** [comment]
> maybe should I close this issue

Sure!

**Comment by JeelRajodiya** [comment]
> maybe should I close this issue
Keep it open, I have closed that issue

**Comment by VivekJaiswal18** [comment]
> Keep it open, I have closed that issue
Okay

**Comment by benjagm** [comment]
In what scenario is this happening?

**Comment by VivekJaiswal18** [comment]
In mobile view when we toggle dark mode and check the sidebar it is showing the background as white

**Comment by JeelRajodiya** [comment]
>In what scenario is this happening?
![input](https://github.com/json-schema-org/website/assets/63534268/f54ca3da-a84c-45ae-abd1-c404a245879a)

**Comment by benjagm** [comment]
Ok. Thanks. Issue accepted.

**Comment by Adity20** [comment]
Can I work on it @benjagm ?

**Comment by AdityaSingh-02** [comment]
Can I work on it @benjagm

**Comment by Michael-Obele** [comment]
Hey everyone, it looks like @VivekJaiswal18 is already on top of this!

**Comment by benjagm** [comment]
@AdityaSingh-02 still interested on this issue?

**Comment by DhairyaMajmudar** [comment]
Shall I take this up : )

**Comment by benjagm** [comment]
Thanks Dhairya. Please go ahead.
