### ISSUE TITLE
🐛 Bug: Overflow in Sidenavbar 

### ISSUE THREAD

**Issue by VivekJaiswal18** [json-schema-org/website#585]
### Describe the bug

The content inside the sidebar is overflowing on the main screen

### Steps To Reproduce

Go to mobile view and scroll to last option

### Expected Behavior

It must not overflow

### Screenshots

https://github.com/json-schema-org/website/assets/96608169/ea4ea19e-0336-41d8-ac2e-accb4ab94479

https://github.com/json-schema-org/website/assets/96608169/b1593354-0de7-44cb-a48f-19101c2dca8f

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

Yes

**Comment by benjagm** [comment]
I don't think that is an overflow. There is no scroll. As per the figma design I think that was intentional.

<img width="456" alt="Screenshot 2024-03-24 at 10 32 46" src="https://github.com/json-schema-org/website/assets/40007659/2f625eac-c164-4cbb-aede-7a39c9a112b1">

**Comment by VivekJaiswal18** [comment]
@benjagm when checking in mobile view open some option that has long list of subtopics it overflows from the specified background.

https://github.com/json-schema-org/website/assets/96608169/7e69cce1-5410-46fe-aacb-5d1e4cd56e12
