### ISSUE TITLE
🐛 Bug: Overflow of text in validators on Obsolete Implementations Page.

### ISSUE THREAD

**Issue by TamannaVerma99** [json-schema-org/website#586]
### Describe the bug

There is an overflow of text in validators on Obsolete Implementations page on reducing screen dimensions less than desktop view.

![image](https://github.com/json-schema-org/website/assets/96949249/3596bdbd-96c7-455d-b129-1f58285a0ce8)

### Steps To Reproduce

1.Go to [LINK](https://json-schema.org/)
2.Click on Obsolete Implementations .

### Expected Behavior

![image](https://github.com/json-schema-org/website/assets/96949249/52f40c85-c505-4605-9ea0-9fc6bc3b99ba)

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by TamannaVerma99** [comment]
Hey! @benjagm 
May I work on this issue .Thanks :)

**Comment by AdityaSingh-02** [comment]
heyy @benjagm Can I take this up? previously I have fixed a similar issue

**Comment by benjagm** [comment]
Please see this issue for implement a solution aligned: https://github.com/json-schema-org/website/issues/485

Go ahead Tamanna.
