### ISSUE TITLE
🐛 Bug: Dark mode not getting applied to Specification Links

### ISSUE THREAD

**Issue by vinfinity7** [json-schema-org/website#587]
### Describe the bug

![image](https://github.com/json-schema-org/website/assets/122719607/53afd972-e71b-423c-9ece-e3e9d0999f36)

### Steps To Reproduce

visit https://json-schema.org/specification-links , toggle light and dark mode to experience this !

### Expected Behavior

It should toggle its theme upon toggle of the light dark button

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by jayprakash25** [comment]
Can I resolve this?

**Comment by benjagm** [comment]
Thanks for filling this issue. We have 2 other issues affecting this page so I prefer to wait until those are closed before we start working on it.

Dependencies:

- #572 
- #571
