### ISSUE TITLE
✨ Enhancement: Add Multilingual Support for Docs and Website 

### ISSUE THREAD

**Issue by vinfinity7** [json-schema-org/website#591]
### Is your feature request related to a problem? Please describe

Implementing multilingual support is crucial for broadening the reach of the website to users from diverse regions worldwide. By incorporating this feature, the docs can cater to individuals who speak different languages, thereby enhancing accessibility and usability. This inclusivity fosters a more welcoming environment for users from various cultural backgrounds, facilitating their engagement with the content and functionality of the application. Moreover, multilingual support enables the application to effectively communicate with a broader audience, ultimately increasing its global impact and relevance.

### Describe the solution you'd like

There are indeed numerous libraries available, such as i18n and Polyglot, designed specifically to facilitate the implementation of multilingual support within applications. These libraries offer robust features for managing translations, language switching, and localization tasks. Integrating such libraries into the project will streamline the process of providing multilingual support, ensuring efficient handling of language-specific content and user interface elements. By leveraging these libraries, the application can effectively manage translations and accommodate diverse linguistic preferences, thereby enhancing its accessibility and usability for a global audience.

### Are you working on this?

Yes

**Comment by benjagm** [comment]
We are not planning to add multi-language support as of now. Thanks!
