### ISSUE TITLE
🐛 Bug: Table heading not visible in dark mode

### ISSUE THREAD

**Issue by VivekJaiswal18** [json-schema-org/website#592]
### Describe the bug

The heading is not visible in dark mode

### Steps To Reproduce

Go to https://json-schema.org/understanding-json-schema/reference/type
Turn on dark mode

### Expected Behavior

It must be visible

### Screenshots

https://github.com/json-schema-org/website/assets/96608169/c1244d5d-c2b2-4a6f-bf17-250ec8a252b3

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by VivekJaiswal18** [comment]
@benjagm can i take this issue

**Comment by benjagm** [comment]
Thanks Vivek. Please go ahead.
