### ISSUE TITLE
🐛 Bug: Community Section Design Improvement: Margin, Contrast & Button Placement

### ISSUE THREAD

**Issue by Sahil-Shadwal** [json-schema-org/website#599]
### Describe the bug

The current design of the community section lacks sufficient margin and padding around content, resulting in a cluttered look and reduced readability. Additionally, the soft-shadow has low contrast with the background, further impacting visual clarity. Furthermore, the misalignment of the "Join Slack" and "View Calendar" buttons creates a disjointed user experience.

### Steps To Reproduce

1. Go to https://json-schema.org/#community

### Expected Behavior

It should have proper margin and padding. The soft-shadow should have more contrast , we could use  a light color instead of using dark in dark. And buttons should also have some margin and padding to give it more elegant look.

### Screenshots

![Screenshot 2024-03-25 130412](https://github.com/json-schema-org/website/assets/119167601/b7d8772d-01fe-47ee-ba62-3dccd8fe038b)

### Device Information [optional]

```markdown
- OS: Windows
- Browser: Chrome
- version:
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by Sahil-Shadwal** [comment]
I would also like to suggest a dedicated community page for improved user experience and engagement .

**Comment by AdityaSingh-02** [comment]
@benjagm Can I take this?

**Comment by Akshaybagai52** [comment]
> Thanks Sahil! If you are actually working on it please go ahead, otherwise I'll assign it to Aditya

Hello
do I need to work with @Sahil-Shadwal on this issue?

**Comment by Sahil-Shadwal** [comment]
![image](https://github.com/json-schema-org/website/assets/119167601/b2cf7284-bfe9-4cc1-83c5-c5ee12c9f582)
Hey @benjagm , 
The empty space is not looking good in community and blog card. And after adding padding it is making it even longer than previous one. What should i do ?

**Comment by VivekJaiswal18** [comment]
@benjagm @Sahil-Shadwal  I would suggest there should be three equal size cards for the- slack workspace, schema blog and community events and meetings. And the upcoming events div to be placed somewhere below it, that will give the community section a clean look. I can also provide a prototype if you like this.

**Comment by Sahil-Shadwal** [comment]
@VivekJaiswal18 please go ahead with the prototype.

**Comment by benjagm** [comment]
If suggest avoid any type or shadow effect. Just adding the padding and leave the cards background the same than the page background

**Comment by Akshaybagai52** [comment]
> @VivekJaiswal18 please go ahead with the prototype.

Hey you can try removing box shadow 
![image](https://github.com/json-schema-org/website/assets/100753870/5d98251f-b753-465a-9d58-2f71e235d507)
in this it will look same as in light mode 
just remove dark:shadow-2xl from the three divs

**Comment by Sahil-Shadwal** [comment]
Yeah that would camouflage the borders and give it a subtle look.

**Comment by benjagm** [comment]
> removing box shadow

Exactly

**Comment by VivekJaiswal18** [comment]
yes shadow is not going well with it

**Comment by Sahil-Shadwal** [comment]
![image](https://github.com/json-schema-org/website/assets/119167601/b950284e-324a-47d2-ae1f-cc556b5df1a6)

its a good temporary solution !

**Comment by Akshaybagai52** [comment]
> ![image](https://private-user-images.githubusercontent.com/119167601/318217402-b950284e-324a-47d2-ae1f-cc556b5df1a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MjQ0MTUsIm5iZiI6MTcxMTgyNDExNSwicGF0aCI6Ii8xMTkxNjc2MDEvMzE4MjE3NDAyLWI5NTAyODRlLTMyNGEtNDdkMi1hZTFmLWNjNTU2YjVkZjFhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMFQxODQxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmI2N2Y2MmUyZmJiNDZhMDIxYzU2YWE2ZTI1ZGJhNWFiYjkzYTI1ZGYzYzBhNWY4ZjNmM2YxOTYzNmYwMWNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gFdVaWTkBHqaIopgslKQMOvO-ElssAu-Z0xFkD69DeM)
> 
> its a good temporary solution !

You can remove margin or padding which you just added

**Comment by Sahil-Shadwal** [comment]
already did

**Comment by Akshaybagai52** [comment]
Okay

**Comment by Sahil-Shadwal** [comment]
![image](https://github.com/json-schema-org/website/assets/119167601/84040fcd-0598-4014-836d-3fe081bbfff9)

thoughts ?

**Comment by VivekJaiswal18** [comment]
Yes it is much better

**Comment by VivekJaiswal18** [comment]
Maybe something like this-


https://github.com/json-schema-org/website/assets/96608169/fb81d58d-796a-48c7-9c7b-73930c5f173a



This is a rough idea/prototype and requires refinement and some buttons.
Any suggestions @benjagm

**Comment by Akshaybagai52** [comment]
> @Sahil-Shadwal Maybe something like this-
> 
>  com.mp4 
> This is a rough idea/prototype and requires refinement and some buttons. And the `upcoming events` go below it Any suggestions @benjagm

This design looks good but I think there is purpose of placing 'upcoming events' below third card because anyone who reads the third card then he will read about 'upcoming events' and if we place 'upcoming events' separate from third card then there is probability that he can miss that 'upcoming events'. But we can wait for benja to get his review about that
