### ISSUE TITLE
Define node version to use in .node-version

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/website#6]
For deployment and local use, we should define a `.node-version` file.

https://developers.cloudflare.com/pages/platform/build-configuration/#language-support-and-tools

Cloudflare defaults to 12.18, which is a little old.
I currently have it set via envrionment vairable inside cloudflare UI.

**Comment by benjagm** [comment]
@OlliesWorld Thoughts on this?

**Comment by OlliesWorld** [comment]
Sorry missed this.
Next 13 requires `The minimum Node.js version has been bumped from 12.22.0 to 14.18.0, since 12.x has reached end-of-life.`
https://nextjs.org/docs/pages/building-your-application/upgrading/version-13

**Comment by benjagm** [comment]
We found some issues recently and to fix them we are running on 16.0.0

**Comment by jdesrosiers** [comment]
> We found some issues recently and to fix them we are running on 16.0.0

Node.js 16 reached end-of-life today. That means it's no longer receiving security patches and is now a risk factor. I think it should be a high priority to address whatever is stopping us from using at least Node.js 18.
