### ISSUE TITLE
🐛 Bug: Adding hover effect to sidenavbar.

### ISSUE THREAD

**Issue by TamannaVerma99** [json-schema-org/website#606]
### Describe the bug

It would be better to have a hover effect on drop down icon in side navbar present in docs section

### Steps To Reproduce

1.Go to [LINK](https://json-schema.org/learn/getting-started-step-by-step)

https://github.com/json-schema-org/website/assets/96949249/59416beb-c5c0-4aba-b604-04f9e9e97b38

### Expected Behavior

Cursor value should change to pointer while hovering on dropdown icon.

https://github.com/json-schema-org/website/assets/96949249/46a096ba-ac41-4898-a339-ed2a823a2ceb

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by TamannaVerma99** [comment]
Hey @benjagm 
Should I work on this?

**Comment by AdityaSingh-02** [comment]
@benjagm Can I work on this?

**Comment by benjagm** [comment]
Good idea thanks Tamanna!! Issue accepted. Please go ahead.
