### ISSUE TITLE
🐛 Bug: Inconsistent text color in dark mode under array section of docs 

### ISSUE THREAD

**Issue by JeelRajodiya** [json-schema-org/website#608]
### Describe the bug

![image](https://github.com/json-schema-org/website/assets/63534268/4233ad27-9701-4f6e-b96b-96690ec8202f)

### Steps To Reproduce

1. Go to https://json-schema.org/understanding-json-schema/reference/array
2.  Turn on the dark mode
3.  You will find the languages written in dark color, which is not readable 

### Expected Behavior

The text should have white color

![image](https://github.com/json-schema-org/website/assets/63534268/1ce8d498-0b2c-4c9f-8ac2-a7c93571def6)

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by Adity20** [comment]
Can I work on this @benjagm?

**Comment by Khaleeq01** [comment]
@benjagm Will you assign this issue to me

**Comment by benjagm** [comment]
Good catch! thanks! Go ahead @Khaleeq01 !!

**Comment by Khaleeq01** [comment]
@JeelRajodiya Will you help me in which folder should i find the code regarding thi s issue. The codebase is very long.

**Comment by vinfinity7** [comment]
Hi @Khaleeq01 visit pages\understanding-json-schema\reference\array.md for the aforementioned file 👍

**Comment by Khaleeq01** [comment]
@vinfinity7 Yes got it. Thanks but here only html code is written from where can i access CSS files.

**Comment by vinfinity7** [comment]
components\StyledMarkdown.tsx line 140 , Tip : In Order to find any peice of code , first familiarize yourself

**Comment by vinfinity7** [comment]
components\StyledMarkdown.tsx  line 140  
ProTip : When navigating through a codebase, it's incredibly helpful to first get known with how the code is structured and how it contributes to rendering the complete website. Understanding the layout and flow of the code will make it much easier to locate specific pieces of code when you need them ( Learn how to use the Search Bar efficiently). Happy coding!

**Comment by JeelRajodiya** [comment]
>@JeelRajodiya Will you help me in which folder should i find the code regarding thi s issue. The codebase is very long.

> components\StyledMarkdown.tsx line 140

along with line 140, you will also need to modify line 143 and 144

![image](https://github.com/json-schema-org/website/assets/63534268/de4c56c2-1105-4cc3-b2d7-e548016c61c1)

**Comment by benjagm** [comment]
Are you still working on this issue @Khaleeq01 ?

**Comment by DhairyaMajmudar** [comment]
Would like to take this up : )

**Comment by benjagm** [comment]
Thanks Dhairya. Please go ahead.
