### ISSUE TITLE
🐛 Bug: box-shadow issue in dark mode on home page

### ISSUE THREAD

**Issue by Akshaybagai52** [json-schema-org/website#610]
### Describe the bug

There is box-shadow applied in dark mode on home page elements which causes text and button to be sticking to the border of the element or card as shown in screenshot attached but in light mode box shadow is not there so it is looking good.

### Steps To Reproduce

Go to home page 
Turn on dark mode
Scroll down to "Welcome to the JSON Schema Community" section
and there are three sections named "Join the JSON Schema Slack Workspace!", "The JSON Schema blog" and "JSON Schema Community Meetings & Events"
Here box-shadow is applied to the parent tag due to which it looks like there isn't enough padding within the tags so the text and buttons sticking to the border of the tag.

### Expected Behavior

Box-shadow should be removed

### Screenshots

![image](https://github.com/json-schema-org/website/assets/100753870/52db997a-7299-4e9c-94d6-5fdf9d45cd33)
![image](https://github.com/json-schema-org/website/assets/100753870/fb10d70c-7141-4ca8-96ea-5ce811c6ba96)
![image](https://github.com/json-schema-org/website/assets/100753870/90864bec-06a1-4afb-8c86-ea864e3ed3e1)
![image](https://github.com/json-schema-org/website/assets/100753870/ed05c041-7447-4c4d-afc3-b8863b03f20b)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

Yes

**Comment by benjagm** [comment]
Thanks @Akshaybagai52 Go ahead!

**Comment by vinfinity7** [comment]
would like to work on this !
