### ISSUE TITLE
🐛 Bug: Inconsistent Dark Mode on Obsolete Implementations page

### ISSUE THREAD

**Issue by vinfinity7** [json-schema-org/website#614]
### Describe the bug

The Dark mode is not consistent  on this page .

### Steps To Reproduce

- Go to [LINK](https://json-schema.org/obsolete-implementations)
- Toggle to dark mode 
- Observe

### Expected Behavior

The Table Should also toggle between dark and light mode 

### Screenshots

![image](https://github.com/json-schema-org/website/assets/122719607/8782307c-c428-4aca-945e-81f89f2b5a67)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by TamannaVerma99** [comment]
Hey @vinfinity7 
Sorry to interrupt you but I have already solved this issue in ISSUE #586 itself.You can check that once before working on it.
Thanks:)

**Comment by vinfinity7** [comment]
Ohk  nevermind!  @TamannaVerma99

**Comment by benjagm** [comment]
duplicated with #586 . Let's please wait to get the issues accepted and assigned before sending a PR.
