### ISSUE TITLE
🐛 Bug:  Tools page does not have a Sidebar

### ISSUE THREAD

**Issue by vinfinity7** [json-schema-org/website#616]
### Describe the bug

Tools page doesn't have a sidebar 

### Steps To Reproduce

go to https://json-schema.org/implementations

### Expected Behavior

![image](https://github.com/json-schema-org/website/assets/122719607/3a85cb03-95e3-42ae-9fe6-957844443a1d)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by benjagm** [comment]
Thanks for opening this issue, however I can't reproduce it. Can you specify what is your scenario?

**Comment by benjagm** [comment]
Thanks for filing this issue, however this page is not expected to have sidebar.
