### ISSUE TITLE
✨ Enhancement: Hover effects on button 

### ISSUE THREAD

**Issue by Akshaybagai52** [json-schema-org/website#621]
### Is your feature request related to a problem? Please describe

There aren't any hover effects on buttons all around the website repo except github button present in the navbar

### Describe the solution you'd like

We can apply hover effects on buttons so the user experience will be good

### Are you working on this?

Yes

**Comment by VivekJaiswal18** [comment]
@Akshaybagai52 I have already raised a PR for this issue. here #428

**Comment by Akshaybagai52** [comment]
> @Akshaybagai52 I have already raised a PR for this issue. here #428

Okay thanks for informing I'll close this issue
