### ISSUE TITLE
✨ Enhancement: Rebuild the sponsors page 

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#626]
### Is your feature request related to a problem? Please describe

We'd like to create a new sponsors page with better UX. The inspiration is the financial page of the AsycnAPI: https://www.asyncapi.com/finance

This will help us to increate the contributions coming from Organizations.

### Describe the solution you'd like

Prototype to be added.

### Are you working on this?

Yes

**Comment by vinfinity7** [comment]
@benjagm i would love to collaborate 👍

**Comment by Akshaybagai52** [comment]
Hey @benjagm if it's not assigned then I would love to contribute to it

**Comment by VivekJaiswal18** [comment]
Hey @benjagm I would love to collaborate too.

**Comment by benjagm** [comment]
Thanks @vinfinity7 !! Please go ahead!

**Comment by benjagm** [comment]
This is the prototype for this page:
[sponsors-prototype.pdf](https://github.com/json-schema-org/website/files/14903901/sponsors-prototype.pdf)

Considerations:
- The prototype is made by screenshots from AsyncAPI so please, adjust the colours to the JSON Schema branding.
- The budget values to build the graph are available here: https://github.com/orgs/json-schema-org/discussions/692
- The sponsorship tiers for the table are available here: https://github.com/json-schema-org/community/blob/main/programs/sponsors/sponsors.md

Thanks a lot.
