### ISSUE TITLE
✨ Enhancement: Modifications required in blog page

### ISSUE THREAD

**Issue by Akshaybagai52** [json-schema-org/website#627]
### Is your feature request related to a problem? Please describe

go to https://json-schema.org/blog
scroll down to filter section 
then click on any filter option it shows result according to filter option selected but the active filter doesn't get any color 

### Describe the solution you'd like

I would like to add color for active tab 

### Are you working on this?

Yes

**Comment by officeneerajsaini** [comment]
This issue looks good to me .

**Comment by benjagm** [comment]
Good improvement. Thanks. Issue accepted.

**Comment by JeelRajodiya** [comment]
**Benjamin**, Can I please work on this issue?

**Comment by benjagm** [comment]
Thanks Jeel. Please go ahead
