### ISSUE TITLE
🐛 Bug: Dark theme consistency for CarbonAds

### ISSUE THREAD

**Issue by DarhkVoyd** [json-schema-org/website#630]
### Describe the bug

With the addition of the dark theme to our website, the white background of carbons ads looks quite bad, which might gather some negative reviews from our users given the past feedback we have had around ads on the website. 

### Steps To Reproduce

This can be reproduced by:
1.  Visiting the website
2.  Enable the dark mode
3. Now, visit any page with ads enabled such as [this](https://json-schema.org/learn/getting-started-step-by-step)

### Expected Behavior

The dark theme should be consistent with CarbonAds component.

### Screenshots

![Screenshot 2024-04-06 at 2 00 28 AM](https://github.com/json-schema-org/website/assets/77478658/cb243bdc-d187-4039-844e-775db4d45333)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by JeelRajodiya** [comment]
**Benjamin**, Can I work on this?

**Comment by crampussm** [comment]
Hey! @benjagm could I work on this?

**Comment by benjagm** [comment]
After giving this a second thought I think it is ok to leave as it is now. The result is actually not bad.
