### ISSUE TITLE
✨ Enhancement: Adopters Should have a dedicated page

### ISSUE THREAD

**Issue by vinfinity7** [json-schema-org/website#631]
### Is your feature request related to a problem? Please describe

The Adopters Section should have a dedicated page with UI likewise the whole website 

### Describe the solution you'd like

I am thinking of a tabular UI as in accordance to any other tabular data in the website 

### Screenshot

![image](https://github.com/json-schema-org/website/assets/122719607/b4c34663-c00d-429e-a8d1-914c52ab95b9)

### Additional context

I would love to work on this one!

### Are you working on this?

Yes

**Comment by benjagm** [comment]
Closed in favour of the Landscape project. https://landscape.json-schema.org/
