### ISSUE TITLE
✨ Enhancement: Newsletter landing page

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#634]
### Is your feature request related to a problem? Please describe

As part of #308 we implementer an initial version of the newsletter component that is now available in the branch [web-release-3](https://github.com/json-schema-org/website/tree/web-release-3) pending to be merged to main alongside other features part of the[ release 3 of the docs strategy](https://github.com/json-schema-org/website/issues/158).

That initial version of the page available in /pages/newsletter is only providing a subscribe form but we'd like to make that page much more powerful by showing also a welcome message and the previously published newsletter. I do like what the CNCF did with their newsletter: https://www.cncf.io/kubeweekly/

I'd like to have something similar. The newsletter will be created in mailchimp so probably we'll need to have a json or yaml file inside the /data folder with the details of newsletters:

- url
- title
- Date

I do like the design of CNCF so let's do something similar. In this case I think we can use the generic card component we build using Title, Body and Link.

### Describe the solution you'd like

See the feature description

### Are you working on this?

No

**Comment by Akshaybagai52** [comment]
Hello @benjagm 
Can I work on this issue?

**Comment by Piyusharora2003** [comment]
Hi @benjagm , is the issue still available to work up on .

**Comment by benjagm** [comment]
Akshaybagai52  and Piyusharora2003 thanks for your support. @Akshaybagai52 you was first so all yours. Thanks!

**Comment by Akshaybagai52** [comment]
Hey @benjagm can you tell me about how we can get previous newsletter data to show in the newsletter page and also Do I need to make the changes in design like form on right side and addition details on left side

**Comment by benjagm** [comment]
> Hey @benjagm can you tell me about how we can get previous newsletter data to show in the newsletter page and also Do I need to make the changes in design like form on right side and addition details on left side

Hi Akshay, the link to previous newsletters will be in a json or yaml file with this structure:

* url
* title
* Date

Use this link as reference for the newsletters: https://us8.campaign-archive.com/?e=__test_email__&u=ef8789d5789a6aff8113a701d&id=69a182f12d

**Comment by Akshaybagai52** [comment]
> > Hey @benjagm can you tell me about how we can get previous newsletter data to show in the newsletter page and also Do I need to make the changes in design like form on right side and addition details on left side
> 
> Hi Akshay, the link to previous newsletters will be in a json or yaml file with this structure:
> 
> * url
> * title
> * Date
> 
> Use this link as reference for the newsletters: https://us8.campaign-archive.com/?e=__test_email__&u=ef8789d5789a6aff8113a701d&id=69a182f12d

Hello Benja
can you check this PR https://github.com/json-schema-org/website/pull/681
Right now I've added dummy details of previous Newsletter Do I need to refactor the design of newsletter page?

**Comment by benjagm** [comment]
> can you check this PR #681
> Right now I've added dummy details of previous Newsletter Do I need to refactor the design of newsletter page?

Thanks @Akshaybagai52 !! This is what I was talking about! There are some changes to be done that I am going to details in the PR.

Great progress!!

**Comment by benjagm** [comment]
@Akshaybagai52 Are you still working on it? We can complete the last changes from our side if this is ok for you.

**Comment by Akshaybagai52** [comment]
> @Akshaybagai52 Are you still working on it? We can complete the last changes from our side if this is ok for you.

Sorry I just forgot to mention you in the latest changes. You can check the latest commit and tell me if there will be any changes need to be done
Thanks

**Comment by benjagm** [comment]
Completed with #733
