### ISSUE TITLE
[📝 Docs]: The Bundling Section of The Structuring doc needs updating for v2012

### ISSUE THREAD

**Issue by theory** [json-schema-org/website#647]
### What Docs changes are you proposing?

It looks like the Bundling section of the Structuring doc needs updating for v2020-12. Proposed changes:

* Use full `$id` in sub-schemas
* Use sub-schema `$id` string for `$defs` keys
* Note this change from 2019 in a new `Draft-specific info` tab

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by radhesh1** [comment]
Hi theory!

**Comment by theory** [comment]
Hi yourself :-)

**Comment by radhesh1** [comment]
Could I help with this too? 
:)

**Comment by theory** [comment]
I wouldn't complain.

**Comment by jdesrosiers** [comment]
I actually rewrote this entire page as part of the 2020-12 updates. So, it's up-to-date with the latest specification.

> * Use full `$id` in sub-schemas

Non-relative URIs aren't required in `$id`. What's required is that they _resolve_ to a non-relative URI. The `$id`s in embedded schemas resolve against the identifier of the schema they're embedded in. I used the relative URI on purpose to illustrate that behavior.

> * Use sub-schema `$id` string for `$defs` keys

Using the URI for the `$defs` key is a recommendation. It has no effect whatsoever on behavior, so it's a little odd to make a recommendation about this at all. The page could be updated to use the recommendation, but it is correct as is. The reason I didn't use a URI was to avoid the confusion that that value matters. By using something that doesn't match the `$id`, I was illustrating that that value could be anything.

> * Note this change from 2019 in a new `Draft-specific info` tab

Not much really changed from 2019-09 to 2020-12. The recommendation about using URIs for embedded schemas in `$defs` is new. The ability to embedded a schema of a different dialect than the parent schema is new. The latter is probably worth mentioning in a "Draft-specific info" block.

**Comment by theory** [comment]
> I used the relative URI on purpose to illustrate that behavior.

I can see that but since I was looking into how to *bundle* schemas, I found this a little confusing, because it appeared to require a change to the `$id`. But it's not required --- and indeed I think it would be clearer, when talking about bundling, for the bundled sub-schemas to be identical to their previous structure, including the ID. Maybe note that they have have to resolve to the base URI.

> Using the URI for the $defs key is a recommendation. 

Okay, good to know. I was a little confused because it only worked for me to use the ID as the object key (using the boon library). It's possible I did something wrong, will try again.

> The latter is probably worth mentioning in a "Draft-specific info" block.

+1

**Comment by jdesrosiers** [comment]
Ok. Let's change the embedded `$id`s to be the full URI and add a "Draft-specific info" block to call out that support for mixing drafts was added in 2020-12.

@radhesh1, it sounds like you would you like to work on this one? Unless @theory wanted to do it himself?

**Comment by Dule-martins** [comment]
@theory if what you are proposing which is adding a `Draft-specific info` is the fix to this issue, can it be assigned to me for completion?
To add to this 
@benjagm what do you think?

> > I used the relative URI on purpose to illustrate that behavior.
> 
> I can see that but since I was looking into how to _bundle_ schemas, I found this a little confusing, because it appeared to require a change to the `$id`. But it's not required --- and indeed I think it would be clearer, when talking about bundling, for the bundled sub-schemas to be identical to their previous structure, including the ID. Maybe note that they have have to resolve to the base URI.
> 
> > Using the URI for the $defs key is a recommendation.
> 
> Okay, good to know. I was a little confused because it only worked for me to use the ID as the object key (using the boon library). It's possible I did something wrong, will try again.
> 
> > The latter is probably worth mentioning in a "Draft-specific info" block.
> 
> +1

Going with @theory on this one, because every documentation aims to provide clarity to the user, where there is clarity there is no confusing it is a seamless journey to implementation.

**Comment by theory** [comment]
I do not have permission to assign people on this project.

**Comment by benjagm** [comment]
Thanks everyone! Who is finally going to implement the solution? Happy to assign the issue to them.

**Comment by Dule-martins** [comment]
@benjagm I updated my comment

**Comment by Dule-martins** [comment]
@theory and @jdesrosiers please I left a comment on slack in #contributor channel can you take a look and give me feedback 

Thanks

**Comment by benjagm** [comment]
Hi @Dule-martins ! Can you please add here the same question you shared in Slack?

**Comment by Dule-martins** [comment]
Okay, @benjagm

**Comment by jdesrosiers** [comment]
@Dule-martins, the answer is [here](https://github.com/json-schema-org/website/issues/647#issuecomment-2054144906)

* The `$defs` keys should remain the same.
* All `$id`s should to be changed to absolute URIs.
* Add a Draft-specific Info block to say that support for changing dialects in an embedded schema (using `$schema` with a different value than the parent schema) was added in 2020-12. This topic is covered in the last paragraph and Draft-specific Info box. You should just have to add another Draft-specific Info box at the end explaining the difference in 2019-09 because the difference for draft-04/6/7 is already covered.

**Comment by theory** [comment]
How's it coming, @Dule-martins?

**Comment by Dule-martins** [comment]
Hello David
Sorry for the long break, I have been on holiday I just resume work so am
ready to be more active in the community

Can I still pick up from where I drop off?

**Comment by theory** [comment]
> Hello David Sorry for the long break, I have been on holiday I just resume work so am ready to be more active in the community Can I still pick up from where I drop off?

I don't see why not. :-)

**Comment by Dule-martins** [comment]
Alright, sure I will take a look at it late a night.
Thank you

**Comment by theory** [comment]
🎉
