### ISSUE TITLE
✨ Enhancement: Web release 3 - Improve resources data / fetch

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#656]
### Is your feature request related to a problem? Please describe

We are preparing for the release 3 of the website with multiple cool features. One of those features is the new resources section. This page is actually fetching the data from https://raw.githubusercontent.com/sourcemeta/awesome-jsonschema/master/data.yaml but we'll prefer to read it from the resources.yaml file available in the data folder.

In addition we'll need to clear the data of that file removing all items of type: Adoption, Article, Tutorial and Vocabulary

This is available in the branch: https://github.com/json-schema-org/website/tree/web-release-3

Section pre-deployed: 
https://web-release-3.website-2v2.pages.dev/resources/books

Source:
/pages/resources

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

### Additional context

.

### Are you working on this?

No

**Comment by DhairyaMajmudar** [comment]
Would love to take this : D

**Comment by VivekJaiswal18** [comment]
Sounds interesting! I would love to work on this

**Comment by benjagm** [comment]
Thanks a lot for your interest. Go ahead Dhairya
