### ISSUE TITLE
[📝 Docs]: Simplify examples on getting started page

### ISSUE THREAD

**Issue by bhavukkalra** [json-schema-org/website#658]
### What Docs changes are you proposing?

Emerged out of the original issue #653.
Page - [getting-started-step-by-step](https://json-schema.org/learn/getting-started-step-by-step)

This issue tracks the progress on having simpler workings while explaining `required` keys to a new user onboarded.

Currently - explanation for required keys  of "productId", "productName" is kinda confusing. The docs does mentions that they are required but it can't be observed in the changes made.
It is only some time later that we see the line of code

```json
"required": [ "productId", "productName", "price]" 
```

Where it starts to make sense.

A better way to write it would be 

```js
  "properties": {
    "productId": {
      "description": "The unique identifier for a product",
      "type": "integer"
    }
  },

  "required": ["productId"]
```

i.e Update the required key as we go along adding new attributes. Not all at once (which is currently in the docs). As it makes a proper flow of what is written in text and simultaneously in code

Original comment - https://github.com/json-schema-org/website/issues/653#issuecomment-2056423433

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chidiadi01** [comment]
Hi, @bhavukkalra I'd love to work on this issue.

**Comment by gregsdennis** [comment]
I think the page is fine as it is.  It presents a journey that I think is more akin to what a developer will experience building a schema: you define the properties, then you say which ones are required.  In JSON Schema these are two different constraints, so it makes sense to help the developer start thinking that way.

**Comment by benjagm** [comment]
Finally we are not implementing changes.
