### ISSUE TITLE
 [📝 Docs]: Improve wording of the new Welcome page for the release 3 of the website

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#660]
### Is your feature request related to a problem? Please describe

We have created a new welcome page for our docs but we need to add all the texts with something inspiring.

You can see that page here: https://web-release-3.website-2v2.pages.dev/overview/welcome

Source: https://github.com/json-schema-org/website/tree/web-release-3/pages/overview/welcome

Branch: https://github.com/json-schema-org/website/tree/web-release-3

### Describe the solution you'd like

Texts that inspires.

### Are you working on this?

No

**Comment by vinfinity7** [comment]
@benjagm Whats up with this , Can I hop in ?

**Comment by benjagm** [comment]
We have technical writers joining the Community and ideally I hope anyone from that group will jump in.

**Comment by kwennB** [comment]
Hi @benjagm I would like to work on this. Is it available?

**Comment by benjagm** [comment]
Thanks @kwennB ! Go ahead!

**Comment by kwennB** [comment]
> Thanks @kwennB ! Go ahead!

Thank you, I will get started!

**Comment by himanshuaggar** [comment]
@benjagm , I would like to work on this issue, If it's still open.

**Comment by kwennB** [comment]
> @benjagm , I would like to work on this issue, If it's still open.

Hey, I'm working on it....

**Comment by benjagm** [comment]
Closed as completed.
