### ISSUE TITLE
[📝 Docs]: Add Table of Contents and Tabs Group to the Markdown Style Guide

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#663]
### What Docs changes are you proposing?

We created A markdown style guide https://json-schema.org/md-style-guide with some custom tags we are using to improve the formatting of Markdown and provide consistency.

This document is missing some of the custom tags like:

- TableOfContent (available in multiple pages like https://json-schema.org/specification-links)
- Tabs Groups using tabs-start / tabs-end. (available in multiple pages like https://json-schema.org/understanding-json-schema/conventions)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by srini047** [comment]
Hey @benjagm, I would like to take up this issue.

**Comment by benjagm** [comment]
Sure @srini047 go ahead!

**Comment by vinfinity7** [comment]
@srini047 Whats up with this ?

**Comment by srini047** [comment]
@vinfinity7 Almost done will make PR soon.
