### ISSUE TITLE
Restructure and rewrite What is JSON Schema Page in the overview section of the documentation for clarity

### ISSUE THREAD

**Issue by Nickyshe** [json-schema-org/website#670]
### What Docs changes are you proposing?

After careful and detailed auditing, I found these problems in the documentation and require improvement.
The page **What is JSON Schema** under the overview section needs improvement in two areas:
1. Structure of the content: 
**Problem:**
The **History of JSON Schema** is added at this page's end.
**Solution:**
With the knowledge of Information architecture, the **History of JSON Schema** should be placed at the beginning of the documentation or created on a separate page. This provides a good flow of information for readers. 

See the highlighted image below:
![Screenshot (511)](https://github.com/json-schema-org/website/assets/110067624/99d5d407-6f9c-43fe-96d9-41ea21676932)
2. Pronoun usage, active voice, and reduce redundancy.
**Problem:**
Third-person pronouns are not encouraged in writing technical documents unless in some special cases and depending on the context. This section used **We** to address the reader instead of **You**, which is the right pronoun to use when writing for your readers. The use of passive voice needs to be clarified for the reader about who is to perform an action.

**Solution:**
-  Use of second-person pronoun(you) to address the reader
-  Use of active voice
-  Make content concise to reduce redundancy
see the highlighted image below: there are other contents with this issue that require modification
![Screenshot (512)](https://github.com/json-schema-org/website/assets/110067624/ab544305-43f1-4ba7-9d52-da2a2c85b83c)

Link to [**What is JSON Schema page**](https://json-schema.org/overview/what-is-jsonschema)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
> This section used We to address the reader instead of You, which is the right pronoun to use when writing for your readers.

While I would agree with this in a formal tech doc like a spec, this is informal.  I think the pronoun use is fine, but it should be consistent.

**Comment by gregsdennis** [comment]
> The use of passive voice needs to be clarified for the reader about who is to perform an action.

What action?  The user is reading docs.  We (the author) aren't asking the reader to _do_ anything.

**Comment by Nickyshe** [comment]
@benjagm noted  working on it 

Additional information to be added

-  under this section there should be a heading for the **use case of JSON Schema** 
What do you think?

**Comment by himanshuaggar** [comment]
@benjagm, I would also like to work on it.
