### ISSUE TITLE
Feature : github-actions - Setup stale Issues and PRs workflow

### ISSUE THREAD

**Issue by aialok** [json-schema-org/website#689]
**Description:**
This feature involves setting up a workflow to manage stale issues and pull requests (PRs) effectively. Stale issues and PRs can accumulate over time, leading to clutter and reduced productivity. By implementing this workflow, we aim to automatically identify and label stale issues and PRs based on predefined criteria. Additionally, the workflow will incorporate actions such as notifying contributors, closing stale items, or prompting for updates to keep the issue tracker organized and relevant. This feature will streamline issue and PR management, ensuring that active contributions receive timely attention while maintaining a clean and responsive development environment.

Something like this:

![Image](https://github.com/json-schema-org/website/assets/66772290/15f7e906-1856-4ca6-ad61-a5a4e7bdfc6b)

**Comment by gregsdennis** [comment]
I think this is a good idea for all the repos in general.

For the spec repo, however, I'd be leary about setting this up right now.  We have a lot of historical issues that still need to be addressed in some way, but we're not prepared to do so.  We need to do a proper triage of all of them first.

If @benjagm feels comfortable setting this up for just the website, that's fine.  It's a fairly new repo, and the issues should be pretty well triaged.

**Comment by aialok** [comment]
@benjagm, could you please tell me about the minimum time required for issues and PRs to be marked as stale? Also, what is the minimum time for closing issues & PRs?

Example:

![image](https://github.com/json-schema-org/website/assets/66772290/bb1ba9bc-f1f3-41a7-ae44-3a7001107aa7)

**Comment by benjagm** [comment]
> @benjagm, could you please tell me about the minimum time required for issues and PRs to be marked as stale? Also, what is the minimum time for closing issues & PRs?

What about 2 weeks?

**Comment by aialok** [comment]
Great, I am going with 2 weeks.
Thank you  : )
