### ISSUE TITLE
Feature: github-actions - Setup authorised file detection job

### ISSUE THREAD

**Issue by aialok** [json-schema-org/website#694]
**Description** 
This jobs alerts maintainers about any unauthorized changes to specified files, helping prevent accidental or malicious modifications. The job will automatically fail if any of the following files are modified:

``` yaml         
.github/**
.husky/**
env.example
package.json
tsconfig.json
next.config.js
next-sitemap.config.js
next-env.d.ts
tailwind.config.js
postcss.config.js
yarn.lock
Dockerfile
CODEOWNERS
LICENSE
.gitignore
.gitsmodules
.gitattributes
.eslintrc.js
.eslintignore
.zshrc
.prettierrc
.prettierignore
.dockerignore
```

By implementing this, we can ensure the integrity and security of critical files in the repository.

**Comment by benjagm** [comment]
What is the process to modify the files when it is necessary? Would it be Disable the GitHub action temporarily for the change?

**Comment by DhairyaMajmudar** [comment]
One thing that can be done is to give a warning to the user when the listed file is changed/deleted instead of failing the workflow. If the change is required then the warning can be ignored while doing PR merge : )

**Comment by aialok** [comment]
The process is the same: when we know a pull request involves changes to workflow files or other configuration files (excluding UI changes), it is acceptable to merge the pull request even if the job fails. However, if the pull request involves changes to the UI only, we should not merge it until the job passes.

And other things which we can do is the comment on the pull request about unauthorized file changes, but our job will pass each time regardless. This is what @DhairyaMajmudar is suggesting.

Like in the past, we've seen many pull requests related to the UI that included changes in the `yarn.lock` file. With this, we can easily identify changes in unauthorized files, even if there are multiple files with many lines of additions and deletions.
