### ISSUE TITLE
✨ Enhancement: Add query string for blog filters

### ISSUE THREAD

**Issue by gregsdennis** [json-schema-org/website#703]
### Is your feature request related to a problem? Please describe

It's impossible to share a category of blog posts (e.g. case studies).

### Describe the solution you'd like

Updating the URL with a query string (and then also applying the filter based on the query string) would allow sharing topical blog post sets.

### Describe alternatives you've considered

There are none.

### Are you working on this?

No

**Comment by benjagm** [comment]
We have this already implemented but not documented. To share a category you can use type as query parameter. For examples:

- https://json-schema.org/blog?type=Engineering
- https://json-schema.org/blog?type=Community
- https://json-schema.org/blog?type=Case%20Study

**Comment by gregsdennis** [comment]
It may be implemented if the user types the query string or is linked to it, but clicking on the tags should update the URL.

**Comment by benjagm** [comment]
Yeah. Let's do it.
