### ISSUE TITLE
[📝 Docs]: Review the content of the FAQ page of the release 3

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#706]
### What Docs changes are you proposing?

The purpose of this issue if the make a content review of the new FAQ page available in the release 3 branch and proceed with the improvements if required.

https://web-release-3.website-2v2.pages.dev/overview/faq

Code is available in /pages/overview/faq

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kwennB** [comment]
Thank you @benjagm I'll get started
