### ISSUE TITLE
✨ Enhancement: Build Data-Driven Tooling Page

### ISSUE THREAD

**Issue by DarhkVoyd** [json-schema-org/website#716]
## Description:

This issue will serve as the parent issue for tracking the progress of the GSoC 2024 project focused on building a data-driven tooling page for the JSON Schema. 

## Epic Releases and Tasks:

- [x] #717
   
- [x] #722

- [x] #779

- [x] #780

- [x] #777

- [x] #776

- [x] #778

- [ ] **Dashboards**

Resolves: #160

### Are you working on this?

Yes

**Comment by benjagm** [comment]
Looks great!
