### ISSUE TITLE
🐛 Bug: "Edit this page on Github" fails when the URL contains a fragment

### ISSUE THREAD

**Issue by gregsdennis** [json-schema-org/website#725]
### Describe the bug

Edit this page on GitHub link should ignore fragments.

### Steps To Reproduce

1. Go to any documentation page
2. Click on a header so that a fragment is added to the URL, e.g.
3. Scroll to the bottom and click on the "edit this page on GitHub" link

The browser is directed to a page that doesn't exist because the fragment is included in the file name.

For example, clicking the link when the URL is

https://json-schema.org/understanding-json-schema/reference/object#unevaluatedproperties

takes me to

https://github.com/json-schema-org/website/blob/main/pages/understanding-json-schema/reference/object#unevaluatedproperties.md

### Expected Behavior

The link should remove any fragments before constructing the file name.

In the example above I should be redirected to

https://github.com/json-schema-org/website/blob/main/pages/understanding-json-schema/reference/object.md

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by benjagm** [comment]
Good catch. We'll fix it. Thanks

**Comment by DarhkVoyd** [comment]
I am working on it.

**Comment by benjagm** [comment]
DV Go ahead please.
