### ISSUE TITLE
✨ Enhancement: Dark/Light mode toggle can be confusing

### ISSUE THREAD

**Issue by gregsdennis** [json-schema-org/website#726]
### Is your feature request related to a problem? Please describe

The dark/light mode button in the upper left of every page operates to say, "click this to go to the mode indicated by the icon."  For example, in dark mode, it shows a sun; and in light mode, it shows a moon.

It shows the mode that that clicking the button would result in.  However, typically, I think of a toggle as showing the mode that you _are_ in.

That said, I can also see that some people might expect the current behavior.

As a result, I'm not sure that the current button adequately caters to all perspectives.  It might seem correct for some, but it's definitely backwards for me.

### Describe the solution you'd like

https://chirpy.cotes.page/ uses a single icon that's just color-flipped with the theme.  The icon indicates both light and dark, indicating that the button toggles between them.

![image](https://github.com/json-schema-org/website/assets/2676804/f0e5213a-cefd-4c44-a2c3-22f21751a2df) ![image](https://github.com/json-schema-org/website/assets/2676804/f4b50912-9992-4b2a-88d1-628b232760ac)

Our current button shows the state, but Chirpy's doesn't.  Chirpy's doesn't carry a state because the theme _is_ the state.  You can plainly see which mode you're in.  The button icon merely needs to indicate that it changes the state.

I'm not saying we need to use _this_ icon, but I think this approach is better.

### Describe alternatives you've considered

The other option is to have a slider toggle, but that takes up more room on the page, and doesn't really fit with the iconography theme we have in the upper right of just single icons.

### Are you working on this?

No

**Comment by benjagm** [comment]
I like this proposal! Thanks Greg.

**Comment by JeelRajodiya** [comment]
Hi, Can I please work on this issue?

**Comment by gregsdennis** [comment]
The Chocolatey website shows yet another aproach: a drop-down with explicit options.  The nice thing about this is that it includes a browser-detection option.

![image](https://github.com/json-schema-org/website/assets/2676804/ffa905b4-93db-4a3e-b966-450aca5719ba)

**Comment by crampussm** [comment]
@benjagm Hi, can I work on this?

**Comment by benjagm** [comment]
@JeelRajodiya Please go ahead. Have you seen Greg's last proposal?

**Comment by JeelRajodiya** [comment]
> @JeelRajodiya Please go ahead. Have you seen Greg's last proposal?

Yes. I think we might need to use a UI library if we want create a drop down list. **Are we using any UI library in the website?** I tried looking in the codebase but couldn't find any. 

**on a side note, this is how it looks like if we make changes as per greg's initial proposal**

![input](https://github.com/json-schema-org/website/assets/63534268/cfc130b0-1eb7-4320-9fe0-e9e8db113c9d)

**Comment by benjagm** [comment]
> Are we using any UI library in the website?** I tried looking in the codebase but couldn't find any.

We are exploring https://ui.shadcn.com/

CC @DhairyaMajmudar

**Comment by DhairyaMajmudar** [comment]
Hi @JeelRajodiya there's a plan to implement ShadCN UI lib. but since this is currently in the planning the above dropdown feature can be implemented using `<select>` and `<options>` HTML tags.

**Comment by DarhkVoyd** [comment]
Also, why do we have to click the toggle button multiple times to switch the theme, this has started to bug me.

**Comment by JeelRajodiya** [comment]
> Could you also check why do we have to click the toggle button multiple times to switch the theme (on a fresh load), this has started to bug me.

@DarhkVoyd Do you mean the improper icon colors shown in the image below? 
![image](https://github.com/json-schema-org/website/assets/63534268/37f33279-0602-4d1c-9d33-938fe5820c2a)

**Comment by DarhkVoyd** [comment]
It takes two clicks to change the theme.

https://github.com/json-schema-org/website/assets/77478658/9b712e8c-1901-4632-8cfe-c2d86ec79051

**Comment by JeelRajodiya** [comment]
> It takes two clicks to change the theme.
> 
>  Screen.Recording.2024-06-17.at.8.49.36.PM.mov

Thankss! I will look into this

**Comment by JeelRajodiya** [comment]
> It takes two clicks to change the theme.
> 
>  Screen.Recording.2024-06-17.at.8.49.36.PM.mov

Fixed!
