### ISSUE TITLE
🐛 Bug: TableOfContent component throws warning in dev console

### ISSUE THREAD

**Issue by DarhkVoyd** [json-schema-org/website#760]
### Describe the bug

The `TableOfContent` component throws various warning in the dev console during development mode. There might be a minor bug in the implementation of this custom component. 

The warnings thrown in the console are:
1. Warning: <TableOfContent /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.
2. Warning: The tag <TableOfContent> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.

### Steps To Reproduce

1. Run `yarn dev` to start local instance in development mode
2. Go to `http://localhost:3000/learn/getting-started-step-by-step`
3. Check dev console

### Expected Behavior

There must not be any warnings in the dev console.

### Screenshots

<img width="767" alt="Screenshot 2024-06-13 at 3 56 42 PM (2)" src="https://github.com/json-schema-org/website/assets/77478658/bccf91f6-09b6-4052-8543-b5602adfa061">

### Device Information [optional]

```markdown
- OS: MacOS
- Browser: Google Chrome
- version:
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by DhairyaMajmudar** [comment]
Fixed this issue in PR #763  : )
