### ISSUE TITLE
🐛 Bug: ES versioning error in `StyledMarkdown.tsx` file

### ISSUE THREAD

**Issue by DhairyaMajmudar** [json-schema-org/website#795]
### Describe the bug

File inspecting the `StyledMarkdown.tsx` file it is found that there's a ES versioning error created due to use of named capturing groups like `<label>` and `<markdown>`

### Steps To Reproduce

1. Navigate to file
2. Check the  errors in vscode problems section  

### Expected Behavior

There must be no errors 

### Screenshots

![image](https://github.com/user-attachments/assets/a01f1056-0b8e-446c-b12c-73d9e2b38f92)

![image](https://github.com/user-attachments/assets/78018ec1-6b14-40ea-8dc0-1a814514111e)

### Device Information [optional]

```markdown
- OS: Linux (Debian)
- Browser: Firefox
- version: Latest
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by DhairyaMajmudar** [comment]
The fix for this issue is to update the `target` field in `tsconfig.json` file : )

**Comment by harshsbhat** [comment]
hey can you close this issue as you have solved it already
