### ISSUE TITLE
[📝 Docs]: Fuse documents and create a single comprehensive tutorial

### ISSUE THREAD

**Issue by valeriahhdez** [json-schema-org/website#804]
### What Docs changes are you proposing?

The information contained in [Creating your first schema](https://json-schema.org/learn/getting-started-step-by-step) and [The basics](https://json-schema.org/understanding-json-schema/basics) is repetitive. We will use the best parts of each document and create a single comprehensive beginner tutorial that is going to live in the new Introduction section of the new documentation structure - issue #790 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by benjagm** [comment]
I like the idea. Thanks

**Comment by kwennB** [comment]
### New proposed Outline for the fusing tutorial 

#### Creating your first JSON Schema

Table Content
- Creating your first schema / the basis into text 
- Introduction to JSON Schema / Hello World 
- Overview  ⇒ Example (The overview would be re-worded to Example)
- Creating a schema definition / Declaring a JSON Schema 
- The type keyword 
- Define properties 
- Create a nested data structure 
- Declaring a unique Identifier 
- Add an external reference 
- Validate a JSON Schema
- What next

What do you think? CC: @valeriahhdez @benjagm

**Comment by valeriahhdez** [comment]
todo: Organize the tutorial's content by heading/section and put which content you'll use inside each section. This will help visualize the final structure of the tutorial. 
For example: 
Bakcground
This section will reuse information contained in the introductory paragraphs of The basics and Create your first schema tutorials. 

suggestion: Use TGDP tutorial template: https://gitlab.com/tgdp/templates/-/blob/main/tutorial/template-tutorial.md?ref_type=heads
Please remember to acknowledge the project if you do use it. 

suggestion: Using TGDP template, you can leave the overview and let readers know this will be the result of the tutorial. 

"In this tutorial, you'll learn to create a product catalog that stores its data using JSON objects, like the following:"

**Comment by kwennB** [comment]
Thank you so much for the awesome feedback @valeriahhdez. Could you take a look at the updated version? Thank you.

**Comment by valeriahhdez** [comment]
lgtm

**Comment by kwennB** [comment]
Awesome! Thank you.

**Comment by valeriahhdez** [comment]
Just a minor observation, no prerequisites are needed to create JSON schemas so you can remove the "Before you start" section

**Comment by benjagm** [comment]
I suggest to be much more conservative with the proposal. The current getting started guide "Creating your first schema" has a lot of great content and I think is working fine. My proposal is to keep the "Creating your first schema" as the main content here and add the information that is missing compared with The basics... if there is any and then remove the basics page and create a redirect to the "Creating your first schema"  page.

Regarding the new structure proposal:
Do we need a Background(1) and Example(4) sections in the current getting started guide? I am not sure about it. I think we need to discuss this in a team meeting.

**Comment by benjagm** [comment]
After some additional consideration I think we should not fuse these 2 pages. The basics page is not a guide and I think it plays a key role as introduction in the reference section before all the keywords sections.

**Comment by kwennB** [comment]
As agreed in our last docs meeting, there was no need to fuse the [Creating your first schema](https://json-schema.org/learn/getting-started-step-by-step) and [The basics](https://json-schema.org/understanding-json-schema/basics), so I will close this issue now.
