### ISSUE TITLE
✨ Enhancement: It well be great to provide a keywords page

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#815]
### Is your feature request related to a problem? Please describe

We don't have a list of keywords in a single page and users will benefit from it.

### Describe the solution you'd like

Taking advantage of the work done by the GSoD team reviewing the keywords, I'd like to provide a webpage with a list of all keywords and the links of pages referencing them. The list is available in this doc.

[Identify Keywords - JSON Schema Reference.pdf](https://github.com/user-attachments/files/16335092/Identify.Keywords.-.JSON.Schema.Reference.pdf)

The page should be totally data driven so we'll create first a yaml file in the data folder each keyword and the links (text+url). Once we have the data we'll build the page with a structure like this:

Title: JSON Schema Keywords
Description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat

(List of keywords sorted alphabetically)

* Keyword 1 (Link to the keyword in Learn JSON Schema)
  * [Link 1](#)
  * [Link N](#)
* Keyword 2
  * [Link 1](#)
  * [Link N](#)
* Keyword N
  * [Link 1](#)
  * [Link N](#)

### Are you working on this?

Yes

**Comment by gregsdennis** [comment]
This work has already been done; it's just not on our website.  It's @jviotti's Learn JSON Schema.

**Comment by benjagm** [comment]
This is slightly different. This is a way to see a keyword's content in our docs.

**Comment by gregsdennis** [comment]
> a keyword's content

What do you mean by this?

**Comment by gregsdennis** [comment]
How does https://www.learnjsonschema.com/2020-12/meta-data/default/ not do that?  It can sort by vocab or alphabetically, and it provides a lot of detailed info.  Probably wouldn't be too hard to add links to the docs.

**Comment by benjagm** [comment]
We are convinced about the benefit about the new page we are proposing. I see your point, however any language documentation requires a page with a list of keywords and the linked content, so we will provide ours, complementary to Learn JSON Schema.

**Comment by jviotti** [comment]
I think a complementary list doesn't hurt. Quite the opposite, I think it helps both projects. I can link to it from learnjsonschema.com and vice-verse if wanted.
