### ISSUE TITLE
✨ Enhancement : Allow your payment processor to authorize prepaid cards for sponsors

### ISSUE THREAD

**Issue by AymarN** [json-schema-org/website#825]
### Is your feature request related to a problem? Please describe

It is related to a payment which was declined through a prepaid AMEX card.

### Describe the solution you'd like

Whether there is a way to implement a solution for the prepaid credit cards which are not linked to a personal bank account. From my point of view, the problem may come from the credit card processor. If there is a way to adapt it to prepaid credit cards which are anonymous. 
I put on a link to the log file regarding that issue :
https://www.dropbox.com/scl/fi/748wkioazemdeey931ue1/github-json-schema-log.com?rlkey=i2yw114bdwbi5k6vy9h84jn6r&st=e0me5bi7&dl=0 

### Describe alternatives you've considered

You may provide other ways of payments which do not require the credit cards to be systematically linked to a bank account.

### Additional context

There are alternative means of payment such as paypal as well that may help a sponsor.

### Are you working on this?

Yes

**Comment by AymarN** [comment]
You may find below the error message.
![Error-Message-prepaid-credit-card](https://github.com/user-attachments/assets/80b3b438-0019-4cc7-808d-f9a4655d555a)

**Comment by gregsdennis** [comment]
Hello, @AymarN!  Is this an error that occurred on our site, https://json-schema.org, or on our Open Collective site, https://opencollective.com/json-schema?

I don't believe we accept payments on our site, which is what this repo is for, and (to my knowledge) we don't control what payment methods Open Collective supports.  This may be an issue you need to take up with them. 

cc: @benjagm @Relequestual

**Comment by AymarN** [comment]
Dear Sir,
The problem is reported on https://github.com/json-schema-org. Let me check on https://json-schema.org and https://opencollective.com/json-schema and get back to you as soon as I may.
Thank you for your answer.

**Comment by AymarN** [comment]
@gregsdennis 
There are two links that you gave. The first one does not allow the payment. The second one is operating. The contribution went through. 

On https://json-schema.org/ , I am redirected to the link that I gave before https://github.com/json-schema-org. The payment does not go through that link. On https://opencollective.com/json-schema, the contribution goes through.

Let me raise a concern, if you do not accept payments on https://github.com/sponsors/json-schema-org, you may perform a redirection to https://opencollective.com/json-schema to avoid any kind of bafflement.

I am hoping to hear from you soon.
Thank you.
![Open_collective_payment](https://github.com/user-attachments/assets/7c9bfdd3-76eb-4491-b9f0-03def69e4170)

**Comment by gregsdennis** [comment]
Oh, GitHub _Sponsors_.  That makes sense. 

This is going to be an issue that you'll need to raise with GitHub themselves.  The payment experience belongs to them.

**Comment by AymarN** [comment]
Thank you very much for the link. It is convenient. I will therefore reach out to GitHub for further details.

**Comment by jdesrosiers** [comment]
Thanks for your donation @AymarN! Sorry it was more difficult than it could have been.

**Comment by AymarN** [comment]
According to our conversation, let me close the issue and redirect it to Github.
Thank you.
