### ISSUE TITLE
[📝 Docs]: Update improving documentation section of contributing guide

### ISSUE THREAD

**Issue by valeriahhdez** [json-schema-org/website#830]
### What Docs changes are you proposing?

Add information on processes for improving documentation or proposing changes. 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
We already have https://github.com/json-schema-org/website/blob/main/CONTRIBUTING.md.  Were you thinking of something different?

**Comment by benjagm** [comment]
> We already have https://github.com/json-schema-org/website/blob/main/CONTRIBUTING.md. Were you thinking of something different?

This is the contributing guide for documentation. Will be added a sub-element of the main contributing guide.

**Comment by valeriahhdez** [comment]
I am closing this issue as we have merged the new contribution guide for documentation

**Comment by valeriahhdez** [comment]
I am closing this issue as we have merged the new contribution guide for documentation
