### ISSUE TITLE
Sphinx inventory is missing for UJS

### ISSUE THREAD

**Issue by Julian** [json-schema-org/website#84]
This link: https://json-schema.org/understanding-json-schema/objects.inv

on the old website was a [Sphinx inventory](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) for Understanding JSON Schema.

It now appears to be a 404.

I know we don't plan on sticking with Sphinx, or perhaps have already switched away from it as part of the website move and I simply didn't know the 2 were happening together -- though regardless, even if we use some other documentation tool, it would be nice to at least consider continuing to provide this file or an equivalent. Its purpose is pretty "universal" in nature -- it's meant to help automated tooling understand where links should go within the site, so other documentation systems likely still could be coerced into producing one.

(This issue essentially breaks [sphinx-json-schema-spec](https://github.com/python-jsonschema/sphinx-json-schema-spec/) and transitively [python-jsonschema's](https://github.com/python-jsonschema/jsonschema/) documentation, though if it turns out we've now officially moved over to something else obviously I'll rework those projects.)

**Comment by Relequestual** [comment]
We wanted to have the site and all pages managed under the same framework and tooling, and using markdown.
I had no idea we were publishing a Sphinx inventory.

Can you construct one from the markdown we have in the website repo now? A quick google tells me the answer is maybe yes. If so, I suspect you're going to need to do the legwork on this one 😅. (Or at least, I suspect there will be python involved.)

**Comment by benjagm** [comment]
Is this feasible with the new website's stack?

**Comment by Julian** [comment]
Probably yes although I haven't given it any time looking into it yet -- probably would keep this as low priority since I'm the primary user of it is my guess :D

**Comment by praveen-rikhari** [comment]
Hii @Julian do you think this is still relevant did we come up with a solution for [sphinx-json-schema-spec](https://github.com/python-jsonschema/sphinx-json-schema-spec/) and [pythons-json-schema](https://github.com/python-jsonschema/jsonschema/)?? I can take this down if we want this page to come back to the new website stack

**Comment by Julian** [comment]
Yes I think it's still relevant!

**Comment by nikhilyadav24** [comment]
Hey @benjagm , Please assign this to me.

**Comment by benjagm** [comment]
Sure @nikhilyadav24 . Go ahead. Feel free to ask as many questions as you may need.
