### ISSUE TITLE
🐛 Bug: Some SVG images are not loading correctly in dark mode on the case studies page.

### ISSUE THREAD

**Issue by aialok** [json-schema-org/website#850]
### Describe the bug

- Some SVG images are not loading in correct theme in dark mode on the case studies page.
-  https://json-schema.org/overview/case-studies

### Steps To Reproduce

- Visit https://json-schema.org/overview/case-studies

### Expected Behavior

- It should render correctly in both light and dark mode.

### Screenshots

[Screencast from 2024-08-05 18-22-17.webm](https://github.com/user-attachments/assets/bee636ff-5bd1-4bcb-ad6b-c520de119ca4)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by bharathz8** [comment]
Hi @aialok 

I am interested in contributing to this issue. can I start to work on it ?

Thank you!

**Comment by aialok** [comment]
> They are loading correctly. The SVGs we are using are black. That is the reason they are not visible after switching to dark mode.

Yes, they are loading correctly, but we need to use dark theme SVGs for some images.

**Comment by harshsbhat** [comment]
Sure, I can work on this. I don't need an assignment. But want to know that is it discussed and ready to work.

**Comment by Michael-Obele** [comment]
Hi @benjagm is this issue still available?

**Comment by harshsbhat** [comment]
@Michael-Obele At least I am not working on this issue.

**Comment by benjagm** [comment]
We can use the white version of the log when in dark mode. We have this already implemented on the landing page.

**Comment by benjagm** [comment]
Can we assign this issue to you Michael?

**Comment by Michael-Obele** [comment]
> Can we assign this issue to you Michael?

Yes. I'll be glad to help.

**Comment by DhairyaMajmudar** [comment]
Hi @Michael-Obele any update on this issue : )

**Comment by Michael-Obele** [comment]
Yeah, I'll finish it up this week. Been a bit pressed with work.

**Comment by Michael-Obele** [comment]
> Hi @Michael-Obele any update on this issue : )

So yeah, I'm done with the changes but I've been hitting errors when trying to commit (even to my own repo) so that's what's delaying me. I would love some help with this if you don't mind

**Comment by Michael-Obele** [comment]
Nope, nevermind, I got it working, making a PR now.

**Comment by Michael-Obele** [comment]
Okay, PR open, @DhairyaMajmudar tell me what you think?

**Comment by DhairyaMajmudar** [comment]
> Okay, PR open, @DhairyaMajmudar tell me what you think?

Thank you for the PR, its working good, left few minor comments : )
