### ISSUE TITLE
[📝 Docs]: Spelling and Grammar Errors in README

### ISSUE THREAD

**Issue by KaranDasA1** [json-schema-org/website#866]
### What Docs changes are you proposing?

I noticed several spelling and grammar issues in the README file of the JSON Schema website repository. Addressing these issues will improve the clarity and professionalism of the documentation. Here are the specific issues I found:

Spelling:

"Enviroment" should be corrected to "Environment" in the "Setup Environment Variables" section.
Grammar:

Ensure all sentences are grammatically correct and clear.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DhairyaMajmudar** [comment]
Thanks for pointing this @KaranDasA1 🚀

**Comment by KaranDasA1** [comment]
> Thanks for pointing this @KaranDasA1 🚀
> 
> Edit: Would you like to be assigned and open a PR?

I’ve just submitted a pull request to correct a minor typographical error

**Comment by DhairyaMajmudar** [comment]
Thank you @KaranDasA1 for PR feel free to open more such issues  : )
