### ISSUE TITLE
✨ Enhancement: Ambassadors Program page

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#884]
We need to create a dedicated page for the [JSON Schema Ambassadors program](https://github.com/json-schema-org/community/tree/main/programs/ambassadors). This page will serve as a hub for information about the program, including how to apply and what the program entails and of course list the ambassadors.  In addition to the main page, we'll provide a second page to show the details and contributions of each ambassador.

Below are the detailed requirements based on the provided [prototype](#prototype).

### Requirements

1. **Header Section:**
   - Title: "Become a JSON Schema Ambassador"
   - Short description: "The JSON Schema Ambassadors Program recognizes the people who drive adoption, innovation, and knowledge sharing in the JSON Schema community."
   
2. **Buttons:**
   - "Become Ambassador" button: Should be prominent, leading to an application form and connect with this link: https://github.com/json-schema-org/community/tree/main/programs/ambassadors#become-an-json-schema-ambassador
   - "Learn More" button: This should link to a section or page with more details about the program. This is the link to use: https://github.com/json-schema-org/community/tree/main/programs/ambassadors

3. **Content Sections:**

There should be multiple sections:
- Section 1 : Same card used in the Community page presenting the program.
- Section 2: Types of contributions: "Articles", "Talk", "JSON Schema Adopter", "Case study", "Video", "Book", "Technical Paper", "Initiative or Project", "Working group", "Community"
- Section 3: Ambassadors listing using the data provided here: https://github.com/json-schema-org/community/blob/main/programs/ambassadors/ambassadors.json
-Section 4: Final call to action to join the program.

### Technical Requirements

* Please make sure to use the Card component for generic Cards. For the ambassadors card feel free to create a new component.
* We have multiple pages reading json and rendering it using the card component, like the case studies, use cases or overview pages, make sure you follow a similar approach.
* The ambassadors json is available through github submodules. Just update the community submodule to get current version.

### Ambassador's details.

When clicking on one ambassador we can have a second page showing the Ambassador's contribution like Async API is doing. For reference: https://www.asyncapi.com/community/ambassadors/raphaeldelio

### Prototype:
<div id=prototype></>
Please check this prototype for reference of the main page layout.

[Ambassadors.pdf](https://github.com/user-attachments/files/16735998/Ambassadors.pdf)

![Ambassadors-1](https://github.com/user-attachments/assets/d9b8d5b9-e729-4461-9624-afedd195dbab)

### References:
We took inspiration from the AsyncAPI Ambassadors page:
* https://www.asyncapi.com/community/ambassadors
* https://www.asyncapi.com/community/ambassadors/raphaeldelio

**Comment by TheShiveshNetwork** [comment]
Hey, I am interested to work on this. Can this be assigned to me?

**Comment by benjagm** [comment]
Thanks a lot for your support @TheShiveshNetwork! Please go ahead

**Comment by Pavankumar07s** [comment]
Hi @benjagm , I'd like to enhance the design of this page with additional styling and also take part in creating it. Would it be possible for me to contribute?

**Comment by DhairyaMajmudar** [comment]
@TheShiveshNetwork any updates on this?

**Comment by techmannih** [comment]
@DhairyaMajmudar can I work on this issue?

**Comment by benjagm** [comment]
@Pavankumar07s Can you please work on a proposal for design enhancements and share it here first until @TheShiveshNetwork shares an update of their work?

**Comment by Pavankumar07s** [comment]
@DhairyaMajmudar working on design.

**Comment by Pavankumar07s** [comment]
Hey @DhairyaMajmudar I’ve completed part of the design enhancement using Figma. How should I propose the design? Should I share the image here or create a professional proposal in a PDF file? Also, can I start working on the implementation now?

**Comment by DhairyaMajmudar** [comment]
> Hey @benjagm @DhairyaMajmudar I’ve completed part of the design enhancement using Figma. How should I propose the design? Should I share the image here or create a professional proposal in a PDF file? Also, can I start working on the implementation now?

yeah you can share the Figma design link

**Comment by Pavankumar07s** [comment]
![Pavan sir-2.png](https://github.com/user-attachments/assets/67e785bf-f6ed-4221-be31-e6cd67a74076)

Here is the image and I am sending the link in few seconds.

**Comment by Pavankumar07s** [comment]
@DhairyaMajmudar  here is the link 
https://www.figma.com/design/my3mUfxMa9wmXgQDNTz3NS/Flow-chart?node-id=0-1&t=gj2ud48jHiazml3c-1

**Comment by DhairyaMajmudar** [comment]
@Pavankumar07s Thanks!! Designs are looking cool, can you pls. use the json schema theme and logos.
You can find the exact color code here https://github.com/json-schema-org/brand

**Comment by Pavankumar07s** [comment]
Hey @DhairyaMajmudar now I am implementing the design, thankyou for this opportunity .

**Comment by Pavankumar07s** [comment]
Hey @DhairyaMajmudar, I have a question. We're creating a new page with all the rest of the features. Do we need to establish a connection between the main page and our dedicated page, either through a section or a button, to allow navigation between them?

**Comment by DhairyaMajmudar** [comment]
> Do we need to establish a connection between the main page and our dedicated page, either through a section or a button, to allow navigation between them?

yep, you can add the link in navbar.

**Comment by Pavankumar07s** [comment]
@DhairyaMajmudar ohhk i got it.Thanks.

**Comment by Pavankumar07s** [comment]
Hi @DhairyaMajmudar, good evening! 
I just learned that the page we're creating for our Ambassador Program is related to the community section. This means we can link our dedicated Ambassador Program page within the community section. Do you think this is a good approach?
![Screenshot from 2024-10-21 17-48-05](https://github.com/user-attachments/assets/2e445649-01bf-4f04-ae1f-92b772c866fd)

**Comment by DhairyaMajmudar** [comment]
@Pavankumar07s Yeah it can be a good idea to add the link of ambassadors page with the ambassadors' program card (Think a bit about how it can be added either by using a button or something kinda similar)

**Comment by Pavankumar07s** [comment]
@DhairyaMajmudar 
1. We can use the navbar to navigate directly to the Ambassadors page.
2. On our website's landing page, we can create a dedicated card or event section to highlight the Ambassadors program. This section could be placed just below the "Welcome to the JSON Schema Community" banner.
![Screenshot from 2024-10-21 18-29-36](https://github.com/user-attachments/assets/03685b6a-d409-432c-a759-853fa1a996f6)
Like this above.
I will try comming up with more ideas.

**Comment by Pavankumar07s** [comment]
Hello @DhairyaMajmudar! Here's the latest status update for the feature:
1.Reviewed the code thoroughly, line by line.
2.Added a direct link in the navbar.
3.Created and added a new card on the landing page (including a custom PNG for a better look).
4.Currently working on the dedicated page with optimal code quality.
Have a look here ,is it looking awesome?
![Screenshot from 2024-10-30 23-50-44](https://github.com/user-attachments/assets/8b45237f-e944-4b18-87eb-272c50429b55)

**Comment by Pavankumar07s** [comment]
hii @benjagm @DhairyaMajmudar have a look on card design. Is it good or we need some changes?
![Screenshot from 2024-11-02 00-37-03](https://github.com/user-attachments/assets/81a2f492-14a6-42b1-a5a6-8b7cf1ef5a75)
![Screenshot from 2024-11-02 00-37-20](https://github.com/user-attachments/assets/78f58f39-ef55-4f2a-9103-6589663f200e)

**Comment by Pavankumar07s** [comment]
hii @DhairyaMajmudar there is some restriction on image of Andreas Eberhart and Ege Korkan.what should i do?
