### ISSUE TITLE
Setup plausible analytics

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#89]
We need to complete the Setup of plausible analytics.

**Comment by Relequestual** [comment]
Related https://github.com/json-schema-org/community/issues/300

**Comment by Relequestual** [comment]
We should be able to import historical data from Google Analytics! https://plausible.io/docs/google-analytics-import

**Comment by Relequestual** [comment]
We can make our stats public: https://plausible.io/docs/visibility
Do we want to do this?
