### ISSUE TITLE
Improve Docs and Spec navigation

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#9]
Draft content Structure
- Overview
    * What is JSON Schema (New)
    * Use Cases (New)
    * Roadmap (New optional)
    * Vision (New)
    * Release and Versioning (New)
    * Support and Community (New)
    * FAQ (This is new)

- Getting Started
    *  Getting started [old](https://github.com/json-schema-org/json-schema-org.github.io/blob/main/learn/index.md).
        [Example](https://kubernetes.io/docs/setup/)
    * Creating a schema ([Existing](https://github.com/json-schema-org/website/blob/main/pages/learn/getting-started-step-by-step.md) getting started, but needs lots of work)
    * Examples
        * Miscellaneous examples (Needs work)
        * Modelling a file system (Needs work)
        * Other examples (Needs work)
- Tutorials: 

- Reference:
    * JSON Schema Glossary (Outdated)
    * Learn JSON Schema   (Link to https://www.learnjsonschema.com)
    * Understanding JSON Schema (Existing - The structure of the book)

- Specification
    * Overview (New)
    * Specification (Existing but poorly structured with multiple embedded sections. Requires analysis and break it into pieces)

**Comment by benjagm** [comment]
Made some changes in the docs structure and prepared this proposal of tools prioritization:

MVP1
 overview\What is JSON schema (New)
 learn\Getting started (https://json-schema.org/learn/)

MVP2
 learn\Creating a schema (https://json-schema.org/learn/getting-started-step-by-step.html)
 Examples: Improve format and structure

MVP3
 learn\Glossary (https://json-schema.org/learn/glossary.html) 

MVP4
 Specification: 
 	- Improve format and structure. 
 	- Embed the old html format into the new format.

**Comment by mjgutermuth** [comment]
I think this looks good. One small change I'd suggest is in the "Reference" section—I think this could be more broad than just that external link. I would suggest nesting the JSON Schema Glossary and Understanding JSON Schema in this section.

So it would look like this:

- Reference
  - JSON Schema Glossary
  - Learn JSON Schema
  - Understanding JSON Schema

I think this would make the navigation cleaner and keep the tutorial/how-to content easy to find.

I also think "Support and Community" could be its own top-level item, and FAQ could fall under that. I think it's okay either way, though.

**Comment by benjagm** [comment]
Thanks Melinda. I updated the taxonomy to reflect your feedback and I validated with the team both, the taxonomy and the releases so we have green light to start with Release 1.

**Comment by benjagm** [comment]
Completed
