### ISSUE TITLE
Understanding JSON Schema presence in the sidebar is slightly awkward

### ISSUE THREAD

**Issue by Julian** [json-schema-org/website#90]
The UJS links on docs pages [e.g. here](https://json-schema.org/learn/getting-started-step-by-step):

<img width="361" alt="Screenshot 2023-10-03 at 3 09 39 PM" src="https://github.com/json-schema-org/website/assets/329822/0bd2fff6-e922-4b77-831b-e5996fb7b880">

are slightly odd to me for 2 minor reasons:

* they expand fully across all pages of the book, so they take up lots of space in the sidebar, rather than simply having one link to UJS there.
* they're in the "References" section, even though I wouldn't think of UJS as a reference (though I'll be honest it's been years since I've read it). Maybe it's me that's misremembering, I'll go flip through it, but is it not meant to be read cover to cover? It's just meant to be individual pages?

(I haven't looked to see if this was discussed elsewhere, so feel free to close if so).

**Comment by benjagm** [comment]
I updated the style of the Reference menu. Please let me know if it improved:

https://bf757ac8.website-2v2.pages.dev/understanding-json-schema

**Comment by Julian** [comment]
Looks like an improvement to me!
