### ISSUE TITLE
Blog not rendering numbered lists properly

### ISSUE THREAD

**Issue by gregsdennis** [json-schema-org/website#92]
In my [static analysis post](https://json-schema.org/blog/posts/schema-static-analysis#root-schema-dynamics), I found that a markdown numbered list isn't rendering correctly.

<img width="732" alt="image" src="https://github.com/json-schema-org/website/assets/2676804/a2806f09-05c4-41ad-8b17-a5a22110fe57">

It looks like it recognizes that the formatting is supposed to be different because the text is slightly darker, but the whole "this is a list" thing is missing.  Here's the code:

https://github.com/json-schema-org/website/blob/2e5d88a5f1ec49a6b45b18fb8608a5bd9368a75b/pages/blog/posts/schema-static-analysis.md?plain=1#L138-L143

(It'd be great for us to have the old site somewhere for reference.)

**Comment by gregsdennis** [comment]
Looks like it's just numbered lists.  In the previous section, there's an unordered list that renders fine.

<img width="379" alt="image" src="https://github.com/json-schema-org/website/assets/2676804/1cd4e094-ea91-4f5c-83eb-479d4065fb59">

Secondly, why is the font color different?

**Comment by benjagm** [comment]
I Greg. Thanks for raising this issue. I made a small change to improve the rendering of the sorted lists. You can see the result here:
https://5f351229.website-2v2.pages.dev/blog/posts/schema-static-analysis

**Comment by gregsdennis** [comment]
Looks good
