### ISSUE TITLE
✨ Enhancement: Differenciate external links in the docs sidebar

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#942]
### Is your feature request related to a problem? Please describe

It would be great to find a way to differentiate those links in the sidebar pointing to external links:

![Screenshot 2024-09-12 at 16 20 39](https://github.com/user-attachments/assets/6bc48484-2796-48d9-ba9d-b17da5f23ad6)

In this image Tour of JSON Schema is an external link.

The component used for this type of link is DocLinkBlank so it should be really easy to modify the style:
````
          <DocLinkBlank
            uri='https://www.learnjsonschema.com/'
            label='Learn JSON Schema'
            setOpen={setOpen}
          />
````

### Describe the solution you'd like

Maybe adding an [external link icon](https://www.flaticon.com/free-icons/external-link) at the end of the text should be enough. For reference [here](https://css-irl.info/styling-external-links-with-attribute-selectors/)

### Are you working on this?

No

**Comment by Vishv0407** [comment]
@benjagm Can you please assign this task to me ?

**Comment by benjagm** [comment]
@iamAyushChamoli please go ahead

**Comment by AkshataABhat** [comment]
can i pls be assigned to this issue?

**Comment by iamAyushChamoli** [comment]
@benjagm Please Check and verify

**Comment by iamAyushChamoli** [comment]
So I checked that the project was throwing a build error. I fixed this issue on my local machine but I'm pretty sure that it will throw an error again if I push this branch along with the previous branches that haven't been approved/merged yet. Can you please go back to my previous branches, see if they fixed their corresponding issues and merge them so that I can push this branch without conflicts or errors as well? Thanks

**Comment by iamAyushChamoli** [comment]
@benjagm it got a little messy in the last PR so I created a new branch for the same. Please check this one out and lmk

**Comment by JeelRajodiya** [comment]
I just noticed, we have not implemented styles for the dark mode on the redirect icon, 
![image](https://github.com/user-attachments/assets/2fcdbe17-bf62-4bda-bfd3-4fb73f01773a)

**Comment by benjagm** [comment]
Thanks @JeelRajodiya !! We are working on it with #972
