### ISSUE TITLE
Add justinrainbow/json-schema to tooling page

### ISSUE THREAD

**Issue by DannyvdSluijs** [json-schema-org/website#944]
### Tool Name

justinrainbow/json-schema

### Tool Description

A PHP Implementation for validating JSON Structures against a given Schema with support for Schemas of Draft-3 or Draft-4

### Action Type

- [X] Add Tool
- [ ] Modify Tool

### Tooling Types

- [X] validator
- [ ] hyper-schema
- [ ] benchmarks
- [ ] documentation
- [ ] LDO-utility
- [ ] code-to-schema
- [ ] data-to-schema
- [ ] model-to-schema
- [ ] schema-to-types
- [ ] schema-to-code
- [ ] schema-to-web-UI
- [ ] schema-to-data
- [ ] util-general-processing
- [ ] util-schema-to-schema
- [ ] util-draft-migration
- [ ] util-format-conversion
- [ ] util-testing
- [ ] editor
- [ ] editor-plugins
- [ ] schema-repository
- [ ] linter
- [ ] linter-plugins

### Languages

PHP

### Environments

PHP >= 7.2

### Creators

Justin Rainbow - https://github.com/justinrainbow

### Maintainers

Erayd - https://github.com/erayd
David Porter - https://github.com/bighappyface
Jordi Boggiano - https://github.com/Seldaek
Danny van der Sluijs - https://github.com/DannyvdSluijs

### License

MIT

### Source Repository URL

https://github.com/jsonrainbow/json-schema

### Homepage URL

https://github.com/jsonrainbow/json-schema

### Supported Dialects

- [ ] 1
- [ ] 2
- [X] 3
- [X] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 2019-09
- [ ] 2020-12

### Bowtie Compliance Testing

php-justinrainbow-json-schema

### Landscape Information

logo: https://avatars.githubusercontent.com/u/170307068?s=200&v=4

**Comment by heysujal** [comment]
Hi @benjagm , I would like to work on this issue.

**Comment by benjagm** [comment]
Hey @heysujal thanks a lot for your support!!

The action here is to make a change in the tooling data file to get this tool added. The PR should be similar to this one:
https://github.com/json-schema-org/website/pull/941

Ping me if you have doubts.
