### ISSUE TITLE
🐛 Bug:  Missing Dark Mode Styles for Redirect Icon

### ISSUE THREAD

**Issue by Vishv0407** [json-schema-org/website#972]
### Describe the bug

 The redirect icon on the left navbar does not have appropriate styles for dark mode. As a result, it may not be visible or appear inconsistent with the overall dark mode theme.

### Steps To Reproduce

1. Navigate to the Specification/docs page.
2. Open dropdown of Getting Started.
3. Switch to dark mode.
4. Observe the redirect icon.

### Expected Behavior

 The redirect icon should have a defined style that complements the dark mode theme, ensuring visibility and consistency.

### Screenshots

![bug1](https://github.com/user-attachments/assets/3c07f9ee-9cfa-4ce4-be24-b09d9ecd4f5a)
![image](https://github.com/user-attachments/assets/bf4e367d-d0cd-4f91-80dc-8e0bbac08bae)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

**Comment by Vishv0407** [comment]
@benjagm I would like to work on it.

**Comment by benjagm** [comment]
Thanks Vish. Please go ahead. Please check the logic we use to change other icons in the sidebar loke the section icons. Ping me if you have any doubt.
