### ISSUE TITLE
Add Bowtie report URL for @cfworker/json-schema

### ISSUE THREAD

**Issue by vaibhavrajsingh2001** [json-schema-org/website#976]
### Tool Name

@cfworker/json-schema

### Tool Description

@cfworker/json-schema also has a Bowtie report page, and its URL should be added on the json-schema.org/tools page.

<img width="996" alt="image" src="https://github.com/user-attachments/assets/dcdd2b43-6911-4399-b989-8d9998dafc1b">

Bowtie report page: https://bowtie.report/#/implementations/js-json-schema

### Action Type

- [ ] Add Tool
- [X] Modify Tool

### Tooling Types

- [X] validator
- [ ] hyper-schema
- [ ] benchmarks
- [ ] documentation
- [ ] LDO-utility
- [ ] code-to-schema
- [ ] data-to-schema
- [ ] model-to-schema
- [ ] schema-to-types
- [ ] schema-to-code
- [ ] schema-to-web-UI
- [ ] schema-to-data
- [ ] util-general-processing
- [ ] util-schema-to-schema
- [ ] util-draft-migration
- [ ] util-format-conversion
- [ ] util-testing
- [ ] editor
- [ ] editor-plugins
- [ ] schema-repository
- [ ] linter
- [ ] linter-plugins

### License

MIT

### Source Repository URL

https://github.com/cfworker/cfworker/tree/main/packages/json-schema

### Supported Dialects

- [ ] 1
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 2019-09
- [ ] 2020-12

### Bowtie Compliance Testing

js-json-schema

**Comment by DarhkVoyd** [comment]
I’ll be working on this issue.
