### ISSUE TITLE
🐛 Bug:  ToolingDetailModal doesn't render logo when provided url instead of path

### ISSUE THREAD

**Issue by heysujal** [json-schema-org/website#988]
### Describe the bug

I came across this bug while working on #987
The current implementation of ToolingDetailModal uses logos from the public directory. But what if the logo is not already present in the `public/img/tools/logos/` directory? 

https://github.com/json-schema-org/website/blob/8551ee618b4bb34cd5b634a0f2ad5bfe35b9da8e/pages/tools/components/ToolingDetailModal.tsx#L76

When someone proposes to add a tooling (e.g. validator) and provide a URL for the logo using `tooling-data.yaml`, then our component is not able to render it as it appends the URL of the image to the current path which results in a 404 error for that image.
For example, the URL becomes : 
`http://localhost:3000/img/tools/logos/https:/avatars.githubusercontent.com/u/170307068?s=200&v=4`

Suggested Fix
As of now in the whole `tooling-data.yaml` there is only one entry of logo, so we should only support links by making changes to `next.config.js` and allowing all remotePatterns. As for the one logo which is already present in the logos directory we can host it somewhere and get a link. Then the path can be replaced with the link for the logo in the corresponding entry for that tool (json-everything)

### Steps To Reproduce

1. Go to `tooling-data.yaml`
2. create a new entry or update existing one which has a `logo` property in it and put URL of the logo.
3. Now go to the tooling page and search for that tool and click the search result.
4. The logo doesn't load.

### Expected Behavior

The logo should load properly.

### Screenshots

Taken from #987
![image](https://github.com/user-attachments/assets/acec7df8-30d0-499c-964d-4a0cbc5deb29)

### Device Information [optional]

```markdown
- OS: macOS
- Browser: Chrome
- version: 129.0.6668.71
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

Yes

**Comment by heysujal** [comment]
I want to work on this issue.

**Comment by DarhkVoyd** [comment]
Hello @heysujal , thanks for creating this issue.

This behaviour was a design choice. IMO, all assets should be hosted as part of the project. This ensures reliability and reduces the risk of broken links, and won't require moderation. Instead, I believe we should update the schema to include that the logos are expected to be in the public directory. What do you think?

**Comment by heysujal** [comment]
Yeah, that makes sense. I did thought about reliability if logos are present in public directory, but wasn't sure how the upload process would work.
I mean if someone makes a PR to add a tooling then they should also commit a logo in the public directory, right?

**Comment by DarhkVoyd** [comment]
Yes, the logo should be added to the tooling logos directory through a PR.

**Comment by heysujal** [comment]
Okay, got it. I will close this issue.

**Comment by DarhkVoyd** [comment]
If not already, I think we should update the `tooling-data.schema.json` to exactly mention where the logos are supposed to go and that they should not be an external path. Could you please create an issue for this? What do you think?
