### ISSUE TITLE
[📝 Docs]: Improvement in installation instructions

### ISSUE THREAD

**Issue by heysujal** [json-schema-org/website#989]
### What Docs changes are you proposing?

I would like to contribute to `INSTALLATION.md` by improving the installation instructions.
The installation guide is great but it could be better. 
Some things that I think can be clarified or added are :

- Adding step mentioning to fork the repo.
- Add the `git clone ` command/instruction before the `git submodule init`
- Give the link to [Algolia](https://www.algolia.com/) to sign up and get credentials for the `env`.
- Since the Algolia dashboard has two types of API keys which are `Admin API Key` and `Search API Key` we can mention that the contributor needs to get the `Search API Key`.

I want to understand if these changes are worth making. If they are, I would like to work on this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by notEthan** [comment]
Forking the repo isn't necessary to install (although I suppose most people installing are likely to be contributing, which does need a fork).

**Comment by 29deepanshutyagi** [comment]
i want to work on this issue @benjagm  ,kindly assign me

**Comment by 29deepanshutyagi** [comment]
i want to work on this issue ,kindly assign me this issue  @benjagm ,if this issue is opened and no one is assigned

**Comment by gregsdennis** [comment]
Algolia?  Is this something new or are we already using this?

If it's something new, I'd like to understand why we need it.

**Comment by heysujal** [comment]
@gregsdennis If I remember correctly it is being used for the search functionality.

**Comment by benjagm** [comment]
Hi everyone. I'd like to clarify that we are using DocSearch that this an opensource solution from Algolia and not Algolia. The second point is this step is not necessary to run this in local environment, this is why we are merged this PR https://github.com/json-schema-org/website/pull/1090 to make it clear. For this reason I think is better to close this issue.

**Comment by valeriahhdez** [comment]
Closed this issues per @benjagm 's suggestion.
